// <auto-generated />
using Lucent.Core;

namespace Lucent.Icons.Lucide;

/// <summary>Finite typed Lucide artwork imported from the pinned upstream revision.</summary>
public static class LucideIcons
{
    /// <summary>The exact upstream Git revision from which the artwork was imported.</summary>
    public const string UpstreamRevision = "ba95e4c988b1e1b39cf5544e73b25a74b76816ee";

    /// <summary>Gets the archive Lucide icon.</summary>
    public static ImageSource Archive { get; } = Create("archive", "78c732e34e232db63af06a2330b4448045cfdf49b48b59f2d31922df54c7bb17", 340);
    /// <summary>Gets the arrow-left Lucide icon.</summary>
    public static ImageSource ArrowLeft { get; } = Create("arrow-left", "c5f4b88076108eb1a0d95336e1aa7e7bb1419a3a92af96f6247d88cd3456f933", 262);
    /// <summary>Gets the arrow-right Lucide icon.</summary>
    public static ImageSource ArrowRight { get; } = Create("arrow-right", "288397fdb73bb4f783cf9eabb726ff47357df1d4e3f1201dd748090579f108b9", 261);
    /// <summary>Gets the circle-check Lucide icon.</summary>
    public static ImageSource CircleCheck { get; } = Create("circle-check", "9711e045a5999f8a3b0782eb88e09b04e0559bc7b379dcc0a4ae645223e10345", 278);
    /// <summary>Gets the circle-dot Lucide icon.</summary>
    public static ImageSource CircleDot { get; } = Create("circle-dot", "c263f6a08a089c06ad40f408ad5da9100359ab52d379e6c571cd7c5bd74eaa87", 279);
    /// <summary>Gets the ellipsis Lucide icon.</summary>
    public static ImageSource Ellipsis { get; } = Create("ellipsis", "4f495cc72013ffdfec677f03b33a150f7b4dd741979283fd6853a09024bca112", 312);
    /// <summary>Gets the file-text Lucide icon.</summary>
    public static ImageSource FileText { get; } = Create("file-text", "52ca55846c202335fb870c8aa23e9345630ec10489303756d62e750f7109605c", 444);
    /// <summary>Gets the inbox Lucide icon.</summary>
    public static ImageSource Inbox { get; } = Create("inbox", "1838482c53d0846badef9be96fdcf7a167064241bd4891efa995c77ebec5f187", 388);
    /// <summary>Gets the link Lucide icon.</summary>
    public static ImageSource Link { get; } = Create("link", "4f3237183dcaabfac92f4e94c776a9a9e45c3c5e77a921061a6b34b61eb5413f", 359);
    /// <summary>Gets the list-filter Lucide icon.</summary>
    public static ImageSource ListFilter { get; } = Create("list-filter", "36b94082bd7f161244c06a27cdeea647cb99ee5b805183cbeaf7ac3155a7103b", 278);
    /// <summary>Gets the notebook-pen Lucide icon.</summary>
    public static ImageSource NotebookPen { get; } = Create("notebook-pen", "56705c35e839977bd6f133d7ca4e9c93a6eea563c89e4be125efd0a32e1fa041", 519);
    /// <summary>Gets the plus Lucide icon.</summary>
    public static ImageSource Plus { get; } = Create("plus", "7f6af73bf1ff6c4bca3f18351c8d1bdec6749c0c2530c4de5da85d520c21df17", 256);
    /// <summary>Gets the refresh-cw Lucide icon.</summary>
    public static ImageSource RefreshCw { get; } = Create("refresh-cw", "2e10dd403c85a24f163d59fc6151aa21147fe9402e1305dfc8979208caee8944", 392);
    /// <summary>Gets the search Lucide icon.</summary>
    public static ImageSource Search { get; } = Create("search", "283d371c2e433817bb9c0c8310caa6c77fa4177c0f4f1168d9c83b97af7389dc", 275);
    /// <summary>Gets the trash Lucide icon.</summary>
    public static ImageSource Trash { get; } = Create("trash", "27299f69ad7c6272be64b1b8e2d48cbd6dcf0ef0d4f92827a1affa945c91700e", 389);

    private static ImageSource Create(string name, string hash, long byteLength) =>
        ImageSource.FromAsset(
            new AssetReference(
                new AssetId("Lucent.Icons.Lucide", "icons/" + name + ".svg"),
                hash,
                byteLength,
                AssetFormat.Svg,
                () => Open(name),
                new AssetImageMetadata(24f, 24f)
            )
        );

    private static Stream Open(string name) =>
        typeof(LucideIcons).Assembly.GetManifestResourceStream(
            "Lucent.Icons.Lucide." + name + ".svg"
        ) ?? throw new InvalidOperationException("Missing embedded Lucide artwork: " + name);
}