<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.321" />
    <PackageVersion Include="SDL3-CS" Version="3.4.14.1" />
    <PackageVersion Include="SDL3-CS.Windows" Version="3.4.14.1" />
    <PackageVersion Include="SkiaSharp" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="4.151.1" />
  </ItemGroup>
</Project>
