param(
    [Parameter(Mandatory)] [string] $SourceDirectory,
    [string] $Revision = 'ba95e4c988b1e1b39cf5544e73b25a74b76816ee'
)

$ErrorActionPreference = 'Stop'
$project = Split-Path $PSScriptRoot -Parent
$selectionPath = Join-Path $project 'lucide-selection.json'
$selection = Get-Content -LiteralPath $selectionPath -Raw | ConvertFrom-Json
if ($selection.importerRevision -ne 'lucent-lucide-import-v1') {
    throw "Unsupported Lucide importer revision: $($selection.importerRevision)"
}
if ($Revision -cne $selection.revision) {
    throw "Lucide source revision must be the selected revision $($selection.revision)."
}
$sourceRoot = (Resolve-Path -LiteralPath $SourceDirectory).Path
$sourceRevision = (& git -C $sourceRoot rev-parse HEAD 2>$null)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($sourceRevision)) {
    throw 'Lucide import requires a Git checkout so its source revision can be verified.'
}
if ($sourceRevision.Trim() -cne $Revision) {
    throw "Lucide checkout HEAD is $($sourceRevision.Trim()); expected $Revision."
}
if (@($selection.icons).Count -eq 0 -or @($selection.icons | Sort-Object -Unique).Count -ne @($selection.icons).Count) {
    throw 'Lucide selection must be finite, nonempty, and unique.'
}

$assets = Join-Path $project 'Assets'
$null = New-Item -ItemType Directory -Force -Path $assets
$inventory = [Collections.Generic.List[object]]::new()
$members = [Collections.Generic.List[string]]::new()
foreach ($name in @($selection.icons | Sort-Object)) {
    if ($name -cnotmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$') { throw "Invalid Lucide icon name: $name" }
    $source = Join-Path $sourceRoot "icons/$name.svg"
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { throw "Missing selected Lucide icon: $name" }
    [xml] $document = Get-Content -LiteralPath $source -Raw
    $root = $document.DocumentElement
    if ($root.LocalName -ne 'svg' -or $root.GetAttribute('viewBox') -cne '0 0 24 24' -or
        $root.GetAttribute('width') -cne '24' -or $root.GetAttribute('height') -cne '24' -or
        $root.GetAttribute('fill') -cne 'none' -or $root.GetAttribute('stroke') -cne 'currentColor' -or
        $root.GetAttribute('stroke-width') -cne '2' -or $root.GetAttribute('stroke-linecap') -cne 'round' -or
        $root.GetAttribute('stroke-linejoin') -cne 'round') {
        throw "Selected artwork is not a canonical Lucide 24px currentColor SVG: $name"
    }
    $destination = Join-Path $assets "$name.svg"
    [IO.File]::WriteAllBytes($destination, [IO.File]::ReadAllBytes($source))
    $hash = (Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash.ToLowerInvariant()
    $length = (Get-Item -LiteralPath $destination).Length
    $member = (($name -split '-') | ForEach-Object { [Globalization.CultureInfo]::InvariantCulture.TextInfo.ToTitleCase($_) }) -join ''
    $members.Add((('    /// <summary>Gets the {0} Lucide icon.</summary>' + "`n" + '    public static ImageSource {1} {{ get; }} = Create("{0}", "{2}", {3});') -f $name, $member, $hash, $length))
    $inventory.Add([ordered]@{ name = $name; accessor = "LucideIcons.$member"; path = "icons/$name.svg"; sha256 = $hash; bytes = $length })
}

$known = @($selection.icons | ForEach-Object { "$_.svg" })
$unexpected = @(Get-ChildItem -LiteralPath $assets -File -Filter '*.svg' | Where-Object Name -cnotin $known)
if ($unexpected.Count) { throw "Unselected Lucide assets remain: $($unexpected.Name -join ', ')" }

$sourceCode = @"
// <auto-generated />
using Lucent.Core;

namespace Lucent.Icons.Lucide;

/// <summary>Finite typed Lucide artwork imported from the pinned upstream revision.</summary>
public static class LucideIcons
{
    /// <summary>The exact upstream Git revision from which the artwork was imported.</summary>
    public const string UpstreamRevision = "$($selection.revision)";

$($members -join "`n")

    private static ImageSource Create(string name, string hash, long byteLength) =>
        ImageSource.FromAsset(
            new AssetReference(
                new AssetId("Lucent.Icons.Lucide", "icons/" + name + ".svg"),
                hash,
                byteLength,
                AssetFormat.Svg,
                () => Open(name),
                new AssetImageMetadata(24f, 24f)
            )
        );

    private static Stream Open(string name) =>
        typeof(LucideIcons).Assembly.GetManifestResourceStream(
            "Lucent.Icons.Lucide." + name + ".svg"
        ) ?? throw new InvalidOperationException("Missing embedded Lucide artwork: " + name);
}
"@
[IO.File]::WriteAllText((Join-Path $project 'LucideIcons.g.cs'), $sourceCode.Replace("`r`n", "`n"), [Text.UTF8Encoding]::new($false))

$output = [ordered]@{
    schema = 1
    pack = 'Lucent.Icons.Lucide'
    upstream = $selection.upstream
    version = $selection.version
    revision = $selection.revision
    importerRevision = $selection.importerRevision
    icons = $inventory
}
$json = $output | ConvertTo-Json -Depth 5
[IO.File]::WriteAllText((Join-Path $project 'lucide-icons.json'), $json.Replace("`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Imported $($inventory.Count) Lucide icons at $Revision."
