<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Reference
      Include="Microsoft.CodeAnalysis"
      HintPath="$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.dll"
    />
    <Reference
      Include="Microsoft.CodeAnalysis.CSharp"
      HintPath="$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.CSharp.dll"
    />
  </ItemGroup>
</Project>
