<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><Version>$(LucentLuiToolingVersion)</Version><IsAotCompatible>false</IsAotCompatible><IsTrimmable>false</IsTrimmable><EnableTrimAnalyzer>false</EnableTrimAnalyzer></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lucent.Lui.Compiler/Lucent.Lui.Compiler.csproj" />
    <ProjectReference Include="../Lucent.Renderer.Skia/Lucent.Renderer.Skia.csproj" />
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
  <ItemGroup>
    <None
      Include="$(MSBuildToolsPath)/../../LICENSE.txt"
      Link="notices/dotnet-LICENSE.txt"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(NuGetPackageRoot)/microsoft.codeanalysis.csharp.workspaces/5.9.0/ThirdPartyNotices.rtf"
      Link="notices/Roslyn-CSharp-Workspaces-NOTICES.rtf"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(NuGetPackageRoot)/microsoft.codeanalysis.workspaces.common/5.9.0/ThirdPartyNotices.rtf"
      Link="notices/Roslyn-Workspaces-Common-NOTICES.rtf"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(NuGetPackageRoot)/microsoft.codeanalysis.workspaces.msbuild/5.9.0/ThirdPartyNotices.rtf"
      Link="notices/Roslyn-Workspaces-MSBuild-NOTICES.rtf"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(NuGetPackageRoot)/microsoft.build/17.14.28/notices/THIRDPARTYNOTICES.txt"
      Link="notices/MSBuild-NOTICES.txt"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(NuGetPackageRoot)/system.security.cryptography.xml/10.0.11/THIRD-PARTY-NOTICES.TXT"
      Link="notices/dotnet-Cryptography-NOTICES.txt"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
