<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><Version>$(LucentLuiToolingVersion)</Version><IsAotCompatible>false</IsAotCompatible><IsTrimmable>false</IsTrimmable><EnableTrimAnalyzer>false</EnableTrimAnalyzer></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Lucent.Lui.Compiler/Lucent.Lui.Compiler.csproj" /><PackageReference Include="Microsoft.CodeAnalysis.CSharp" /></ItemGroup>
</Project>
