namespace Lucent.Compiler.CodeGeneration;

internal static class CSharpEmitter
{
    public static string Emit(BoundCounterModel model, string sourcePath)
    {
        var writer = new CodeWriter();
        var typeName = $"{model.ComponentName}Component";
        var stateField = $"_{model.StateName}";

        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("// <auto-generated />");
        writer.Line($"// Generated by Lucent.Compiler from {Path.GetFileName(sourcePath)}.");
        writer.Line();
        writer.Line("using Avalonia.Controls;");
        writer.Line("using Avalonia.Interactivity;");
        writer.Line();
        writer.Line($"namespace {model.NamespaceName};");
        writer.Line();
        writer.Line($"internal sealed class {typeName} : IDisposable");
        writer.Line("{");
        writer.Indent();
        writer.Line("private Button? _button1;");
        writer.Line("private TextBlock? _text1;");
        writer.Line($"private int {stateField} = {model.InitialValue};");
        writer.Line("private bool _disposed;");
        writer.Line("private bool _mounted;");
        writer.Line();
        writer.Line("public Control Mount()");
        writer.Line("{");
        writer.Indent();
        writer.Line("ObjectDisposedException.ThrowIf(_disposed, this);");
        writer.Line();
        writer.Line("if (_mounted)");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            $"throw new InvalidOperationException(\"A {model.ComponentName} component can only be mounted once.\");");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("_mounted = true;");
        writer.Line();
        writer.Line("_text1 = new TextBlock();");
        EmitClassAssignment(writer, "_text1", model.CountTextClass);
        writer.Line();
        writer.Line("_button1 = new Button");
        writer.Line("{");
        writer.Indent();
        writer.Line($"Content = {model.ButtonTextLiteral},");
        writer.Unindent();
        writer.Line("};");
        EmitClassAssignment(writer, "_button1", model.ButtonClass);
        writer.Line("_button1.Click += OnButton1Click;");
        writer.Line();
        writer.Line("var root = new StackPanel");
        writer.Line("{");
        writer.Indent();
        writer.Line("Children =");
        writer.Line("{");
        writer.Indent();
        writer.Line("_text1,");
        writer.Line("_button1,");
        writer.Unindent();
        writer.Line("},");
        writer.Unindent();
        writer.Line("};");
        EmitClassAssignment(writer, "root", model.RootClass);
        writer.Line();
        writer.Line($"Set{UppercaseFirst(model.StateName)}({model.InitialValue});");
        writer.Line("return root;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("public void Dispose()");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (_disposed)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("if (_button1 is not null)");
        writer.Line("{");
        writer.Indent();
        writer.Line("_button1.Click -= OnButton1Click;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("_disposed = true;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private void OnButton1Click(object? sender, RoutedEventArgs e)");
        writer.Line("{");
        writer.Indent();
        writer.Line($"Set{UppercaseFirst(model.StateName)}({stateField} + {model.Increment});");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line($"private void Set{UppercaseFirst(model.StateName)}(int value)");
        writer.Line("{");
        writer.Indent();
        writer.Line($"{stateField} = value;");
        writer.Line();
        writer.Line("if (_text1 is not null)");
        writer.Line("{");
        writer.Indent();
        writer.Line($"_text1.Text = {model.CountTextExpression};");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");

        return writer.ToString();
    }

    private static void EmitClassAssignment(
        CodeWriter writer,
        string variable,
        string? className)
    {
        if (className is not null)
        {
            writer.Line($"{variable}.Classes.Add({ToCSharpString(className)});");
        }
    }

    private static string UppercaseFirst(string value) =>
        value.Length == 0
            ? value
            : char.ToUpperInvariant(value[0]) + value[1..];

    private static string ToCSharpString(string value) =>
        '"' + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal) + '"';
}
