using System.Globalization;
using Lucent.Compiler.Parsing;
using Lucent.Compiler.Styling;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lucent.Compiler.CodeGeneration;

internal static class GeneralCSharpEmitter
{
    public static string Emit(
        BoundComponentModel model,
        string sourcePath,
        string sourceText,
        BoundStyleSheet? styles = null)
    {
        var source = new SourceDocument(sourceText, sourcePath);
        var writer = new CodeWriter();
        var controls = Flatten(model.Root).ToArray();
        var fields = controls
            .Select((control, index) => (control, index: index + 1))
            .ToArray();
        var regions = fields
            .SelectMany(field => field.control.Members
                .OfType<BoundForEachMember>()
                .Select(loop => (field.control, parentIndex: field.index, loop)))
            .Select((region, index) => new BoundRegion(
                region.control,
                region.parentIndex,
                region.loop,
                index + 1))
            .ToArray();
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("// <auto-generated />");
        writer.Line($"// Generated by Lucent.Compiler from {Path.GetFileName(sourcePath)}.");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        if (regions.Length > 0)
        {
            writer.Line("using System.Linq;");
        }
        writer.Line("using Avalonia.Controls;");
        writer.Line("using Avalonia.Interactivity;");
        writer.Line("using Lucent.Runtime;");
        if (styles?.Rules.Count > 0)
        {
            writer.Line("using Avalonia.Styling;");
        }
        foreach (var usingDirective in model.Usings
                     .Where(directive =>
                         directive is not "using System;" and
                         not "using System.Collections.Generic;" and
                         not "using System.Linq;" and
                         not "using Avalonia.Controls;" and
                         not "using Avalonia.Interactivity;" and
                         not "using Lucent.Runtime;")
                     .Distinct(StringComparer.Ordinal))
        {
            writer.Line(usingDirective);
        }
        writer.Line();
        writer.Line($"namespace {model.NamespaceName};");
        writer.Line();
        writer.Line($"internal sealed class {model.ComponentName}Component : IDisposable");
        writer.Line("{");
        writer.Indent();

        foreach (var (control, index) in fields)
        {
            writer.Line($"private {control.TypeName}? _control{index};");
        }

        foreach (var region in regions)
        {
            writer.Line(
                $"private readonly Dictionary<object, ILoopEntry> _region{region.Index} = new();");
        }

        if (regions.Length > 0)
        {
            EmitLoopRuntime(writer);
        }

        foreach (var state in model.States)
        {
            writer.Line($"private {state.TypeName} _{state.Name} = {state.InitializerText};");
        }

        foreach (var computed in model.Computed)
        {
            writer.Line($"private {computed.TypeName} _{computed.Name} = {computed.InitialValueText};");
            writer.Line($"private bool _{computed.Name}Pending;");
            writer.Line($"private string? _{computed.Name}ErrorMessage;");
            writer.Line($"private global::System.Threading.CancellationTokenSource? _{computed.Name}Cancellation;");
            writer.Line($"private int _{computed.Name}Generation;");
        }

        writer.Line("private readonly ComponentOwner _owner;");
        writer.Line("private bool _mounted;");
        writer.Line();
        writer.Line($"internal {model.ComponentName}Component(IUiDispatcher? dispatcher = null)");
        writer.Line("{");
        writer.Indent();
        writer.Line("_owner = new ComponentOwner(dispatcher ?? AvaloniaUiDispatcher.Instance);");
        foreach (var region in regions)
        {
            writer.Line($"_owner.OnDispose(_region{region.Index}.Clear);");
        }
        foreach (var computed in model.Computed)
        {
            writer.Line("_owner.OnDispose(() =>");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_{computed.Name}Cancellation?.Cancel();");
            writer.Line($"_{computed.Name}Cancellation?.Dispose();");
            writer.Unindent();
            writer.Line("});");
        }
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("public Control Mount()");
        writer.Line("{");
        writer.Indent();
        writer.Line("ObjectDisposedException.ThrowIf(_owner.IsDisposed, this);");
        writer.Line();
        writer.Line("if (_mounted)");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            $"throw new InvalidOperationException(\"A {model.ComponentName} component can only be mounted once.\");");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("_mounted = true;");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            writer.Line($"_control{index} = new {control.TypeName}();");
        }

        EmitStyles(writer, model, styles ?? BoundStyleSheet.Empty);

        writer.Line();
        foreach (var (control, index) in fields)
        {
            EmitStaticProperties(writer, control, index, model.States, model.Computed, source);
        }

        foreach (var (control, index) in fields)
        {
            EmitChildren(writer, control, index, fields);
        }

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                writer.Line(
                    $"_control{index}!.{eventMember.EventName} += " +
                    $"OnControl{index}{eventMember.EventName};");
                writer.Line(
                    $"_owner.OnDispose(() => _control{index}!.{eventMember.EventName} -= " +
                    $"OnControl{index}{eventMember.EventName});");
            }
        }

        writer.Line();
        writer.Line("UpdateBindings();");
        foreach (var computed in model.Computed)
        {
            writer.Line($"Refresh{Pascal(computed.Name)}();");
        }
        writer.Line();
        writer.Line("return _control1!;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        writer.Line("public void Dispose() => _owner.Dispose();");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                EmitEventHandler(writer, control, eventMember, index, model, source);
                writer.Line();
            }
        }

        EmitUpdateBindings(writer, model, fields, regions, source);
        foreach (var region in regions)
        {
            writer.Line();
            EmitRegionUpdater(writer, model, region, source);
        }

        foreach (var computed in model.Computed)
        {
            writer.Line();
            EmitComputed(writer, computed, model.States);
        }

        foreach (var state in model.States)
        {
            writer.Line();
            var methodName = SetterName(state.Name);
            writer.Line($"private void {methodName}({state.TypeName} value)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_owner.Dispatch(() => {methodName}Core(value));");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line($"private void {methodName}Core({state.TypeName} value)");
            writer.Line("{");
            writer.Indent();
            writer.Line(
                $"if (EqualityComparer<{state.TypeName}>.Default.Equals(_{state.Name}, value))");
            writer.Line("{");
            writer.Indent();
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line($"_{state.Name} = value;");
            writer.Line("UpdateBindings();");
            if (model.Computed.Count > 0)
            {
                writer.Line("// ponytail: refresh all computed values; use symbol dependencies when components have several.");
            }
            foreach (var computed in model.Computed)
            {
                writer.Line($"Refresh{Pascal(computed.Name)}();");
            }
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line(
                $"private void {methodName}(Func<{state.TypeName}, {state.TypeName}> update)");
            writer.Line("{");
            writer.Indent();
            writer.Line("ArgumentNullException.ThrowIfNull(update);");
            writer.Line($"_owner.Dispatch(() => {methodName}Core(update(_{state.Name})));");
            writer.Unindent();
            writer.Line("}");
        }

        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static void EmitComputed(
        CodeWriter writer,
        BoundComputedModel computed,
        IReadOnlyList<BoundStateModel> states)
    {
        var pascalName = Pascal(computed.Name);
        var factory = RewriteStateReferences(computed.FactoryText, states);

        writer.Line($"private void Refresh{pascalName}()");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (_owner.IsDisposed)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line($"var generation = ++_{computed.Name}Generation;");
        writer.Line($"_{computed.Name}Cancellation?.Cancel();");
        writer.Line($"_{computed.Name}Cancellation?.Dispose();");
        writer.Line(
            $"_{computed.Name}Cancellation = global::System.Threading.CancellationTokenSource." +
            "CreateLinkedTokenSource(_owner.CancellationToken);");
        writer.Line($"_{computed.Name}Pending = true;");
        writer.Line($"_{computed.Name}ErrorMessage = null;");
        writer.Line("UpdateBindings();");
        writer.Line($"_ = Run{pascalName}Async(generation, _{computed.Name}Cancellation.Token);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        writer.Line($"private async global::System.Threading.Tasks.Task Run{pascalName}Async(");
        writer.Indent();
        writer.Line("int generation,");
        writer.Line("global::System.Threading.CancellationToken cancellationToken)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();
        writer.Line("try");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            $"var value = await ((global::System.Func<global::System.Threading.CancellationToken, " +
            $"global::System.Threading.Tasks.Task<{computed.TypeName}>>)({factory}))" +
            "(cancellationToken).ConfigureAwait(false);");
        writer.Line("_owner.Dispatch(() =>");
        writer.Line("{");
        writer.Indent();
        writer.Line($"if (generation != _{computed.Name}Generation)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line($"_{computed.Name} = value;");
        writer.Line($"_{computed.Name}Pending = false;");
        writer.Line("UpdateBindings();");
        writer.Unindent();
        writer.Line("});");
        writer.Unindent();
        writer.Line("}");
        writer.Line("catch (global::System.OperationCanceledException) when (cancellationToken.IsCancellationRequested)");
        writer.Line("{");
        writer.Line("}");
        writer.Line("catch (global::System.Exception exception)");
        writer.Line("{");
        writer.Indent();
        writer.Line("_owner.Dispatch(() =>");
        writer.Line("{");
        writer.Indent();
        writer.Line($"if (generation != _{computed.Name}Generation)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line($"_{computed.Name}Pending = false;");
        writer.Line($"_{computed.Name}ErrorMessage = exception.Message;");
        writer.Line("UpdateBindings();");
        writer.Unindent();
        writer.Line("});");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitStyles(
        CodeWriter writer,
        BoundComponentModel model,
        BoundStyleSheet styles)
    {
        if (styles.Rules.Count == 0)
        {
            return;
        }

        var controls = FlattenStyleTargets(model.Root).ToArray();
        foreach (var rule in styles.Rules)
        {
            var targetTypes = controls
                .Where(control => Matches(rule, control))
                .Select(control => control.TypeName)
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            foreach (var targetType in targetTypes)
            {
                var selector = $"x.OfType<{targetType}>()";
                if (rule.ClassName is not null)
                {
                    selector += $".Class({Quote(rule.ClassName)})";
                }
                if (rule.PseudoClass is not null)
                {
                    selector += $".Class({Quote(rule.PseudoClass)})";
                }

                writer.Line();
                writer.Line($"_control1!.Styles.Add(new global::Avalonia.Styling.Style(x => {selector})");
                writer.Line("{");
                writer.Indent();
                writer.Line("Setters =");
                writer.Line("{");
                writer.Indent();
                foreach (var declaration in rule.Declarations)
                {
                    if (declaration.PropertyName == "transition")
                    {
                        writer.Line(
                            "new global::Avalonia.Styling.Setter(global::Avalonia.Animation.Animatable.TransitionsProperty, " +
                            $"{LowerTransitions(declaration.Value, targetType)}),");
                        continue;
                    }

                    writer.Line(
                        $"new global::Avalonia.Styling.Setter({PropertyField(targetType, declaration.PropertyName)}, " +
                        $"{LowerStyleValue(declaration.PropertyName, declaration.Value)}),");
                }
                writer.Unindent();
                writer.Line("},");
                writer.Unindent();
                writer.Line("});");
            }
        }
    }

    private static bool Matches(BoundStyleRule rule, BoundControlModel control)
    {
        if (rule.TypeName is not null &&
            !string.Equals(rule.TypeName, control.Name, StringComparison.Ordinal) &&
            !control.TypeName.EndsWith("." + rule.TypeName, StringComparison.Ordinal))
        {
            return false;
        }

        return rule.ClassName is null || StaticClasses(control).Contains(rule.ClassName);
    }

    private static HashSet<string> StaticClasses(BoundControlModel control)
    {
        var classes = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in control.Members
                     .OfType<BoundPropertyMember>()
                     .Where(property => property.Name == "Class"))
        {
            if (SyntaxFactory.ParseExpression(property.ExpressionText) is LiteralExpressionSyntax literal &&
                literal.IsKind(SyntaxKind.StringLiteralExpression))
            {
                foreach (var name in literal.Token.ValueText.Split(
                             ' ',
                             StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                {
                    classes.Add(name);
                }
            }
        }

        return classes;
    }

    private static IEnumerable<BoundControlModel> FlattenStyleTargets(BoundControlModel root)
    {
        yield return root;
        foreach (var member in root.Members)
        {
            var child = member switch
            {
                BoundChildMember boundChild => boundChild.Child,
                BoundForEachMember loop => loop.Body,
                _ => null,
            };
            if (child is null)
            {
                continue;
            }

            foreach (var nested in FlattenStyleTargets(child))
            {
                yield return nested;
            }
        }
    }

    private static string PropertyField(string targetType, string cssName)
    {
        var propertyName = cssName switch
        {
            "gap" => "Spacing",
            "border-radius" => "CornerRadius",
            _ => string.Concat(cssName.Split('-')
                .Select(part => char.ToUpperInvariant(part[0]) + part[1..])),
        };
        return $"{targetType}.{propertyName}Property";
    }

    private static string LowerStyleValue(string propertyName, string value) =>
        propertyName switch
        {
            "background" or "foreground" => LowerBrush(value),
            "padding" or "margin" => LowerThickness(value),
            "border-radius" => LowerCornerRadius(value),
            "font-weight" => value switch
            {
                "normal" => "global::Avalonia.Media.FontWeight.Normal",
                "semibold" or "600" => "global::Avalonia.Media.FontWeight.SemiBold",
                "bold" or "700" => "global::Avalonia.Media.FontWeight.Bold",
                _ => throw new InvalidOperationException($"Unsupported CSS font weight '{value}'."),
            },
            "horizontal-alignment" =>
                $"global::Avalonia.Layout.HorizontalAlignment.{Pascal(value)}",
            "vertical-alignment" =>
                $"global::Avalonia.Layout.VerticalAlignment.{Pascal(value)}",
            _ => LowerNumber(value),
        };

    private static string LowerBrush(string value)
    {
        if (!value.StartsWith('#'))
        {
            return value switch
            {
                "transparent" => "global::Avalonia.Media.Brushes.Transparent",
                "black" => "global::Avalonia.Media.Brushes.Black",
                "white" => "global::Avalonia.Media.Brushes.White",
                _ => throw new InvalidOperationException($"Unsupported CSS color '{value}'."),
            };
        }

        var hex = value[1..];
        if (hex.Length == 3)
        {
            hex = string.Concat(hex.Select(character => new string(character, 2)));
        }

        if (hex.Length != 6 || !uint.TryParse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var rgb))
        {
            throw new InvalidOperationException($"Unsupported CSS color '{value}'.");
        }

        return "new global::Avalonia.Media.SolidColorBrush(" +
               $"global::Avalonia.Media.Color.FromRgb(0x{hex[..2]}, 0x{hex[2..4]}, 0x{hex[4..6]}))";
    }

    private static string LowerThickness(string value)
    {
        var values = value.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(LowerNumber)
            .ToArray();
        return values.Length switch
        {
            1 => $"new global::Avalonia.Thickness({values[0]})",
            2 => $"new global::Avalonia.Thickness({values[1]}, {values[0]})",
            4 => $"new global::Avalonia.Thickness({values[3]}, {values[0]}, {values[1]}, {values[2]})",
            _ => throw new InvalidOperationException($"Unsupported CSS thickness '{value}'."),
        };
    }

    private static string LowerCornerRadius(string value)
    {
        var values = value.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(LowerNumber)
            .ToArray();
        return values.Length switch
        {
            1 => $"new global::Avalonia.CornerRadius({values[0]})",
            4 => $"new global::Avalonia.CornerRadius({string.Join(", ", values)})",
            _ => throw new InvalidOperationException($"Unsupported CSS corner radius '{value}'."),
        };
    }

    private static string LowerNumber(string value)
    {
        var number = value.EndsWith("px", StringComparison.Ordinal)
            ? value[..^2]
            : value;
        if (!double.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed))
        {
            throw new InvalidOperationException($"Unsupported CSS number '{value}'.");
        }

        return parsed.ToString("R", CultureInfo.InvariantCulture) + "d";
    }

    private static string LowerTransitions(string value, string targetType)
    {
        var transitions = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(candidate => LowerTransition(candidate, targetType));
        return "new global::Avalonia.Animation.Transitions { " +
               string.Join(", ", transitions) + " }";
    }

    private static string LowerTransition(string value, string targetType)
    {
        var parts = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length is < 2 or > 3)
        {
            throw new InvalidOperationException($"Unsupported CSS transition '{value}'.");
        }

        var propertyName = parts[0];
        var transitionType = propertyName switch
        {
            "background" or "foreground" => "BrushTransition",
            "padding" or "margin" => "ThicknessTransition",
            "border-radius" => "CornerRadiusTransition",
            _ => "DoubleTransition",
        };
        var duration = LowerDuration(parts[1]);
        var easing = parts.Length == 3 ? LowerEasing(parts[2]) : "LinearEasing";
        return $"new global::Avalonia.Animation.{transitionType} " +
               "{ " +
               $"Property = {PropertyField(targetType, propertyName)}, " +
               $"Duration = global::System.TimeSpan.FromMilliseconds({duration}), " +
               $"Easing = new global::Avalonia.Animation.Easings.{easing}() " +
               "}";
    }

    private static string LowerDuration(string value)
    {
        var multiplier = value.EndsWith("ms", StringComparison.Ordinal) ? 1d :
            value.EndsWith('s') ? 1000d :
            throw new InvalidOperationException($"Unsupported CSS duration '{value}'.");
        var number = value.EndsWith("ms", StringComparison.Ordinal) ? value[..^2] : value[..^1];
        if (!double.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed))
        {
            throw new InvalidOperationException($"Unsupported CSS duration '{value}'.");
        }

        return (parsed * multiplier).ToString("R", CultureInfo.InvariantCulture) + "d";
    }

    private static string LowerEasing(string value) => value switch
    {
        "linear" => "LinearEasing",
        "ease-in" => "QuadraticEaseIn",
        "ease-out" => "QuadraticEaseOut",
        "ease-in-out" => "QuadraticEaseInOut",
        _ => throw new InvalidOperationException($"Unsupported CSS easing '{value}'."),
    };

    private static string Pascal(string value) =>
        char.ToUpperInvariant(value[0]) + value[1..];

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static void EmitStaticProperties(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<BoundStateModel> states,
        IReadOnlyList<BoundComputedModel> computed,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            var target = $"_control{index}!";
            if (property.Name == "Class")
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"{target}.Classes.Add({property.ExpressionText});");
                writer.Line("#line default");
                continue;
            }

            if (IsReactive(property.ExpressionText, states, computed))
            {
                continue;
            }

            EmitLineMapping(writer, source, property.ExpressionSpan);
            var expression = LowerPropertyValue(
                property.ExpressionText,
                property.NativeValueKind);
            writer.Line($"{target}.{property.Name} = {expression};");
            writer.Line("#line default");
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (IsReactive(content.ExpressionText, states, computed))
            {
                continue;
            }

            EmitContent(writer, control, index, content, source);
        }
    }

    private static void EmitChildren(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<(BoundControlModel control, int index)> fields)
    {
        if (!control.Members.OfType<BoundChildMember>().Any())
        {
            return;
        }

        foreach (var child in control.Members.OfType<BoundChildMember>())
        {
            var childIndex = fields
                .First(candidate => ReferenceEquals(candidate.control, child.Child))
                .index;
            var route = control.ContentRoute
                ?? throw new InvalidOperationException(
                    $"Bound control '{control.Name}' has children without a content route.");
            writer.Line(route.IsCollection
                ? $"_control{index}!.{route.PropertyName}.Add(_control{childIndex}!);"
                : $"_control{index}!.{route.PropertyName} = _control{childIndex}!;");
        }
    }

    private static void EmitUpdateBindings(
        CodeWriter writer,
        BoundComponentModel model,
        IReadOnlyList<(BoundControlModel control, int index)> fields,
        IReadOnlyList<BoundRegion> regions,
        SourceDocument source)
    {
        writer.Line("private void UpdateBindings()");
        writer.Line("{");
        writer.Indent();
        foreach (var (control, index) in fields)
        {
            foreach (var property in control.Members.OfType<BoundPropertyMember>())
            {
                if (property.Name == "Class" ||
                    !IsReactive(property.ExpressionText, model.States, model.Computed))
                {
                    continue;
                }

                EmitLineMapping(writer, source, property.ExpressionSpan);
                var rewritten = RewriteStateReferences(
                    property.ExpressionText,
                    model.States,
                    model.Computed);
                var expression = LowerPropertyValue(
                    rewritten,
                    property.NativeValueKind);
                writer.Line(
                    $"_control{index}!." +
                    $"{property.Name} = {expression};");
                writer.Line("#line default");
            }

            foreach (var content in control.Members.OfType<BoundContentMember>())
            {
                if (!IsReactive(content.ExpressionText, model.States, model.Computed))
                {
                    continue;
                }

                EmitContent(
                    writer,
                    control,
                    index,
                    content with
                    {
                        ExpressionText = RewriteStateReferences(
                            content.ExpressionText,
                            model.States,
                            model.Computed),
                    },
                    source);
            }
        }

        foreach (var region in regions)
        {
            writer.Line($"UpdateRegion{region.Index}();");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitEventHandler(
        CodeWriter writer,
        BoundControlModel control,
        BoundEventMember eventMember,
        int index,
        BoundComponentModel model,
        SourceDocument source)
    {
        writer.Line(
            $"private void OnControl{index}{eventMember.EventName}" +
            $"({eventMember.DelegateSenderTypeName} __sender, " +
            $"{eventMember.EventArgsTypeName} __eventArgs)");
        writer.Line("{");
        writer.Indent();
        EmitEventParameterAliases(writer, control, eventMember);
        EmitLineMapping(writer, source, eventMember.BodySpan);

        var body = RewriteStateReferences(eventMember.BodyText, model.States, model.Computed).Trim();
        if (body.Length > 0)
        {
            foreach (var line in body.Split(
                         ["\r\n", "\n", "\r"],
                         StringSplitOptions.None))
            {
                writer.Line(line);
            }
        }

        writer.Line("#line default");
        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitEventParameterAliases(
        CodeWriter writer,
        BoundControlModel control,
        BoundEventMember eventMember)
    {
        if (eventMember.SenderParameterName is { } sender && sender != "_")
        {
            writer.Line($"var {sender} = ({control.TypeName})__sender!;");
        }

        if (eventMember.EventArgsParameterName is { } eventArgs && eventArgs != "_")
        {
            writer.Line($"var {eventArgs} = __eventArgs;");
        }
    }

    private static void EmitContent(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        BoundContentMember content,
        SourceDocument source)
    {
        EmitLineMapping(writer, source, content.ExpressionSpan);
        var route = control.ContentRoute
            ?? throw new InvalidOperationException(
                $"Bound control '{control.Name}' has content without a content route.");
        writer.Line(route.IsCollection
            ? $"_control{index}!.{route.PropertyName}.Add({content.ExpressionText});"
            : $"_control{index}!.{route.PropertyName} = {content.ExpressionText};");

        writer.Line("#line default");
    }

    private static void EmitLoopRuntime(CodeWriter writer)
    {
        writer.Line();
        writer.Line("private interface ILoopEntry : IDisposable");
        writer.Line("{");
        writer.Indent();
        writer.Line("Control Root { get; }");
        writer.Line("void Update(object value);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private sealed class LoopValue<T>(T value)");
        writer.Line("{");
        writer.Indent();
        writer.Line("public T Value { get; set; } = value;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private sealed class LoopEntry<T>(");
        writer.Indent();
        writer.Line("LoopValue<T> value,");
        writer.Line("Control root,");
        writer.Line("Action refresh,");
        writer.Line("Action dispose) : ILoopEntry");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();
        writer.Line("public Control Root { get; } = root;");
        writer.Line();
        writer.Line("public void Update(object next)");
        writer.Line("{");
        writer.Indent();
        writer.Line("value.Value = (T)next;");
        writer.Line("refresh();");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("public void Dispose() => dispose();");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private static ILoopEntry CreateLoopEntry<T>(");
        writer.Indent();
        writer.Line("T item,");
        writer.Line("Func<LoopValue<T>, (Control Root, Action Refresh, Action Dispose)> factory)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();
        writer.Line("var value = new LoopValue<T>(item);");
        writer.Line("var created = factory(value);");
        writer.Line("return new LoopEntry<T>(");
        writer.Indent();
        writer.Line("value,");
        writer.Line("created.Root,");
        writer.Line("created.Refresh,");
        writer.Line("created.Dispose);");
        writer.Unindent();
        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitRegionUpdater(
        CodeWriter writer,
        BoundComponentModel model,
        BoundRegion region,
        SourceDocument source)
    {
        var loop = region.Loop;
        var templateControls = Flatten(loop.Body)
            .Select((control, index) => (control, index: index + 1))
            .ToArray();
        var dictionary = $"_region{region.Index}";

        writer.Line($"private void UpdateRegion{region.Index}()");
        writer.Line("{");
        writer.Indent();
        writer.Line("var nextEntries = new List<ILoopEntry>();");
        writer.Line("var seenKeys = new HashSet<object>();");
        writer.Line("var orderedKeys = new List<object>();");
        EmitLineMapping(writer, source, loop.SourceExpressionSpan);
        writer.Line(
            $"var sourceItems = " +
            $"({RewriteStateReferences(loop.SourceExpression, model.States, model.Computed)}).ToArray();");
        writer.Line("#line default");
        writer.Line($"foreach (var {loop.ItemName} in sourceItems)");
        writer.Line("{");
        writer.Indent();
        EmitLineMapping(writer, source, loop.KeyExpressionSpan);
        writer.Line($"object? key = {loop.KeyExpression};");
        writer.Line("#line default");
        writer.Line("if (key is null)");
        writer.Line("{");
        writer.Indent();
        writer.Line("""throw new InvalidOperationException("A keyed foreach produced a null key.");""");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("if (!seenKeys.Add(key))");
        writer.Line("{");
        writer.Indent();
        writer.Line("""throw new InvalidOperationException($"A keyed foreach produced duplicate key '{key}'.");""");
        writer.Unindent();
        writer.Line("}");
        writer.Line("orderedKeys.Add(key);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("var itemIndex = 0;");
        writer.Line($"foreach (var {loop.ItemName} in sourceItems)");
        writer.Line("{");
        writer.Indent();
        writer.Line("var key = orderedKeys[itemIndex++];");
        writer.Line();
        writer.Line($"if (!{dictionary}.TryGetValue(key, out var entry))");
        writer.Line("{");
        writer.Indent();
        writer.Line($"entry = CreateLoopEntry({loop.ItemName}, loopValue =>");
        writer.Line("{");
        writer.Indent();

        foreach (var (control, index) in templateControls)
        {
            writer.Line($"var control{index} = new {control.TypeName}();");
        }
        writer.Line("var rowOwner = _owner.CreateChild();");

        writer.Line();
        foreach (var (control, index) in templateControls)
        {
            EmitTemplateStaticProperties(
                writer,
                control,
                index,
                loop.ItemName,
                model.States,
                model.Computed,
                source);
        }

        foreach (var (control, index) in templateControls)
        {
            EmitTemplateChildren(
                writer,
                control,
                index,
                templateControls);
        }

        writer.Line();
        writer.Line("void Refresh()");
        writer.Line("{");
        writer.Indent();
        var hasItemBindings = templateControls.Any(candidate =>
            candidate.control.Members.Any(member =>
                MemberReferencesItem(member, loop.ItemName)));
        if (hasItemBindings)
        {
            writer.Line($"var {loop.ItemName} = loopValue.Value;");
        }

        foreach (var (control, index) in templateControls)
        {
            EmitTemplateBindings(
                writer,
                control,
                index,
                loop.ItemName,
                model.States,
                model.Computed,
                source);
        }

        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("Refresh();");

        foreach (var (control, index) in templateControls)
        {
            foreach (var (eventMember, eventIndex) in control.Members
                         .OfType<BoundEventMember>()
                         .Select((eventMember, eventIndex) => (eventMember, eventIndex)))
            {
                var handlerName = $"handler{index}_{eventIndex + 1}";
                writer.Line(
                    $"{eventMember.DelegateTypeName} {handlerName} = " +
                    "(__sender, __eventArgs) =>");

                writer.Line("{");
                writer.Indent();
                EmitEventParameterAliases(writer, control, eventMember);
                var body = eventMember.BodyText;
                if (ReferencesItem(body, loop.ItemName))
                {
                    writer.Line($"var {loop.ItemName} = loopValue.Value;");
                }

                EmitLineMapping(writer, source, eventMember.BodySpan);
                EmitBody(
                    writer,
                    RewriteStateReferences(body, model.States, model.Computed));
                writer.Line("#line default");
                writer.Unindent();
                writer.Line("};");
                writer.Line($"control{index}.{eventMember.EventName} += {handlerName};");
                writer.Line(
                    $"rowOwner.OnDispose(() => " +
                    $"control{index}.{eventMember.EventName} -= {handlerName});");
            }
        }

        writer.Line();
        writer.Line("return (control1, (Action)Refresh, rowOwner.Dispose);");
        writer.Unindent();
        writer.Line("});");
        writer.Line($"{dictionary}.Add(key, entry);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("else");
        writer.Line("{");
        writer.Indent();
        writer.Line($"entry.Update({loop.ItemName});");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("nextEntries.Add(entry);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("var staleKeys = new List<object>();");
        writer.Line($"foreach (var pair in {dictionary})");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (!seenKeys.Contains(pair.Key))");
        writer.Line("{");
        writer.Indent();
        writer.Line("pair.Value.Dispose();");
        writer.Line("staleKeys.Add(pair.Key);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("foreach (var staleKey in staleKeys)");
        writer.Line("{");
        writer.Indent();
        writer.Line($"{dictionary}.Remove(staleKey);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        var collectionProperty = region.Parent.ContentRoute?.PropertyName
            ?? throw new InvalidOperationException(
                $"Keyed region parent '{region.Parent.Name}' has no collection content route.");
        writer.Line(
            $"var nativeItems = _control{region.ParentIndex}!.{collectionProperty};");
        writer.Line("var orderChanged = nativeItems.Count != nextEntries.Count;");
        writer.Line("for (var index = 0; !orderChanged && index < nextEntries.Count; index++)");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            "orderChanged = !ReferenceEquals(nativeItems[index], nextEntries[index].Root);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("if (orderChanged)");
        writer.Line("{");
        writer.Indent();
        writer.Line("nativeItems.Clear();");
        writer.Line("foreach (var entry in nextEntries)");
        writer.Line("{");
        writer.Indent();
        writer.Line("nativeItems.Add(entry.Root);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");

        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitTemplateStaticProperties(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        string itemName,
        IReadOnlyList<BoundStateModel> states,
        IReadOnlyList<BoundComputedModel> computed,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            if (property.Name == "Class")
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"control{index}.Classes.Add({property.ExpressionText});");
                writer.Line("#line default");
                continue;
            }

            if (IsReactive(property.ExpressionText, states, computed) ||
                ReferencesItem(property.ExpressionText, itemName))
            {
                continue;
            }

            EmitLineMapping(writer, source, property.ExpressionSpan);
            var target = $"control{index}.{property.Name}";
            writer.Line(
                $"{target} = " +
                $"{LowerPropertyValue(property.ExpressionText, property.NativeValueKind)};");
            writer.Line("#line default");
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (IsReactive(content.ExpressionText, states, computed) ||
                ReferencesItem(content.ExpressionText, itemName))
            {
                continue;
            }

            EmitTemplateContent(writer, control, index, content, source);
        }
    }

    private static void EmitTemplateBindings(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        string itemName,
        IReadOnlyList<BoundStateModel> states,
        IReadOnlyList<BoundComputedModel> computed,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            if (property.Name == "Class" ||
                (!IsReactive(property.ExpressionText, states, computed) &&
                 !ReferencesItem(property.ExpressionText, itemName)))
            {
                continue;
            }

            EmitLineMapping(writer, source, property.ExpressionSpan);
            var target = $"control{index}.{property.Name}";
            var rewritten = RewriteStateReferences(property.ExpressionText, states, computed);
            writer.Line(
                $"{target} = " +
                $"{LowerPropertyValue(rewritten, property.NativeValueKind)};");
            writer.Line("#line default");
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (!IsReactive(content.ExpressionText, states, computed) &&
                !ReferencesItem(content.ExpressionText, itemName))
            {
                continue;
            }

            EmitTemplateContent(
                writer,
                control,
                index,
                content with
                {
                    ExpressionText = RewriteStateReferences(content.ExpressionText, states, computed),
                },
                source);
        }
    }

    private static void EmitTemplateChildren(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<(BoundControlModel control, int index)> controls)
    {
        foreach (var child in control.Members.OfType<BoundChildMember>())
        {
            var childIndex = controls
                .First(candidate => ReferenceEquals(candidate.control, child.Child))
                .index;
            var route = control.ContentRoute
                ?? throw new InvalidOperationException(
                    $"Bound control '{control.Name}' has children without a content route.");
            writer.Line(route.IsCollection
                ? $"control{index}.{route.PropertyName}.Add(control{childIndex});"
                : $"control{index}.{route.PropertyName} = control{childIndex};");
        }
    }

    private static void EmitTemplateContent(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        BoundContentMember content,
        SourceDocument source)
    {
        EmitLineMapping(writer, source, content.ExpressionSpan);
        var route = control.ContentRoute
            ?? throw new InvalidOperationException(
                $"Bound control '{control.Name}' has content without a content route.");
        writer.Line(route.IsCollection
            ? $"control{index}.{route.PropertyName}.Add({content.ExpressionText});"
            : $"control{index}.{route.PropertyName} = {content.ExpressionText};");

        writer.Line("#line default");
    }

    private static bool MemberReferencesItem(
        BoundControlMember member,
        string itemName) =>
        member switch
        {
            BoundPropertyMember property => ReferencesItem(property.ExpressionText, itemName),
            BoundContentMember content => ReferencesItem(content.ExpressionText, itemName),
            _ => false,
        };

    private static bool ReferencesItem(string expression, string itemName)
    {
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        return root.DescendantNodes()
            .OfType<IdentifierNameSyntax>()
            .Any(identifier =>
                identifier.Identifier.ValueText == itemName &&
                (identifier.Parent is not MemberAccessExpressionSyntax access ||
                 !ReferenceEquals(access.Name, identifier)));
    }

    private static string LowerPropertyValue(
        string expression,
        BoundNativeValueKind nativeValueKind)
    {
        if (nativeValueKind == BoundNativeValueKind.None)
        {
            return expression;
        }

        var syntax = SyntaxFactory.ParseExpression(expression);
        var typeName = nativeValueKind switch
        {
            BoundNativeValueKind.Thickness => "global::Avalonia.Thickness",
            BoundNativeValueKind.CornerRadius => "global::Avalonia.CornerRadius",
            _ => throw new InvalidOperationException(
                $"Unsupported native value kind '{nativeValueKind}'."),
        };

        if (IsNumericLiteral(syntax))
        {
            return $"new {typeName}({expression})";
        }

        var supportsTuple =
            nativeValueKind == BoundNativeValueKind.Thickness &&
            syntax is TupleExpressionSyntax { Arguments.Count: 2 or 4 } ||
            nativeValueKind == BoundNativeValueKind.CornerRadius &&
            syntax is TupleExpressionSyntax { Arguments.Count: 4 };
        if (supportsTuple && syntax is TupleExpressionSyntax tuple)
        {
            var arguments = string.Join(
                ", ",
                tuple.Arguments.Select(argument => argument.Expression.ToFullString().Trim()));
            return $"new {typeName}({arguments})";
        }

        return expression;
    }

    private static bool IsNumericLiteral(ExpressionSyntax syntax) =>
        syntax switch
        {
            LiteralExpressionSyntax literal =>
                literal.IsKind(SyntaxKind.NumericLiteralExpression),
            ParenthesizedExpressionSyntax parenthesized =>
                IsNumericLiteral(parenthesized.Expression),
            PrefixUnaryExpressionSyntax prefix
                when prefix.IsKind(SyntaxKind.UnaryMinusExpression) ||
                     prefix.IsKind(SyntaxKind.UnaryPlusExpression) =>
                IsNumericLiteral(prefix.Operand),
            _ => false,
        };

    private static void EmitBody(CodeWriter writer, string body)
    {
        body = body.Trim();
        if (body.Length == 0)
        {
            return;
        }

        foreach (var line in body.Split(
                     ["\r\n", "\n", "\r"],
                     StringSplitOptions.None))
        {
            writer.Line(line);
        }
    }

    private static IEnumerable<BoundControlModel> Flatten(BoundControlModel root)
    {
        yield return root;
        foreach (var child in root.Members.OfType<BoundChildMember>())
        {
            foreach (var nested in Flatten(child.Child))
            {
                yield return nested;
            }
        }
    }

    private static bool IsReactive(
        string expression,
        IReadOnlyList<BoundStateModel> states,
        IReadOnlyList<BoundComputedModel>? computed = null)
    {
        var stateNames = states
            .Select(state => state.Name)
            .ToHashSet(StringComparer.Ordinal);
        var computedNames = (computed ?? [])
            .Select(candidate => candidate.Name)
            .ToHashSet(StringComparer.Ordinal);
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        return root.DescendantNodes()
            .OfType<MemberAccessExpressionSyntax>()
            .Any(access =>
                access.Expression is IdentifierNameSyntax identifier &&
                (stateNames.Contains(identifier.Identifier.ValueText) &&
                 access.Name.Identifier.ValueText == "Value" ||
                 computedNames.Contains(identifier.Identifier.ValueText) &&
                 access.Name.Identifier.ValueText is "Value" or "IsPending" or "ErrorMessage"));
    }

    private static string RewriteStateReferences(
        string expression,
        IReadOnlyList<BoundStateModel> states,
        IReadOnlyList<BoundComputedModel>? computed = null)
    {
        var replacements = new List<(int Start, int Length, string Text)>();
        var stateNames = states.ToDictionary(
            state => state.Name,
            state => state,
            StringComparer.Ordinal);
        var computedNames = (computed ?? []).ToDictionary(
            candidate => candidate.Name,
            candidate => candidate,
            StringComparer.Ordinal);
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        foreach (var access in root.DescendantNodes()
                     .OfType<MemberAccessExpressionSyntax>())
        {
            if (access.Expression is not IdentifierNameSyntax identifier)
            {
                continue;
            }

            string? replacement = null;
            if (stateNames.TryGetValue(identifier.Identifier.ValueText, out var state))
            {
                replacement = access.Name.Identifier.ValueText switch
                {
                    "Value" => "_" + state.Name,
                    "Update" => SetterName(state.Name),
                    _ => null,
                };
            }
            else if (computedNames.TryGetValue(identifier.Identifier.ValueText, out var candidate))
            {
                replacement = access.Name.Identifier.ValueText switch
                {
                    "Value" => "_" + candidate.Name,
                    "IsPending" => "_" + candidate.Name + "Pending",
                    "ErrorMessage" => "_" + candidate.Name + "ErrorMessage",
                    _ => null,
                };
            }

            if (replacement is not null)
            {
                replacements.Add(
                    (access.SpanStart, access.Span.Length, replacement));
            }
        }

        foreach (var replacement in replacements
                     .OrderByDescending(candidate => candidate.Start))
        {
            expression = expression.Remove(
                    replacement.Start,
                    replacement.Length)
                .Insert(replacement.Start, replacement.Text);
        }

        return expression;
    }

    private static void EmitLineMapping(
        CodeWriter writer,
        SourceDocument source,
        SourceSpan span)
    {
        var (line, _) = source.GetLineAndColumn(span.Start);
        writer.Line($"#line {line} \"{EscapeLinePath(source.Path)}\"");
    }

    private static string SetterName(string stateName) =>
        "Set" + (stateName.Length == 0
            ? stateName
            : char.ToUpperInvariant(stateName[0]) + stateName[1..]);

    private sealed record BoundRegion(
        BoundControlModel Parent,
        int ParentIndex,
        BoundForEachMember Loop,
        int Index);

    private static string EscapeLinePath(string path) =>
        path.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
