using System.Text.RegularExpressions;
using Lucent.Compiler.Parsing;

namespace Lucent.Compiler.CodeGeneration;

internal static class GeneralCSharpEmitter
{
    public static string Emit(
        BoundComponentModel model,
        string sourcePath,
        string sourceText)
    {
        var source = new SourceDocument(sourceText, sourcePath);
        var writer = new CodeWriter();
        var controls = Flatten(model.Root).ToArray();
        var fields = controls
            .Select((control, index) => (control, index: index + 1))
            .ToArray();

        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("// <auto-generated />");
        writer.Line($"// Generated by Lucent.Compiler from {Path.GetFileName(sourcePath)}.");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using Avalonia.Controls;");
        writer.Line("using Avalonia.Interactivity;");
        writer.Line();
        writer.Line($"namespace {model.NamespaceName};");
        writer.Line();
        writer.Line($"internal sealed class {model.ComponentName}Component : IDisposable");
        writer.Line("{");
        writer.Indent();

        foreach (var (control, index) in fields)
        {
            writer.Line($"private {ControlType(control.Name)}? _control{index};");
        }

        foreach (var state in model.States)
        {
            writer.Line($"private {state.TypeName} _{state.Name} = {state.InitializerText};");
        }

        writer.Line("private bool _disposed;");
        writer.Line("private bool _mounted;");
        writer.Line();
        writer.Line("public Control Mount()");
        writer.Line("{");
        writer.Indent();
        writer.Line("ObjectDisposedException.ThrowIf(_disposed, this);");
        writer.Line();
        writer.Line("if (_mounted)");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            $"throw new InvalidOperationException(\"A {model.ComponentName} component can only be mounted once.\");");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("_mounted = true;");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            writer.Line($"_control{index} = new {ControlType(control.Name)}();");
        }

        writer.Line();
        foreach (var (control, index) in fields)
        {
            EmitStaticProperties(writer, control, index, model.States, source);
        }

        foreach (var (control, index) in fields)
        {
            EmitChildren(writer, control, index, fields);
        }

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (!string.Equals(control.Name, "Button", StringComparison.Ordinal) ||
                    !string.Equals(eventMember.Name, "onClick", StringComparison.Ordinal))
                {
                    continue;
                }

                writer.Line($"_control{index}!.Click += OnControl{index}Click;");
            }
        }

        writer.Line();
        writer.Line("UpdateBindings();");
        writer.Line();
        writer.Line("return _control1!;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        writer.Line("public void Dispose()");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (_disposed)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (control.Name == "Button" && eventMember.Name == "onClick")
                {
                    writer.Line($"if (_control{index} is not null)");
                    writer.Line("{");
                    writer.Indent();
                    writer.Line($"_control{index}.Click -= OnControl{index}Click;");
                    writer.Unindent();
                    writer.Line("}");
                }
            }
        }

        writer.Line();
        writer.Line("_disposed = true;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (control.Name != "Button" ||
                    eventMember.Name != "onClick")
                {
                    continue;
                }

                EmitEventHandler(writer, eventMember, index, model, source);
                writer.Line();
            }
        }

        EmitUpdateBindings(writer, model, fields, source);
        foreach (var state in model.States)
        {
            writer.Line();
            var methodName = SetterName(state.Name);
            writer.Line($"private void {methodName}({state.TypeName} value)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_{state.Name} = value;");
            writer.Line("UpdateBindings();");
            writer.Unindent();
            writer.Line("}");
        }

        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static void EmitStaticProperties(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<BoundStateModel> states,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            var target = $"_control{index}!";
            if (property.Name == "class")
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"{target}.Classes.Add({property.ExpressionText});");
                writer.Line("#line default");
                continue;
            }

            if (IsReactive(property.ExpressionText, states))
            {
                continue;
            }

            var targetProperty = TargetProperty(control.Name, property.Name);
            if (targetProperty is not null)
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"{target}.{targetProperty} = {property.ExpressionText};");
                writer.Line("#line default");
            }
        }
    }

    private static void EmitChildren(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<(BoundControlModel control, int index)> fields)
    {
        if (control.Name != "Column")
        {
            return;
        }

        foreach (var child in control.Members.OfType<BoundChildMember>())
        {
            var childIndex = fields
                .First(candidate => ReferenceEquals(candidate.control, child.Child))
                .index;
            writer.Line($"_control{index}!.Children.Add(_control{childIndex}!);");
        }
    }

    private static void EmitUpdateBindings(
        CodeWriter writer,
        BoundComponentModel model,
        IReadOnlyList<(BoundControlModel control, int index)> fields,
        SourceDocument source)
    {
        writer.Line("private void UpdateBindings()");
        writer.Line("{");
        writer.Indent();
        foreach (var (control, index) in fields)
        {
            foreach (var property in control.Members.OfType<BoundPropertyMember>())
            {
                if (property.Name == "class" ||
                    !IsReactive(property.ExpressionText, model.States))
                {
                    continue;
                }

                var targetProperty = TargetProperty(control.Name, property.Name);
                if (targetProperty is null)
                {
                    continue;
                }

                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line(
                    $"_control{index}!." +
                    $"{targetProperty} = {RewriteStateReferences(property.ExpressionText, model.States)};");
                writer.Line("#line default");
            }
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitEventHandler(
        CodeWriter writer,
        BoundEventMember eventMember,
        int index,
        BoundComponentModel model,
        SourceDocument source)
    {
        writer.Line(
            $"private void OnControl{index}Click(object? sender, RoutedEventArgs e)");
        writer.Line("{");
        writer.Indent();
        EmitLineMapping(writer, source, eventMember.BodySpan);

        var body = eventMember.IsExpression
            ? ExtractLambdaBody(eventMember.BodyText)
            : eventMember.BodyText;
        body = RewriteStateReferences(body, model.States).Trim();
        if (body.Length > 0)
        {
            foreach (var line in body.Split(
                         ["\r\n", "\n", "\r"],
                         StringSplitOptions.None))
            {
                writer.Line(line);
            }
        }

        writer.Line("#line default");
        writer.Unindent();
        writer.Line("}");
    }

    private static IEnumerable<BoundControlModel> Flatten(BoundControlModel root)
    {
        yield return root;
        foreach (var child in root.Members.OfType<BoundChildMember>())
        {
            foreach (var nested in Flatten(child.Child))
            {
                yield return nested;
            }
        }
    }

    private static string ControlType(string name) =>
        name switch
        {
            "Column" => "StackPanel",
            "Text" => "TextBlock",
            "Button" => "Button",
            _ => "Control",
        };

    private static string? TargetProperty(string controlName, string propertyName) =>
        (controlName, propertyName) switch
        {
            ("Text", "text") => "Text",
            ("Button", "text") => "Content",
            _ => null,
        };

    private static bool IsReactive(
        string expression,
        IReadOnlyList<BoundStateModel> states)
    {
        return states.Any(state =>
            Regex.IsMatch(
                expression,
                $@"\b{Regex.Escape(state.Name)}\.Value\b",
                RegexOptions.CultureInvariant));
    }

    private static string RewriteStateReferences(
        string expression,
        IReadOnlyList<BoundStateModel> states)
    {
        foreach (var state in states)
        {
            expression = Regex.Replace(
                expression,
                $@"\b{Regex.Escape(state.Name)}\.Value\b",
                "_" + state.Name,
                RegexOptions.CultureInvariant);
            expression = Regex.Replace(
                expression,
                $@"\b{Regex.Escape(state.Name)}\.Update\s*\(",
                SetterName(state.Name) + "(",
                RegexOptions.CultureInvariant);
        }

        return expression;
    }

    private static string ExtractLambdaBody(string expression)
    {
        var arrow = expression.IndexOf("=>", StringComparison.Ordinal);
        if (arrow < 0)
        {
            return expression;
        }

        var body = expression[(arrow + 2)..].Trim();
        return body.EndsWith(';')
            ? body
            : body + ";";
    }

    private static void EmitLineMapping(
        CodeWriter writer,
        SourceDocument source,
        SourceSpan span)
    {
        var (line, _) = source.GetLineAndColumn(span.Start);
        writer.Line($"#line {line} \"{EscapeLinePath(source.Path)}\"");
    }

    private static string SetterName(string stateName) =>
        "Set" + (stateName.Length == 0
            ? stateName
            : char.ToUpperInvariant(stateName[0]) + stateName[1..]);

    private static string EscapeLinePath(string path) =>
        path.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
