using Lucent.Compiler.Parsing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lucent.Compiler.CodeGeneration;

internal static class GeneralCSharpEmitter
{
    public static string Emit(
        BoundComponentModel model,
        string sourcePath,
        string sourceText)
    {
        var source = new SourceDocument(sourceText, sourcePath);
        var writer = new CodeWriter();
        var controls = Flatten(model.Root).ToArray();
        var fields = controls
            .Select((control, index) => (control, index: index + 1))
            .ToArray();
        var regions = fields
            .SelectMany(field => field.control.Members
                .OfType<BoundForEachMember>()
                .Select(loop => (field.control, parentIndex: field.index, loop)))
            .Select((region, index) => new BoundRegion(
                region.control,
                region.parentIndex,
                region.loop,
                index + 1))
            .ToArray();
        var allControls = controls
            .Concat(regions.SelectMany(region => Flatten(region.Loop.Body)))
            .ToArray();
        var hasNativeChildSlots = allControls.Any(control =>
            control.Name != "Column" &&
            control.Members.OfType<BoundChildMember>().Any());

        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("// <auto-generated />");
        writer.Line($"// Generated by Lucent.Compiler from {Path.GetFileName(sourcePath)}.");
        writer.Line();
        writer.Line("using System;");
        writer.Line("using System.Collections.Generic;");
        if (regions.Length > 0)
        {
            writer.Line("using System.Linq;");
        }
        writer.Line("using Avalonia.Controls;");
        writer.Line("using Avalonia.Interactivity;");
        writer.Line("using Avalonia.Threading;");
        foreach (var usingDirective in model.Usings
                     .Where(directive =>
                         directive is not "using System;" and
                         not "using System.Collections.Generic;" and
                         not "using System.Linq;" and
                         not "using Avalonia.Controls;" and
                         not "using Avalonia.Interactivity;" and
                         not "using Avalonia.Threading;")
                     .Distinct(StringComparer.Ordinal))
        {
            writer.Line(usingDirective);
        }
        writer.Line();
        writer.Line($"namespace {model.NamespaceName};");
        writer.Line();
        writer.Line($"internal sealed class {model.ComponentName}Component : IDisposable");
        writer.Line("{");
        writer.Indent();

        foreach (var (control, index) in fields)
        {
            writer.Line($"private {ControlType(control.Name)}? _control{index};");
        }

        foreach (var region in regions)
        {
            writer.Line(
                $"private readonly Dictionary<object, ILoopEntry> _region{region.Index} = new();");
        }

        if (hasNativeChildSlots)
        {
            writer.Line();
            writer.Line("private static void AttachChild(Panel parent, Control child) => parent.Children.Add(child);");
            writer.Line("private static void AttachChild(Decorator parent, Control child) => parent.Child = child;");
            writer.Line("private static void AttachChild(ContentControl parent, Control child) => parent.Content = child;");
            writer.Line("private static void AttachChild(ItemsControl parent, Control child) => parent.Items.Add(child);");
        }

        if (regions.Length > 0)
        {
            EmitLoopRuntime(writer);
        }

        foreach (var state in model.States)
        {
            writer.Line($"private {state.TypeName} _{state.Name} = {state.InitializerText};");
        }

        writer.Line("private bool _disposed;");
        writer.Line("private bool _mounted;");
        writer.Line();
        writer.Line("public Control Mount()");
        writer.Line("{");
        writer.Indent();
        writer.Line("ObjectDisposedException.ThrowIf(_disposed, this);");
        writer.Line();
        writer.Line("if (_mounted)");
        writer.Line("{");
        writer.Indent();
        writer.Line(
            $"throw new InvalidOperationException(\"A {model.ComponentName} component can only be mounted once.\");");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("_mounted = true;");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            writer.Line($"_control{index} = new {ControlType(control.Name)}();");
        }

        writer.Line();
        foreach (var (control, index) in fields)
        {
            EmitStaticProperties(writer, control, index, model.States, source);
        }

        foreach (var (control, index) in fields)
        {
            EmitChildren(writer, control, index, fields);
        }

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (HasNamedHandler(eventMember))
                {
                    writer.Line(
                        $"_control{index}!.{eventMember.EventName} += " +
                        $"OnControl{index}{eventMember.EventName};");
                }
                else
                {
                    EmitInlineEvent(writer, eventMember, index, model, source);
                }
            }
        }

        writer.Line();
        writer.Line("UpdateBindings();");
        writer.Line();
        writer.Line("return _control1!;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        writer.Line("public void Dispose()");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (_disposed)");
        writer.Line("{");
        writer.Indent();
        writer.Line("return;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (HasNamedHandler(eventMember))
                {
                    writer.Line($"if (_control{index} is not null)");
                    writer.Line("{");
                    writer.Indent();
                    writer.Line(
                        $"_control{index}.{eventMember.EventName} -= " +
                        $"OnControl{index}{eventMember.EventName};");
                    writer.Unindent();
                    writer.Line("}");
                }
            }
        }

        foreach (var region in regions)
        {
            writer.Line($"foreach (var entry in _region{region.Index}.Values)");
            writer.Line("{");
            writer.Indent();
            writer.Line("entry.Dispose();");
            writer.Unindent();
            writer.Line("}");
            writer.Line($"_region{region.Index}.Clear();");
        }

        writer.Line();
        writer.Line("_disposed = true;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        foreach (var (control, index) in fields)
        {
            foreach (var eventMember in control.Members.OfType<BoundEventMember>())
            {
                if (!HasNamedHandler(eventMember))
                {
                    continue;
                }

                EmitEventHandler(writer, eventMember, index, model, source);
                writer.Line();
            }
        }

        EmitUpdateBindings(writer, model, fields, regions, source);
        foreach (var region in regions)
        {
            writer.Line();
            EmitRegionUpdater(writer, model, region, source, hasNativeChildSlots);
        }

        foreach (var state in model.States)
        {
            writer.Line();
            var methodName = SetterName(state.Name);
            writer.Line($"private void {methodName}({state.TypeName} value)");
            writer.Line("{");
            writer.Indent();
            writer.Line("if (_disposed)");
            writer.Line("{");
            writer.Indent();
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line("if (!Dispatcher.UIThread.CheckAccess())");
            writer.Line("{");
            writer.Indent();
            writer.Line($"Dispatcher.UIThread.Post(() => {methodName}(value));");
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line(
                $"if (EqualityComparer<{state.TypeName}>.Default.Equals(_{state.Name}, value))");
            writer.Line("{");
            writer.Indent();
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line($"_{state.Name} = value;");
            writer.Line("UpdateBindings();");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line(
                $"private void {methodName}(Func<{state.TypeName}, {state.TypeName}> update)");
            writer.Line("{");
            writer.Indent();
            writer.Line("ArgumentNullException.ThrowIfNull(update);");
            writer.Line("if (_disposed)");
            writer.Line("{");
            writer.Indent();
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line("if (!Dispatcher.UIThread.CheckAccess())");
            writer.Line("{");
            writer.Indent();
            writer.Line($"Dispatcher.UIThread.Post(() => {methodName}(update));");
            writer.Line("return;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line($"{methodName}(update(_{state.Name}));");
            writer.Unindent();
            writer.Line("}");
        }

        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static void EmitStaticProperties(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<BoundStateModel> states,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            var target = $"_control{index}!";
            if (property.Name == "class")
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"{target}.Classes.Add({property.ExpressionText});");
                writer.Line("#line default");
                continue;
            }

            if (IsReactive(property.ExpressionText, states))
            {
                continue;
            }

            var targetProperty = TargetProperty(control.Name, property.Name);
            if (targetProperty is not null)
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                var expression = LowerPropertyValue(
                    property.ExpressionText,
                    property.NativeValueKind);
                writer.Line($"{target}.{targetProperty} = {expression};");
                writer.Line("#line default");
            }
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (IsReactive(content.ExpressionText, states))
            {
                continue;
            }

            EmitContent(writer, control, index, content, source);
        }
    }

    private static void EmitChildren(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<(BoundControlModel control, int index)> fields)
    {
        if (!control.Members.OfType<BoundChildMember>().Any())
        {
            return;
        }

        foreach (var child in control.Members.OfType<BoundChildMember>())
        {
            var childIndex = fields
                .First(candidate => ReferenceEquals(candidate.control, child.Child))
                .index;
            if (control.Name == "Column")
            {
                writer.Line($"_control{index}!.Children.Add(_control{childIndex}!);");
            }
            else
            {
                writer.Line($"AttachChild(_control{index}!, _control{childIndex}!);");
            }
        }
    }

    private static void EmitUpdateBindings(
        CodeWriter writer,
        BoundComponentModel model,
        IReadOnlyList<(BoundControlModel control, int index)> fields,
        IReadOnlyList<BoundRegion> regions,
        SourceDocument source)
    {
        writer.Line("private void UpdateBindings()");
        writer.Line("{");
        writer.Indent();
        foreach (var (control, index) in fields)
        {
            foreach (var property in control.Members.OfType<BoundPropertyMember>())
            {
                if (property.Name == "class" ||
                    !IsReactive(property.ExpressionText, model.States))
                {
                    continue;
                }

                var targetProperty = TargetProperty(control.Name, property.Name);
                if (targetProperty is null)
                {
                    continue;
                }

                EmitLineMapping(writer, source, property.ExpressionSpan);
                var rewritten = RewriteStateReferences(
                    property.ExpressionText,
                    model.States);
                var expression = LowerPropertyValue(
                    rewritten,
                    property.NativeValueKind);
                writer.Line(
                    $"_control{index}!." +
                    $"{targetProperty} = {expression};");
                writer.Line("#line default");
            }

            foreach (var content in control.Members.OfType<BoundContentMember>())
            {
                if (!IsReactive(content.ExpressionText, model.States))
                {
                    continue;
                }

                EmitContent(
                    writer,
                    control,
                    index,
                    content with
                    {
                        ExpressionText = RewriteStateReferences(content.ExpressionText, model.States),
                    },
                    source);
            }
        }

        foreach (var region in regions)
        {
            writer.Line($"UpdateRegion{region.Index}();");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitEventHandler(
        CodeWriter writer,
        BoundEventMember eventMember,
        int index,
        BoundComponentModel model,
        SourceDocument source)
    {
        var eventArgsType = EventArgsType(eventMember.EventName)
            ?? throw new InvalidOperationException(
                $"No generated handler signature is registered for '{eventMember.EventName}'.");
        writer.Line(
            $"private void OnControl{index}{eventMember.EventName}" +
            $"(object? sender, {eventArgsType} e)");
        writer.Line("{");
        writer.Indent();
        EmitLineMapping(writer, source, eventMember.BodySpan);

        var body = eventMember.IsExpression
            ? ExtractLambdaBody(eventMember.BodyText)
            : eventMember.BodyText;
        body = RewriteStateReferences(body, model.States).Trim();
        if (body.Length > 0)
        {
            foreach (var line in body.Split(
                         ["\r\n", "\n", "\r"],
                         StringSplitOptions.None))
            {
                writer.Line(line);
            }
        }

        writer.Line("#line default");
        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitInlineEvent(
        CodeWriter writer,
        BoundEventMember eventMember,
        int index,
        BoundComponentModel model,
        SourceDocument source)
    {
        writer.Line($"_control{index}!.{eventMember.EventName} += (sender, e) =>");
        writer.Line("{");
        writer.Indent();
        EmitLineMapping(writer, source, eventMember.BodySpan);

        var body = eventMember.IsExpression
            ? ExtractLambdaBody(eventMember.BodyText)
            : eventMember.BodyText;
        body = RewriteStateReferences(body, model.States).Trim();
        if (body.Length > 0)
        {
            foreach (var line in body.Split(
                         ["\r\n", "\n", "\r"],
                         StringSplitOptions.None))
            {
                writer.Line(line);
            }
        }

        writer.Line("#line default");
        writer.Unindent();
        writer.Line("};");
    }

    private static void EmitContent(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        BoundContentMember content,
        SourceDocument source)
    {
        EmitLineMapping(writer, source, content.ExpressionSpan);
        var target = control.Kind switch
        {
            BoundControlKind.Text => $"_control{index}!.Text = {content.ExpressionText};",
            BoundControlKind.ContentControl => $"_control{index}!.Content = {content.ExpressionText};",
            BoundControlKind.ItemsControl => $"_control{index}!.Items.Add({content.ExpressionText});",
            _ => null,
        };

        if (target is not null)
        {
            writer.Line(target);
        }

        writer.Line("#line default");
    }

    private static void EmitLoopRuntime(CodeWriter writer)
    {
        writer.Line();
        writer.Line("private interface ILoopEntry : IDisposable");
        writer.Line("{");
        writer.Indent();
        writer.Line("Control Root { get; }");
        writer.Line("void Update(object value);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private sealed class LoopValue<T>(T value)");
        writer.Line("{");
        writer.Indent();
        writer.Line("public T Value { get; set; } = value;");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private sealed class LoopEntry<T>(");
        writer.Indent();
        writer.Line("LoopValue<T> value,");
        writer.Line("Control root,");
        writer.Line("Action refresh,");
        writer.Line("Action dispose) : ILoopEntry");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();
        writer.Line("public Control Root { get; } = root;");
        writer.Line();
        writer.Line("public void Update(object next)");
        writer.Line("{");
        writer.Indent();
        writer.Line("value.Value = (T)next;");
        writer.Line("refresh();");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("public void Dispose() => dispose();");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("private static ILoopEntry CreateLoopEntry<T>(");
        writer.Indent();
        writer.Line("T item,");
        writer.Line("Func<LoopValue<T>, (Control Root, Action Refresh, Action Dispose)> factory)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();
        writer.Line("var value = new LoopValue<T>(item);");
        writer.Line("var created = factory(value);");
        writer.Line("return new LoopEntry<T>(");
        writer.Indent();
        writer.Line("value,");
        writer.Line("created.Root,");
        writer.Line("created.Refresh,");
        writer.Line("created.Dispose);");
        writer.Unindent();
        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitRegionUpdater(
        CodeWriter writer,
        BoundComponentModel model,
        BoundRegion region,
        SourceDocument source,
        bool hasNativeChildSlots)
    {
        var loop = region.Loop;
        var templateControls = Flatten(loop.Body)
            .Select((control, index) => (control, index: index + 1))
            .ToArray();
        var dictionary = $"_region{region.Index}";

        writer.Line($"private void UpdateRegion{region.Index}()");
        writer.Line("{");
        writer.Indent();
        writer.Line("var nextEntries = new List<ILoopEntry>();");
        writer.Line("var seenKeys = new HashSet<object>();");
        writer.Line("var orderedKeys = new List<object>();");
        EmitLineMapping(writer, source, loop.SourceExpressionSpan);
        writer.Line(
            $"var sourceItems = " +
            $"({RewriteStateReferences(loop.SourceExpression, model.States)}).ToArray();");
        writer.Line("#line default");
        writer.Line($"foreach (var {loop.ItemName} in sourceItems)");
        writer.Line("{");
        writer.Indent();
        EmitLineMapping(writer, source, loop.KeyExpressionSpan);
        writer.Line($"object? key = {loop.KeyExpression};");
        writer.Line("#line default");
        writer.Line("if (key is null)");
        writer.Line("{");
        writer.Indent();
        writer.Line("""throw new InvalidOperationException("A keyed foreach produced a null key.");""");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("if (!seenKeys.Add(key))");
        writer.Line("{");
        writer.Indent();
        writer.Line("""throw new InvalidOperationException($"A keyed foreach produced duplicate key '{key}'.");""");
        writer.Unindent();
        writer.Line("}");
        writer.Line("orderedKeys.Add(key);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("var itemIndex = 0;");
        writer.Line($"foreach (var {loop.ItemName} in sourceItems)");
        writer.Line("{");
        writer.Indent();
        writer.Line("var key = orderedKeys[itemIndex++];");
        writer.Line();
        writer.Line($"if (!{dictionary}.TryGetValue(key, out var entry))");
        writer.Line("{");
        writer.Indent();
        writer.Line($"entry = CreateLoopEntry({loop.ItemName}, loopValue =>");
        writer.Line("{");
        writer.Indent();

        foreach (var (control, index) in templateControls)
        {
            writer.Line($"var control{index} = new {ControlType(control.Name)}();");
        }
        writer.Line("var disposeActions = new List<Action>();");

        writer.Line();
        foreach (var (control, index) in templateControls)
        {
            EmitTemplateStaticProperties(
                writer,
                control,
                index,
                loop.ItemName,
                model.States,
                source);
        }

        foreach (var (control, index) in templateControls)
        {
            EmitTemplateChildren(
                writer,
                control,
                index,
                templateControls,
                hasNativeChildSlots);
        }

        writer.Line();
        writer.Line("void Refresh()");
        writer.Line("{");
        writer.Indent();
        var hasItemBindings = templateControls.Any(candidate =>
            candidate.control.Members.Any(member =>
                MemberReferencesItem(member, loop.ItemName)));
        if (hasItemBindings)
        {
            writer.Line($"var {loop.ItemName} = loopValue.Value;");
        }

        foreach (var (control, index) in templateControls)
        {
            EmitTemplateBindings(
                writer,
                control,
                index,
                loop.ItemName,
                model.States,
                source);
        }

        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("Refresh();");

        foreach (var (control, index) in templateControls)
        {
            foreach (var (eventMember, eventIndex) in control.Members
                         .OfType<BoundEventMember>()
                         .Select((eventMember, eventIndex) => (eventMember, eventIndex)))
            {
                var eventArgsType = EventArgsType(eventMember.EventName);
                var handlerName = $"handler{index}_{eventIndex + 1}";
                if (eventArgsType is null)
                {
                    writer.Line($"control{index}.{eventMember.EventName} += (sender, e) =>");
                }
                else
                {
                    writer.Line(
                        $"EventHandler<{eventArgsType}> {handlerName} = (sender, e) =>");
                }

                writer.Line("{");
                writer.Indent();
                var body = eventMember.IsExpression
                    ? ExtractLambdaBody(eventMember.BodyText)
                    : eventMember.BodyText;
                if (ReferencesItem(body, loop.ItemName))
                {
                    writer.Line($"var {loop.ItemName} = loopValue.Value;");
                }

                EmitLineMapping(writer, source, eventMember.BodySpan);
                EmitBody(
                    writer,
                    RewriteStateReferences(body, model.States));
                writer.Line("#line default");
                writer.Unindent();
                writer.Line("};");
                if (eventArgsType is not null)
                {
                    writer.Line($"control{index}.{eventMember.EventName} += {handlerName};");
                    writer.Line(
                        $"disposeActions.Add(() => " +
                        $"control{index}.{eventMember.EventName} -= {handlerName});");
                }
            }
        }

        writer.Line();
        writer.Line("return (control1, (Action)Refresh, () =>");
        writer.Line("{");
        writer.Indent();
        writer.Line("foreach (var disposeAction in disposeActions)");
        writer.Line("{");
        writer.Indent();
        writer.Line("disposeAction();");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("});");
        writer.Unindent();
        writer.Line("});");
        writer.Line($"{dictionary}.Add(key, entry);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("else");
        writer.Line("{");
        writer.Indent();
        writer.Line($"entry.Update({loop.ItemName});");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("nextEntries.Add(entry);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("var staleKeys = new List<object>();");
        writer.Line($"foreach (var pair in {dictionary})");
        writer.Line("{");
        writer.Indent();
        writer.Line("if (!seenKeys.Contains(pair.Key))");
        writer.Line("{");
        writer.Indent();
        writer.Line("pair.Value.Dispose();");
        writer.Line("staleKeys.Add(pair.Key);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
        writer.Line("foreach (var staleKey in staleKeys)");
        writer.Line("{");
        writer.Indent();
        writer.Line($"{dictionary}.Remove(staleKey);");
        writer.Unindent();
        writer.Line("}");
        writer.Line();

        if (region.Parent.Kind == BoundControlKind.ItemsControl)
        {
            writer.Line(
                $"var orderChanged = " +
                $"_control{region.ParentIndex}!.Items.Count != nextEntries.Count;");
            writer.Line("for (var index = 0; !orderChanged && index < nextEntries.Count; index++)");
            writer.Line("{");
            writer.Indent();
            writer.Line(
                $"orderChanged = !ReferenceEquals(" +
                $"_control{region.ParentIndex}!.Items[index], nextEntries[index].Root);");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line("if (orderChanged)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_control{region.ParentIndex}!.Items.Clear();");
            writer.Line("foreach (var entry in nextEntries)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_control{region.ParentIndex}!.Items.Add(entry.Root);");
            writer.Unindent();
            writer.Line("}");
            writer.Unindent();
            writer.Line("}");
        }
        else
        {
            writer.Line(
                $"var orderChanged = " +
                $"_control{region.ParentIndex}!.Children.Count != nextEntries.Count;");
            writer.Line("for (var index = 0; !orderChanged && index < nextEntries.Count; index++)");
            writer.Line("{");
            writer.Indent();
            writer.Line(
                $"orderChanged = !ReferenceEquals(" +
                $"_control{region.ParentIndex}!.Children[index], nextEntries[index].Root);");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
            writer.Line("if (orderChanged)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_control{region.ParentIndex}!.Children.Clear();");
            writer.Line("foreach (var entry in nextEntries)");
            writer.Line("{");
            writer.Indent();
            writer.Line($"_control{region.ParentIndex}!.Children.Add(entry.Root);");
            writer.Unindent();
            writer.Line("}");
            writer.Unindent();
            writer.Line("}");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void EmitTemplateStaticProperties(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        string itemName,
        IReadOnlyList<BoundStateModel> states,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            if (property.Name == "class")
            {
                EmitLineMapping(writer, source, property.ExpressionSpan);
                writer.Line($"control{index}.Classes.Add({property.ExpressionText});");
                writer.Line("#line default");
                continue;
            }

            if (IsReactive(property.ExpressionText, states) ||
                ReferencesItem(property.ExpressionText, itemName))
            {
                continue;
            }

            var targetProperty = TargetProperty(control.Name, property.Name);
            if (targetProperty is null)
            {
                continue;
            }

            EmitLineMapping(writer, source, property.ExpressionSpan);
            var target = $"control{index}.{targetProperty}";
            writer.Line(
                $"{target} = " +
                $"{LowerPropertyValue(property.ExpressionText, property.NativeValueKind)};");
            writer.Line("#line default");
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (IsReactive(content.ExpressionText, states) ||
                ReferencesItem(content.ExpressionText, itemName))
            {
                continue;
            }

            EmitTemplateContent(writer, control, index, content, source);
        }
    }

    private static void EmitTemplateBindings(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        string itemName,
        IReadOnlyList<BoundStateModel> states,
        SourceDocument source)
    {
        foreach (var property in control.Members.OfType<BoundPropertyMember>())
        {
            if (property.Name == "class" ||
                (!IsReactive(property.ExpressionText, states) &&
                 !ReferencesItem(property.ExpressionText, itemName)))
            {
                continue;
            }

            var targetProperty = TargetProperty(control.Name, property.Name);
            if (targetProperty is null)
            {
                continue;
            }

            EmitLineMapping(writer, source, property.ExpressionSpan);
            var target = $"control{index}.{targetProperty}";
            var rewritten = RewriteStateReferences(property.ExpressionText, states);
            writer.Line(
                $"{target} = " +
                $"{LowerPropertyValue(rewritten, property.NativeValueKind)};");
            writer.Line("#line default");
        }

        foreach (var content in control.Members.OfType<BoundContentMember>())
        {
            if (!IsReactive(content.ExpressionText, states) &&
                !ReferencesItem(content.ExpressionText, itemName))
            {
                continue;
            }

            EmitTemplateContent(
                writer,
                control,
                index,
                content with
                {
                    ExpressionText = RewriteStateReferences(content.ExpressionText, states),
                },
                source);
        }
    }

    private static void EmitTemplateChildren(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        IReadOnlyList<(BoundControlModel control, int index)> controls,
        bool hasNativeChildSlots)
    {
        foreach (var child in control.Members.OfType<BoundChildMember>())
        {
            var childIndex = controls
                .First(candidate => ReferenceEquals(candidate.control, child.Child))
                .index;
            if (control.Name == "Column")
            {
                writer.Line($"control{index}.Children.Add(control{childIndex});");
            }
            else if (hasNativeChildSlots)
            {
                writer.Line($"AttachChild(control{index}, control{childIndex});");
            }
        }
    }

    private static void EmitTemplateContent(
        CodeWriter writer,
        BoundControlModel control,
        int index,
        BoundContentMember content,
        SourceDocument source)
    {
        EmitLineMapping(writer, source, content.ExpressionSpan);
        var line = control.Kind switch
        {
            BoundControlKind.Text => $"control{index}.Text = {content.ExpressionText};",
            BoundControlKind.ContentControl => $"control{index}.Content = {content.ExpressionText};",
            BoundControlKind.ItemsControl => $"control{index}.Items.Add({content.ExpressionText});",
            _ => null,
        };
        if (line is not null)
        {
            writer.Line(line);
        }

        writer.Line("#line default");
    }

    private static bool MemberReferencesItem(
        BoundControlMember member,
        string itemName) =>
        member switch
        {
            BoundPropertyMember property => ReferencesItem(property.ExpressionText, itemName),
            BoundContentMember content => ReferencesItem(content.ExpressionText, itemName),
            _ => false,
        };

    private static bool ReferencesItem(string expression, string itemName)
    {
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        return root.DescendantNodes()
            .OfType<IdentifierNameSyntax>()
            .Any(identifier =>
                identifier.Identifier.ValueText == itemName &&
                (identifier.Parent is not MemberAccessExpressionSyntax access ||
                 !ReferenceEquals(access.Name, identifier)));
    }

    private static string LowerPropertyValue(
        string expression,
        BoundNativeValueKind nativeValueKind)
    {
        if (nativeValueKind == BoundNativeValueKind.None)
        {
            return expression;
        }

        var syntax = SyntaxFactory.ParseExpression(expression);
        var typeName = nativeValueKind switch
        {
            BoundNativeValueKind.Thickness => "global::Avalonia.Thickness",
            BoundNativeValueKind.CornerRadius => "global::Avalonia.CornerRadius",
            _ => throw new InvalidOperationException(
                $"Unsupported native value kind '{nativeValueKind}'."),
        };

        if (IsNumericLiteral(syntax))
        {
            return $"new {typeName}({expression})";
        }

        var supportsTuple =
            nativeValueKind == BoundNativeValueKind.Thickness &&
            syntax is TupleExpressionSyntax { Arguments.Count: 2 or 4 } ||
            nativeValueKind == BoundNativeValueKind.CornerRadius &&
            syntax is TupleExpressionSyntax { Arguments.Count: 4 };
        if (supportsTuple && syntax is TupleExpressionSyntax tuple)
        {
            var arguments = string.Join(
                ", ",
                tuple.Arguments.Select(argument => argument.Expression.ToFullString().Trim()));
            return $"new {typeName}({arguments})";
        }

        return expression;
    }

    private static bool IsNumericLiteral(ExpressionSyntax syntax) =>
        syntax switch
        {
            LiteralExpressionSyntax literal =>
                literal.IsKind(SyntaxKind.NumericLiteralExpression),
            ParenthesizedExpressionSyntax parenthesized =>
                IsNumericLiteral(parenthesized.Expression),
            PrefixUnaryExpressionSyntax prefix
                when prefix.IsKind(SyntaxKind.UnaryMinusExpression) ||
                     prefix.IsKind(SyntaxKind.UnaryPlusExpression) =>
                IsNumericLiteral(prefix.Operand),
            _ => false,
        };

    private static void EmitBody(CodeWriter writer, string body)
    {
        body = body.Trim();
        if (body.Length == 0)
        {
            return;
        }

        foreach (var line in body.Split(
                     ["\r\n", "\n", "\r"],
                     StringSplitOptions.None))
        {
            writer.Line(line);
        }
    }

    private static bool HasNamedHandler(BoundEventMember eventMember) =>
        EventArgsType(eventMember.EventName) is not null;

    private static string? EventArgsType(string eventName) =>
        eventName switch
        {
            "Click" => "RoutedEventArgs",
            "TextChanged" => "TextChangedEventArgs",
            _ => null,
        };

    private static IEnumerable<BoundControlModel> Flatten(BoundControlModel root)
    {
        yield return root;
        foreach (var child in root.Members.OfType<BoundChildMember>())
        {
            foreach (var nested in Flatten(child.Child))
            {
                yield return nested;
            }
        }
    }

    private static string ControlType(string name) =>
        name switch
        {
            "Column" => "StackPanel",
            "Text" => "TextBlock",
            "Button" => "Button",
            _ => name,
        };

    private static string? TargetProperty(string controlName, string propertyName) =>
        (controlName, propertyName) switch
        {
            ("Text", "text") => "Text",
            ("Button", "text") => "Content",
            ("Column", "class") => null,
            _ => propertyName,
        };

    private static bool IsReactive(
        string expression,
        IReadOnlyList<BoundStateModel> states)
    {
        var stateNames = states
            .Select(state => state.Name)
            .ToHashSet(StringComparer.Ordinal);
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        return root.DescendantNodes()
            .OfType<MemberAccessExpressionSyntax>()
            .Any(access =>
                access.Expression is IdentifierNameSyntax identifier &&
                stateNames.Contains(identifier.Identifier.ValueText) &&
                access.Name.Identifier.ValueText == "Value");
    }

    private static string RewriteStateReferences(
        string expression,
        IReadOnlyList<BoundStateModel> states)
    {
        var replacements = new List<(int Start, int Length, string Text)>();
        var stateNames = states.ToDictionary(
            state => state.Name,
            state => state,
            StringComparer.Ordinal);
        var root = CSharpSyntaxTree.ParseText(expression).GetRoot();
        foreach (var access in root.DescendantNodes()
                     .OfType<MemberAccessExpressionSyntax>())
        {
            if (access.Expression is not IdentifierNameSyntax identifier ||
                !stateNames.TryGetValue(identifier.Identifier.ValueText, out var state))
            {
                continue;
            }

            var replacement = access.Name.Identifier.ValueText switch
            {
                "Value" => "_" + state.Name,
                "Update" => SetterName(state.Name),
                _ => null,
            };
            if (replacement is not null)
            {
                replacements.Add(
                    (access.SpanStart, access.Span.Length, replacement));
            }
        }

        foreach (var replacement in replacements
                     .OrderByDescending(candidate => candidate.Start))
        {
            expression = expression.Remove(
                    replacement.Start,
                    replacement.Length)
                .Insert(replacement.Start, replacement.Text);
        }

        return expression;
    }

    private static string ExtractLambdaBody(string expression)
    {
        var arrow = expression.IndexOf("=>", StringComparison.Ordinal);
        if (arrow < 0)
        {
            return expression;
        }

        var body = expression[(arrow + 2)..].Trim();
        return body.EndsWith(';')
            ? body
            : body + ";";
    }

    private static void EmitLineMapping(
        CodeWriter writer,
        SourceDocument source,
        SourceSpan span)
    {
        var (line, _) = source.GetLineAndColumn(span.Start);
        writer.Line($"#line {line} \"{EscapeLinePath(source.Path)}\"");
    }

    private static string SetterName(string stateName) =>
        "Set" + (stateName.Length == 0
            ? stateName
            : char.ToUpperInvariant(stateName[0]) + stateName[1..]);

    private sealed record BoundRegion(
        BoundControlModel Parent,
        int ParentIndex,
        BoundForEachMember Loop,
        int Index);

    private static string EscapeLinePath(string path) =>
        path.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
}
