<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lucent.Core/Lucent.Core.csproj" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="Svg.Skia" />
    <None Include="notices/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Pack="true" PackagePath="buildTransitive/notices/" />
    <None
      Include="$(NuGetPackageRoot)/skiasharp.nativeassets.win32/4.151.1/LICENSE.txt"
      Link="notices/SkiaSharp-LICENSE.txt"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
      Pack="true"
      PackagePath="buildTransitive/notices/SkiaSharp-LICENSE.txt"
    />
    <None
      Include="$(NuGetPackageRoot)/skiasharp.nativeassets.win32/4.151.1/THIRD-PARTY-NOTICES.txt"
      Link="notices/SkiaSharp-NOTICES.txt"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
      Pack="true"
      PackagePath="buildTransitive/notices/SkiaSharp-NOTICES.txt"
    />
    <None
      Include="$(NuGetPackageRoot)/harfbuzzsharp.nativeassets.win32/14.2.1.1/LICENSE.txt"
      Link="notices/HarfBuzzSharp-LICENSE.txt"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
      Pack="true"
      PackagePath="buildTransitive/notices/HarfBuzzSharp-LICENSE.txt"
    />
    <None
      Include="$(NuGetPackageRoot)/harfbuzzsharp.nativeassets.win32/14.2.1.1/THIRD-PARTY-NOTICES.txt"
      Link="notices/HarfBuzzSharp-NOTICES.txt"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
      Pack="true"
      PackagePath="buildTransitive/notices/HarfBuzzSharp-NOTICES.txt"
    />
    <None
      Include="buildTransitive/Lucent.Renderer.Skia.targets"
      Pack="true"
      PackagePath="buildTransitive/Lucent.Renderer.Skia.targets"
    />
  </ItemGroup>
</Project>
