<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotCompatible>false</IsAotCompatible>
    <IsTrimmable>false</IsTrimmable>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <Version>$(LucentLuiToolingVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lucent.Lui.Compiler/Lucent.Lui.Compiler.csproj" />
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Framework" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
</Project>
