<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lucent.Testing/Lucent.Testing.csproj" />
    <ProjectReference Include="../Lucent.Renderer.Skia/Lucent.Renderer.Skia.csproj" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
