<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <None Update="protocol.schema.json;Fixtures/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
