<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <IsTrimmable>false</IsTrimmable>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Lucent.Preview.Hosting/Lucent.Preview.Hosting.csproj" />
  </ItemGroup>
</Project>
