<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.0</TargetFramework><LangVersion>latest</LangVersion><Version>$(LucentLuiToolingVersion)</Version><GenerateDocumentationFile>true</GenerateDocumentationFile><IsAotCompatible>false</IsAotCompatible><IsTrimmable>false</IsTrimmable><EnableTrimAnalyzer>false</EnableTrimAnalyzer><IncludeBuildOutput>false</IncludeBuildOutput><EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lucent.Lui.Compiler/Lucent.Lui.Compiler.csproj" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
  </ItemGroup>
</Project>
