using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Lucent.Lui.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Lucent.Lui.Generator;

/// <summary>Generates same-name style and capability-bearing recipe helpers from Core descriptors.</summary>
[Generator]
public sealed class StyleFluencyGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedNullableFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
                | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var input = context.CompilationProvider.Select(
            static (compilation, _) =>
                new GenerationInput(compilation, LuiPropertyCatalog.Discover(compilation))
        );
        context.RegisterSourceOutput(
            input,
            static (production, value) =>
            {
                var source = Generate(value);
                if (source.Length != 0)
                    production.AddSource(
                        "Lucent.Core.StyleFluency.g.cs",
                        SourceText.From(source, Encoding.UTF8)
                    );
            }
        );
    }

    private static string Generate(GenerationInput input)
    {
        var descriptors = input
            .Descriptors.Where(descriptor => descriptor.DeclaredInCompilation)
            .ToArray();
        if (descriptors.Length == 0)
            return String.Empty;

        var source = new StringBuilder(
            "// <auto-generated />\n#nullable enable\nnamespace Lucent.Core;\n\n"
        );
        var styleMethods = OwnsStyleFluency(input.Compilation)
            ? AppendStyleMethods(source, input.Compilation, descriptors)
            : 0;
        var recipeMethods = CanAccessRecipeStyle(input.Compilation)
            ? AppendRecipeMethods(source, input.Compilation, descriptors)
            : 0;
        if (styleMethods == 0 && recipeMethods == 0)
            return String.Empty;
        return source.ToString();
    }

    private static bool OwnsStyleFluency(Compilation compilation)
    {
        var style = compilation.GetTypeByMetadataName("Lucent.Core.StyleFluency");
        return style is not null
            && SymbolEqualityComparer.Default.Equals(style.ContainingAssembly, compilation.Assembly)
            && (
                StringComparer.Ordinal.Equals(compilation.AssemblyName, "Lucent.Core")
                || !compilation.ReferencedAssemblyNames.Any(item =>
                    StringComparer.Ordinal.Equals(item.Name, "Lucent.Core")
                )
            );
    }

    private static int AppendStyleMethods(
        StringBuilder source,
        Compilation compilation,
        IReadOnlyList<LuiAuthorPropertyDescriptor> descriptors
    )
    {
        var style = compilation.GetTypeByMetadataName("Lucent.Core.StyleFluency");
        var count = 0;
        source.AppendLine("/// <summary>Generated same-name style helpers.</summary>");
        source.AppendLine("public static partial class StyleFluency");
        source.AppendLine("{");
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (
            var descriptor in descriptors.Where(descriptor =>
                (descriptor.Capabilities & LuiAuthoringCapabilities.Styled) != 0
            )
        )
        foreach (var name in descriptor.Names)
        {
            var memberName = EscapeIdentifier(name);
            if (memberName is null)
                continue;
            foreach (var input in Inputs(descriptor.InputForms))
            {
                var parameterType = InputType(descriptor.ValueTypeName, input);
                var key = memberName + "|" + parameterType;
                if (!emitted.Add(key) || HasStyleMethod(style, name, parameterType))
                    continue;
                source.AppendLine();
                AppendDocumentation(source, memberName, input);
                if (input == InputKind.Value && IsPriorityEligible(compilation, descriptor))
                    source.AppendLine(
                        "    [global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]"
                    );
                source.Append("    public static global::Lucent.Core.Style ");
                source.Append(memberName);
                source.AppendLine("(");
                source.AppendLine("        this global::Lucent.Core.Style style,");
                source.Append("        ");
                source.Append(parameterType);
                source.AppendLine(" value");
                source.AppendLine("    ) =>");
                source.Append("        style.");
                source.Append(input == InputKind.Reader ? "Bind" : "Set");
                source.Append('(');
                source.Append(FieldExpression(descriptor));
                source.Append(", value);");
                source.AppendLine();
                count++;
            }
        }
        source.AppendLine("}");
        return count;
    }

    private static int AppendRecipeMethods(
        StringBuilder source,
        Compilation compilation,
        IReadOnlyList<LuiAuthorPropertyDescriptor> descriptors
    )
    {
        var count = 0;
        source.AppendLine();
        source.AppendLine(
            "/// <summary>Generated style helpers for capability-bearing author recipes.</summary>"
        );
        source.AppendLine("public static class GeneratedAuthorRecipeStyleFluency");
        source.AppendLine("{");
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var capability in new[] { "StyledCapability", "StyledAccessibleCapability" })
        {
            var recipeType =
                "global::Lucent.Core.AuthorRecipe<global::Lucent.Core." + capability + ">";
            foreach (
                var descriptor in descriptors.Where(descriptor =>
                    (descriptor.Capabilities & LuiAuthoringCapabilities.Styled) != 0
                )
            )
            foreach (var name in descriptor.Names)
            {
                var memberName = EscapeIdentifier(name);
                if (memberName is null)
                    continue;
                foreach (var input in Inputs(descriptor.InputForms))
                {
                    var parameterType = InputType(descriptor.ValueTypeName, input);
                    var key = capability + "|" + memberName + "|" + parameterType;
                    if (!emitted.Add(key))
                        continue;
                    source.AppendLine();
                    AppendDocumentation(source, memberName, input);
                    if (input == InputKind.Value && IsPriorityEligible(compilation, descriptor))
                        source.AppendLine(
                            "    [global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]"
                        );
                    source.Append("    public static ");
                    source.Append(recipeType);
                    source.Append(' ');
                    source.Append(memberName);
                    source.AppendLine("(");
                    source.Append("        this ");
                    source.Append(recipeType);
                    source.AppendLine(" recipe,");
                    source.Append("        ");
                    source.Append(parameterType);
                    source.AppendLine(" value");
                    source.AppendLine("    ) =>");
                    source.AppendLine("        recipe.WithStyle(");
                    source.Append("            global::Lucent.Core.Style.Empty.");
                    source.Append(input == InputKind.Reader ? "Bind" : "Set");
                    source.Append('(');
                    source.Append(FieldExpression(descriptor));
                    source.AppendLine(", value));");
                    count++;
                }
            }
        }
        source.AppendLine("}");
        return count;
    }

    private static bool CanAccessRecipeStyle(Compilation compilation)
    {
        var recipe = compilation.GetTypeByMetadataName("Lucent.Core.AuthorRecipe`1");
        var method = recipe
            ?.GetMembers("WithStyle")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(item =>
                item.Parameters.Length == 1
                && item.Parameters[0].Type.ToDisplayString(FullyQualifiedNullableFormat)
                    == "global::Lucent.Core.Style"
            );
        return method is not null
            && method.DeclaredAccessibility is Accessibility.Internal or Accessibility.Public
            && SymbolEqualityComparer.Default.Equals(
                method.ContainingAssembly,
                compilation.Assembly
            );
    }

    private static bool HasStyleMethod(
        INamedTypeSymbol? style,
        string name,
        string parameterType
    ) =>
        style
            ?.GetMembers(name)
            .OfType<IMethodSymbol>()
            .Any(method =>
                method.IsStatic
                && method.Parameters.Length == 2
                && method.Parameters[0].Type.ToDisplayString(FullyQualifiedNullableFormat)
                    == "global::Lucent.Core.Style"
                && method.Parameters[1].Type.ToDisplayString(FullyQualifiedNullableFormat)
                    == parameterType
            ) == true;

    private static void AppendDocumentation(
        StringBuilder source,
        string memberName,
        InputKind input
    )
    {
        var inputDescription = input switch
        {
            InputKind.Reader => "a live reader",
            InputKind.Token => "a theme token",
            _ => "a snapshot value",
        };
        source.Append("    /// <summary>Applies ");
        source.Append(memberName);
        source.Append(" from ");
        source.Append(inputDescription);
        source.AppendLine(".</summary>");
    }

    private static bool IsPriorityEligible(
        Compilation compilation,
        LuiAuthorPropertyDescriptor descriptor
    )
    {
        var declaringType = compilation.GetTypeByMetadataName(descriptor.DeclaringTypeName);
        var field = declaringType
            ?.GetMembers(descriptor.FieldName)
            .OfType<IFieldSymbol>()
            .FirstOrDefault();
        var property = field?.Type as INamedTypeSymbol;
        var valueType = property?.TypeArguments.FirstOrDefault();
        return valueType is not null
            && (
                valueType.SpecialType == SpecialType.System_String
                || valueType.TypeKind is TypeKind.Struct or TypeKind.Enum
            );
    }

    private static string FieldExpression(LuiAuthorPropertyDescriptor descriptor) =>
        "global::"
        + descriptor.DeclaringTypeName
        + "."
        + (EscapeIdentifier(descriptor.FieldName) ?? descriptor.FieldName);

    private static string InputType(string valueType, InputKind input) =>
        input switch
        {
            InputKind.Reader => "global::System.Func<" + valueType + ">",
            InputKind.Token => "global::Lucent.Core.Token<" + valueType + ">",
            _ => valueType,
        };

    private static IEnumerable<InputKind> Inputs(LuiAuthoringInputForms forms)
    {
        if ((forms & LuiAuthoringInputForms.Value) != 0)
            yield return InputKind.Value;
        if ((forms & LuiAuthoringInputForms.Reader) != 0)
            yield return InputKind.Reader;
        if ((forms & LuiAuthoringInputForms.Token) != 0)
            yield return InputKind.Token;
    }

    private static string? EscapeIdentifier(string name)
    {
        if (!SyntaxFacts.IsValidIdentifier(name))
            return null;
        return
            SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None
            || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;
    }

    private sealed class GenerationInput
    {
        internal GenerationInput(
            Compilation compilation,
            IReadOnlyList<LuiAuthorPropertyDescriptor> descriptors
        )
        {
            Compilation = compilation;
            Descriptors = descriptors;
        }

        internal Compilation Compilation { get; }
        internal IReadOnlyList<LuiAuthorPropertyDescriptor> Descriptors { get; }
    }

    private enum InputKind
    {
        Value,
        Reader,
        Token,
    }
}
