<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <IsTrimmable>false</IsTrimmable>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../eng/lui-release-policy.json" LogicalName="Lucent.Tooling.Cache.ReleasePolicy.json" />
  </ItemGroup>
</Project>
