<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference
      Include="Lucent.Core"
      HintPath="../../src/Lucent.Core/bin/Release/net10.0/Lucent.Core.dll"
      Private="true"
    />
    <Reference
      Include="Lucent.Renderer.Skia"
      HintPath="../../src/Lucent.Renderer.Skia/bin/Release/net10.0/Lucent.Renderer.Skia.dll"
      Private="true"
    />
    <Reference
      Include="SkiaSharp"
      HintPath="$(UserProfile)/.nuget/packages/skiasharp/4.151.1/lib/net10.0/SkiaSharp.dll"
      Private="true"
    />
    <Reference
      Include="SkiaSharp.HarfBuzz"
      HintPath="$(UserProfile)/.nuget/packages/skiasharp.harfbuzz/4.151.1/lib/net10.0/SkiaSharp.HarfBuzz.dll"
      Private="true"
    />
    <Reference
      Include="HarfBuzzSharp"
      HintPath="$(UserProfile)/.nuget/packages/harfbuzzsharp/14.2.1.1/lib/net10.0/HarfBuzzSharp.dll"
      Private="true"
    />
    <Reference
      Include="Svg.Skia"
      HintPath="$(UserProfile)/.nuget/packages/svg.skia/5.2.3/lib/net10.0/Svg.Skia.dll"
      Private="true"
    />
    <Reference
      Include="Svg.Animation"
      HintPath="$(UserProfile)/.nuget/packages/svg.animation/5.2.3/lib/net10.0/Svg.Animation.dll"
      Private="true"
    />
    <Reference
      Include="Svg.Custom"
      HintPath="$(UserProfile)/.nuget/packages/svg.custom/5.2.3/lib/net10.0/Svg.Custom.dll"
      Private="true"
    />
    <Reference
      Include="Svg.Model"
      HintPath="$(UserProfile)/.nuget/packages/svg.model/5.2.3/lib/net10.0/Svg.Model.dll"
      Private="true"
    />
    <Reference
      Include="Svg.SceneGraph"
      HintPath="$(UserProfile)/.nuget/packages/svg.scenegraph/5.2.3/lib/net10.0/Svg.SceneGraph.dll"
      Private="true"
    />
    <Reference
      Include="ShimSkiaSharp"
      HintPath="$(UserProfile)/.nuget/packages/shimskiasharp/5.2.3/lib/net10.0/ShimSkiaSharp.dll"
      Private="true"
    />
    <Reference
      Include="ExCSS"
      HintPath="$(UserProfile)/.nuget/packages/excss/4.3.1/lib/net8.0/ExCSS.dll"
      Private="true"
    />
    <None
      Include="$(UserProfile)/.nuget/packages/skiasharp.nativeassets.win32/4.151.1/runtimes/win-x64/native/libSkiaSharp.dll"
      Link="libSkiaSharp.dll"
      CopyToOutputDirectory="PreserveNewest"
    />
    <None
      Include="$(UserProfile)/.nuget/packages/harfbuzzsharp.nativeassets.win32/14.2.1.1/runtimes/win-x64/native/libHarfBuzzSharp.dll"
      Link="libHarfBuzzSharp.dll"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
