$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dotnet = Join-Path $root '.dotnet/dotnet.exe'; if (!(Test-Path $dotnet)) { $dotnet = 'dotnet' }
$artifacts = Join-Path $root 'artifacts/lui-matrix'
$feed = Join-Path $root 'artifacts/lui-feed'
$consumer = Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/Consumer/Consumer.csproj'
$widgetPath = Join-Path (Split-Path $consumer) 'Widget.lui'
$widgetSource = Get-Content $widgetPath -Raw
$config = Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/NuGet.config'
$env:NUGET_PACKAGES = Join-Path $root 'artifacts/lui-packages'

function Invoke-Dotnet([string[]]$arguments) {
    & $dotnet @arguments
    if ($LASTEXITCODE -ne 0) { throw "dotnet $($arguments -join ' ') failed ($LASTEXITCODE)." }
}

function Expected-Failure([string[]]$arguments, [string]$mustContain) {
    $output = (& $dotnet @arguments 2>&1) -join "`n"
    if ($LASTEXITCODE -eq 0 -or $output -notmatch [regex]::Escape($mustContain)) {
        throw "Expected '$mustContain' from dotnet $($arguments -join ' ').`n$output"
    }
    $output
}

function Write-Project([string]$directory, [string]$name, [string]$body) {
    New-Item $directory -ItemType Directory -Force | Out-Null
    $body = $body.Replace('</Project>', '<PropertyGroup><OutputType>Exe</OutputType><IsAotCompatible>false</IsAotCompatible><IsTrimmable>false</IsTrimmable><EnableTrimAnalyzer>false</EnableTrimAnalyzer></PropertyGroup></Project>')
    $core = Join-Path $root 'src/Lucent.Core/bin/Debug/net10.0/Lucent.Core.dll'
    $body = $body.Replace('</Project>', ('<ItemGroup><Reference Include="Lucent.Core"><HintPath>' + $core + '</HintPath></Reference></ItemGroup></Project>'))
    Set-Content (Join-Path $directory "$name.csproj") $body
    Set-Content (Join-Path $directory 'NuGet.config') ('<configuration><packageSources><clear /><add key="local" value="' + $feed + '" /></packageSources></configuration>')
    Set-Content (Join-Path $directory 'Program.cs') 'Console.WriteLine("lui sdk consumer");'
}

Remove-Item $feed, $env:NUGET_PACKAGES, $artifacts -Recurse -Force -ErrorAction Ignore
New-Item $artifacts -ItemType Directory -Force | Out-Null
try {
    $coreProject = Join-Path $root 'src/Lucent.Core/Lucent.Core.csproj'
    Invoke-Dotnet @('restore', $coreProject, '--locked-mode')
    Invoke-Dotnet @('build', $coreProject, '-c', 'Debug', '--no-restore', '-warnaserror')
    $sdk = Join-Path $root 'src/Lucent.Lui.Sdk/Lucent.Lui.Sdk.csproj'
    Invoke-Dotnet @('restore', $sdk, '--locked-mode')
    Invoke-Dotnet @('pack', $sdk, '-c', 'Release', '--no-restore', '-o', $feed)
    @"
<configuration><packageSources><clear /><add key="local" value="$feed" /></packageSources></configuration>
"@ | Set-Content $config
    Invoke-Dotnet @('restore', $consumer, '--configfile', $config, '--locked-mode', '--force-evaluate')
    Remove-Item $config -Force

    # The checked-in consumer is the smallest package, generated-output, and preprocess smoke.
    Invoke-Dotnet @('build', $consumer, '--no-restore', '-warnaserror', '-p:LucentLuiFormatCheck=true')
    [IO.File]::WriteAllText($widgetPath, 'internal component Widget() { <Row/> }')
    Expected-Failure @('build', $consumer, '--no-restore', '-p:LucentLuiFormatCheck=true') 'MSB3073' | Out-Null
    [IO.File]::WriteAllText($widgetPath, $widgetSource)
    Invoke-Dotnet @('build', $consumer, '--no-restore', '-warnaserror', '-p:LucentLuiFormatCheck=true')
    $items = (& $dotnet 'msbuild' $consumer '-getItem:AdditionalFiles') -join "`n"
    if ($LASTEXITCODE -or $items -notmatch 'Widget\.lui' -or $items -match 'bin|obj|Hidden|\.g\.lui|\.generated\.lui') { throw 'SDK default glob evaluated an excluded input.' }
    $preprocess = Join-Path $root 'artifacts/lui-consumer.preprocessed.xml'
    Invoke-Dotnet @('msbuild', $consumer, "-preprocess:$preprocess")
    if (!(Select-String -LiteralPath $preprocess -SimpleMatch 'LucentLuiLogicalPath="%(RecursiveDir)%(Filename)%(Extension)"' -Quiet)) { throw 'SDK props were absent from preprocess evidence.' }
    $generated = Get-ChildItem (Join-Path (Split-Path $consumer) 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore
    $generatedText = $generated | Get-Content -Raw
    if (!$generated -or $generatedText -notmatch '<auto-generated/>' -or $generatedText -notmatch 'GeneratedCodeAttribute') { throw 'Generated inspection output lacks required markers.' }
    if ($generatedText -notmatch 'global::Consumer\.Tokens\.DensitySpacing' -or $generatedText -match 'using static global::Consumer\.Tokens') { throw 'RootNamespace Tokens were not style-scoped and fully qualified.' }
    if ([regex]::Matches($generatedText, 'global::Lucent\.Core\.Components\.Text\(content:').Count -ne 2) { throw 'Body and named scalar expressions did not both lower through the generated Text content argument.' }
    Invoke-Dotnet @('clean', $consumer)
    if (Get-ChildItem (Join-Path (Split-Path $consumer) 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore) { throw 'Clean left generated source.' }

    # A mutable copy proves add/change/delete/rename without touching the fixture.
    $matrix = Join-Path $artifacts 'consumer'
    New-Item $matrix -ItemType Directory -Force | Out-Null
    Copy-Item (Join-Path (Split-Path $consumer) 'Consumer.csproj'), (Join-Path (Split-Path $consumer) 'Program.cs'), (Join-Path (Split-Path $consumer) 'Tokens.cs'), (Join-Path (Split-Path $consumer) 'Widget.lui'), (Join-Path (Split-Path $consumer) 'packages.lock.json') $matrix
    Set-Content (Join-Path $matrix 'NuGet.config') ('<configuration><packageSources><clear /><add key="local" value="' + $feed + '" /></packageSources></configuration>')
    New-Item (Join-Path $matrix '.hidden'), (Join-Path $matrix 'bin'), (Join-Path $matrix 'obj') -ItemType Directory -Force | Out-Null
    Set-Content (Join-Path $matrix '.hidden/Hidden.lui'), (Join-Path $matrix 'bin/Bin.lui'), (Join-Path $matrix 'obj/Obj.lui'), (Join-Path $matrix 'Ignored.g.lui'), (Join-Path $matrix 'Ignored.generated.lui') 'ignored'
    $matrixProject = Join-Path $matrix 'Consumer.csproj'
    Invoke-Dotnet @('restore', $matrixProject, '--configfile', (Join-Path $matrix 'NuGet.config'), '--locked-mode')
    Invoke-Dotnet @('build', $matrixProject, '--no-restore', '-t:Rebuild', '-warnaserror')
    $before = Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs'
    if ($before.Count -ne 1) { throw 'Baseline did not produce exactly one generated document.' }
    $beforeText = Get-Content $before[0].FullName -Raw
    Set-Content (Join-Path $matrix 'Added.lui') 'internal component Added() { <Row /> }'
    Invoke-Dotnet @('build', $matrixProject, '--no-restore', '-t:Rebuild', '-warnaserror')
    if ((Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs').Count -ne 2) { throw 'Adding a .lui did not add one generated source.' }
    Set-Content (Join-Path $matrix 'Widget.lui') 'internal component Widget() { <Row name="changed" /> }'
    Invoke-Dotnet @('build', $matrixProject, '--no-restore', '-t:Rebuild', '-warnaserror')
    $after = Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' | Where-Object Name -eq $before[0].Name
    if (!$after -or (Get-Content $after.FullName -Raw) -eq $beforeText) { throw 'Changing a .lui did not update generated source.' }
    Remove-Item (Join-Path $matrix 'Added.lui')
    Invoke-Dotnet @('build', $matrixProject, '--no-restore', '-t:Rebuild', '-warnaserror')
    if ((Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs').Count -ne 1) { throw 'Deleting a .lui left stale generated source.' }
    Move-Item (Join-Path $matrix 'Widget.lui') (Join-Path $matrix 'Renamed.lui')
    Invoke-Dotnet @('build', $matrixProject, '--no-restore', '-t:Rebuild', '-warnaserror')
    $renamed = Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs'
    if ($renamed.Count -ne 1 -or (Get-Content $renamed[0].FullName -Raw) -notmatch 'Renamed\.lui') { throw 'Renaming a .lui left stale identity or did not emit the new identity.' }
    Invoke-Dotnet @('clean', $matrixProject)
    if (Get-ChildItem (Join-Path $matrix 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore) { throw 'Matrix clean left generated inspection output.' }

    $excluded = Join-Path $artifacts 'excluded'
    Write-Project $excluded 'Excluded' '<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk/0.2.0"><PropertyGroup><TargetFramework>net10.0</TargetFramework><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles><EnableDefaultLuiItems>false</EnableDefaultLuiItems></PropertyGroup><ItemGroup><AdditionalFiles Include="Widget.lui" LucentLuiLogicalPath="explicit/Widget.lui" /><AdditionalFiles Include="one/Widget.lui" /><AdditionalFiles Include="two/Widget.lui" /></ItemGroup></Project>'
    New-Item (Join-Path $excluded 'one'), (Join-Path $excluded 'two') -ItemType Directory -Force | Out-Null
    Set-Content (Join-Path $excluded 'Widget.lui') 'internal component Explicit() { <Row /> }'; Set-Content (Join-Path $excluded 'one/Widget.lui') 'internal component One() { <Row /> }'; Set-Content (Join-Path $excluded 'two/Widget.lui') 'internal component Two() { <Row /> }'
    Invoke-Dotnet @('restore', (Join-Path $excluded 'Excluded.csproj'), '--configfile', (Join-Path $excluded 'NuGet.config'))
    $explicitItems = (& $dotnet 'msbuild' (Join-Path $excluded 'Excluded.csproj') '-getItem:AdditionalFiles') -join "`n"
    if ($LASTEXITCODE -or $explicitItems -notmatch 'explicit/Widget\.lui' -or $explicitItems -notmatch 'one[\\/]Widget\.lui' -or $explicitItems -notmatch 'two[\\/]Widget\.lui' -or $explicitItems -match 'Consumer|obj|bin') { throw 'Explicit AdditionalFiles did not retain or receive project-relative logical paths.' }
    Invoke-Dotnet @('build', (Join-Path $excluded 'Excluded.csproj'), '--no-restore', '-warnaserror')
    $excludedGenerated = Get-ChildItem (Join-Path $excluded 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs'
    $excludedText = ($excludedGenerated | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
    if ($excludedGenerated.Count -ne 3 -or $excludedText -notmatch 'explicit/Widget\.lui' -or $excludedText -notmatch 'one/Widget\.lui' -or $excludedText -notmatch 'two/Widget\.lui') { throw 'Nested explicit .lui files lost distinct identities or explicit metadata.' }

    $multi = Join-Path $artifacts 'multi'
    Write-Project $multi 'Multi' '<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk/0.2.0"><PropertyGroup><TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles></PropertyGroup></Project>'
    Set-Content (Join-Path $multi 'Widget.lui') 'internal component Widget() { <Row /> }'
    Invoke-Dotnet @('restore', (Join-Path $multi 'Multi.csproj'), '--configfile', (Join-Path $multi 'NuGet.config'))
    Invoke-Dotnet @('build', (Join-Path $multi 'Multi.csproj'), '--no-restore', '-f', 'net10.0', '-warnaserror')
    Invoke-Dotnet @('build', (Join-Path $multi 'Multi.csproj'), '--no-restore', '-f', 'net10.0-windows', '-warnaserror')
    $multiGenerated = Get-ChildItem (Join-Path $multi 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs'
    if (($multiGenerated | Select-Object -ExpandProperty Name -Unique).Count -ne 1 -or $multiGenerated.Count -ne 2) { throw 'Multi-target generation produced ambiguous or missing identities.' }

    $invalid = Join-Path $artifacts 'invalid'
    Write-Project $invalid 'Invalid' '<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk/0.2.0"><PropertyGroup><TargetFramework>net10.0</TargetFramework><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles></PropertyGroup></Project>'
    Set-Content (Join-Path $invalid 'Widget.lui') 'internal component Widget() { <Row /> }'
    Invoke-Dotnet @('restore', (Join-Path $invalid 'Invalid.csproj'), '--configfile', (Join-Path $invalid 'NuGet.config'))
    Invoke-Dotnet @('build', (Join-Path $invalid 'Invalid.csproj'), '--no-restore', '-warnaserror')
    if (!(Get-ChildItem (Join-Path $invalid 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore)) { throw 'Valid input did not produce generated inspection output.' }
    [IO.File]::WriteAllText((Join-Path $invalid 'Widget.lui'), '')
    Expected-Failure @('build', (Join-Path $invalid 'Invalid.csproj'), '--no-restore') 'LUI1003' | Out-Null
    if (Get-ChildItem (Join-Path $invalid 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore) { throw 'Invalid input produced generated source.' }

    $duplicate = Join-Path $artifacts 'duplicate'
    Write-Project $duplicate 'Duplicate' '<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk/0.2.0"><PropertyGroup><TargetFramework>net10.0</TargetFramework><EnableDefaultLuiItems>false</EnableDefaultLuiItems><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles></PropertyGroup><ItemGroup><AdditionalFiles Include="One.lui" LucentLuiLogicalPath="same/Main.lui" /><AdditionalFiles Include="Two.lui" LucentLuiLogicalPath="same/Main.lui" /></ItemGroup></Project>'
    Set-Content (Join-Path $duplicate 'One.lui') 'internal component One() { <Row /> }'; Set-Content (Join-Path $duplicate 'Two.lui') 'internal component Two() { <Row /> }'
    Invoke-Dotnet @('restore', (Join-Path $duplicate 'Duplicate.csproj'), '--configfile', (Join-Path $duplicate 'NuGet.config'))
    Expected-Failure @('build', (Join-Path $duplicate 'Duplicate.csproj'), '--no-restore') 'LUI4002' | Out-Null
    if (Get-ChildItem (Join-Path $duplicate 'obj') -Recurse -Filter 'Lucent.Lui.*.g.cs' -ErrorAction Ignore) { throw 'Duplicate logical paths produced generated source.' }

    # Framework namespaces/components are ordinary global usings; style properties stay .lui-style scoped.
    $using = Join-Path $artifacts 'using'
    $core = (Join-Path $root 'src/Lucent.Core/bin/Debug/net10.0/Lucent.Core.dll')
    if (!(Test-Path $core)) { throw 'Build Lucent.Core before running this proof.' }
    $usingProject = '<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk/0.2.0"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><Reference Include="Lucent.Core"><HintPath>' + $core + '</HintPath></Reference></ItemGroup></Project>'
    Write-Project $using 'Using' $usingProject
    Set-Content (Join-Path $using 'Author.cs') 'namespace Author; public readonly struct Color { public static Color Parse(string value) => default; } public static class Theme { public static int TextColor => 0; }'
    Set-Content (Join-Path $using 'Program.cs') 'using static Author.Theme; var color = Author.Color.Parse("#010203"); var property = TextColor; var style = Style.Empty; Console.WriteLine(color); Console.WriteLine(property); Console.WriteLine(style);'
    Invoke-Dotnet @('restore', (Join-Path $using 'Using.csproj'), '--configfile', (Join-Path $using 'NuGet.config'))
    $evaluatedUsings = (& $dotnet 'msbuild' (Join-Path $using 'Using.csproj') '-getItem:Using') -join "`n"
    if ($LASTEXITCODE -or $evaluatedUsings -notmatch 'Lucent.Core') { throw 'Default Lucent.Core global using was not evaluated.' }
    if ($evaluatedUsings -match 'Lucent.Core.Components') { throw 'Built-in Components leaked into project-wide global usings.' }
    if ($evaluatedUsings -match 'Lucent.Core.(Layout|Visual|Typography|Input)Properties') { throw 'Framework style properties leaked into project-wide global usings.' }
    Invoke-Dotnet @('build', (Join-Path $using 'Using.csproj'), '--no-restore', '-warnaserror')
    (Get-Content (Join-Path $using 'Using.csproj') -Raw).Replace('</PropertyGroup>', '<LucentLuiImplicitUsings>false</LucentLuiImplicitUsings></PropertyGroup>') | Set-Content (Join-Path $using 'Using.csproj')
    (Get-Content (Join-Path $using 'Program.cs') -Raw).Replace('using static Author.Theme;', 'using Lucent.Core; using static Author.Theme;') | Set-Content (Join-Path $using 'Program.cs')
    Invoke-Dotnet @('build', (Join-Path $using 'Using.csproj'), '--no-restore', '-warnaserror')

    # The published consumer also exercises content forwarding and retained payloads through the packed SDK.
    Copy-Item (Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/Content/*.lui'), (Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/Content/ContentConsumer.cs') $matrix
    Copy-Item (Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/Retained/Retained.lui'), (Join-Path $root 'tests/Lucent.Lui.Sdk.Fixtures/Retained/RetainedConsumer.cs') $matrix
    Set-Content (Join-Path $matrix 'Program.cs') 'Consumer.ContentConsumer.Run(); Consumer.RetainedConsumer.Run(); Console.WriteLine("lui sdk consumer");'

    # Publish/run is the runtime-asset boundary proof; analyzers must not enter the app.
    $publish = Join-Path $artifacts 'publish'
    $publishConfig = Join-Path $artifacts 'publish.NuGet.config'
    @"
<configuration><packageSources><clear /><add key="local" value="$feed" /><add key="nuget.org" value="https://api.nuget.org/v3/index.json" /></packageSources></configuration>
"@ | Set-Content $publishConfig
    Invoke-Dotnet @('publish', $matrixProject, '-c', 'Release', '-r', 'win-x64', '--self-contained', 'true', '-p:PublishAot=true', '--configfile', $publishConfig, '-o', $publish)
    $exe = Join-Path $publish 'Consumer.exe'
    if (!(Test-Path $exe)) { throw 'NativeAOT consumer executable is missing.' }
    $consumerOutput = @(& $exe)
    $consumerOutput | Write-Output
    if ($LASTEXITCODE -ne 0 -or ($consumerOutput -join "`n") -notmatch 'content forwarding SDK proof: PASS' -or ($consumerOutput -join "`n") -notmatch 'retained payload SDK proof: PASS' -or ($consumerOutput -join "`n") -notmatch 'lui sdk consumer') { throw 'NativeAOT consumer did not pass its runtime contracts.' }
    $actual = Get-ChildItem $publish -Recurse -File | ForEach-Object { $_.FullName.Substring($publish.Length + 1).Replace('\', '/') } | Sort-Object
    $allowed = @('Consumer.exe', 'Consumer.pdb', 'Lucent.Core.pdb', 'Lucent.Core.xml')
    if ((Compare-Object $allowed $actual)) { throw "NativeAOT runtime inventory differs from its fail-closed allowlist: $($actual -join ', ')." }
}
finally {
    [IO.File]::WriteAllText($widgetPath, $widgetSource)
    Remove-Item $config, (Join-Path $root 'artifacts/lui-matrix/publish.NuGet.config') -Force -ErrorAction Ignore
}
