using System.Globalization;
using System.Reflection;
using Lucent.Core;
using Lucent.Lui.Compiler;
using Lucent.Lui.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Lucent.Lui.Generator.Tests;

[TestClass]
public sealed class GeneratorTests
{
    private const string Valid =
        "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Widget() { <Row /> }";

    [TestMethod]
    public void DiagnosticsAndGeneratedIdentity()
    {
        Assert(
            new LuiDocumentIdentity("views\\Main.lui").LogicalPath == "views/Main.lui",
            "logical paths were not normalized."
        );
        foreach (
            var path in new[]
            {
                "/views/Main.lui",
                "\\views\\Main.lui",
                "C:/views/Main.lui",
                "C:\\views\\Main.lui",
                "C:Main.lui",
                "views/./Main.lui",
                "views/../Main.lui",
                ".",
                "..",
            }
        )
        {
            try
            {
                _ = new LuiDocumentIdentity(path);
                throw new InvalidOperationException(
                    "rooted or traversing path was accepted: " + path
                );
            }
            catch (ArgumentException) { }
        }
        Assert(
            new LuiFreshnessIdentity(
                "1",
                "sample",
                new LuiDocumentIdentity("views/Main.lui"),
                "a",
                "preview"
            ).HintName
                == new LuiFreshnessIdentity(
                    "1",
                    "sample",
                    new LuiDocumentIdentity("views/Main.lui"),
                    "a",
                    "preview"
                ).HintName,
            "hint identity was not deterministic."
        );
        Assert(
            !new LuiProjectIdentity("C:/one", "preview").Equals(
                new LuiProjectIdentity("C:/two", "preview")
            ),
            "absolute project roots must remain distinct project identities."
        );
        Assert(
            new LuiDocumentIdentity("views/Main.lui").StableId
                == new LuiDocumentIdentity("views/Main.lui").StableId,
            "document identity changed across absolute roots."
        );
        var rootA = Run(new TextFile("C:/one/views/Main.lui", Valid, "views/Main.lui"));
        var rootB = Run(new TextFile("C:/two/views/Main.lui", Valid, "views/Main.lui"));
        Assert(
            rootA.Results.Single().GeneratedSources.Single().HintName
                == rootB.Results.Single().GeneratedSources.Single().HintName,
            "absolute checkout roots changed a project-relative generated identity."
        );
        var valid = Run(new TextFile("C:/consumer/views/Main.lui", Valid, "views/Main.lui"));
        var generated = valid.Results.Single().GeneratedSources.Single().SourceText.ToString();
        Assert(
            generated.Contains("<auto-generated/>")
                && generated.Contains("GeneratedCodeAttribute")
                && generated.Contains("Row(content: [])")
                && generated.Contains("#line"),
            "generator did not emit mapped recipe source."
        );
        Assert(valid.Diagnostics.Length == 0, "valid probe reported a diagnostic.");
        var scalarExpression = Run(
            new TextFile(
                "C:/consumer/views/Scalar.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Scalar(string value) { <Text>{value}</Text> }",
                "views/Scalar.lui"
            )
        );
        var scalarGenerated = scalarExpression
            .Results.Single()
            .GeneratedSources.Single()
            .SourceText.ToString();
        Assert(
            scalarExpression.Diagnostics.Length == 0
                && scalarGenerated.Contains(
                    "global::Lucent.Core.Components.Text(content:",
                    StringComparison.Ordinal
                )
                && scalarGenerated.Contains("\nvalue\n#line hidden", StringComparison.Ordinal),
            "generator did not publish the scalar body expression through the ordinary component call."
        );
        var namedScalarExpression = Run(
            new TextFile(
                "C:/consumer/views/Scalar.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Scalar(string value) { <Text content={value} /> }",
                "views/Scalar.lui"
            )
        );
        Assert(
            namedScalarExpression.Diagnostics.Length == 0
                && namedScalarExpression
                    .Results.Single()
                    .GeneratedSources.Single()
                    .SourceText.ToString()
                    .Contains(
                        "global::Lucent.Core.Components.Text(content:",
                        StringComparison.Ordinal
                    ),
            "named and body scalar expressions did not select the same generated component parameter."
        );
        var malformed = Run(
            new TextFile(
                "C:/consumer/Broken.lui",
                "using static Lucent.Core.Components; internal component Broken() { <Row>",
                "Broken.lui"
            )
        );
        Assert(
            malformed.Diagnostics.Any(diagnostic =>
                diagnostic.Id.StartsWith("LUI1", StringComparison.Ordinal)
            )
                && malformed.Results.Single().GeneratedSources.Length == 0,
            "syntax-invalid input emitted a probe."
        );
        var empty = Run(new TextFile("C:/consumer/Empty.lui", "", "Empty.lui"));
        Assert(
            empty.Diagnostics.Any(diagnostic =>
                diagnostic.Id == "LUI1003"
                && diagnostic.Location.GetLineSpan().Path == "C:/consumer/Empty.lui"
            ),
            "empty input diagnostic lost its exact path."
        );
        var unreadable = Run(new TextFile("C:/consumer/Unreadable.lui", null, "Unreadable.lui"));
        Assert(
            unreadable.Diagnostics.Single().Id == "LUI4001"
                && unreadable.Results.Single().GeneratedSources.Length == 0
                && unreadable.Diagnostics.Single().Location.GetLineSpan().Path
                    == "C:/consumer/Unreadable.lui",
            "unreadable input did not fail closed with its exact path."
        );
        var invalidPath = Run(new TextFile("C:/consumer/Main.lui", Valid, "../Main.lui"));
        Assert(
            invalidPath.Diagnostics.Single().Id == "LUI4003"
                && invalidPath.Results.Single().GeneratedSources.Length == 0,
            "invalid metadata did not fail closed."
        );
        var blankPath = Run(new TextFile("C:/consumer/Main.lui", Valid, " "));
        Assert(
            blankPath.Diagnostics.Single().Id == "LUI4003"
                && blankPath.Results.Single().GeneratedSources.Length == 0,
            "blank metadata did not fail closed."
        );
        var duplicate = Run(
            new TextFile("C:/one/Main.lui", Valid, "same/Main.lui"),
            new TextFile("C:/two/Main.lui", Valid, "same/Main.lui")
        );
        Assert(
            duplicate.Diagnostics.Length == 2
                && duplicate.Diagnostics.All(diagnostic => diagnostic.Id == "LUI4002")
                && duplicate.Results.Single().GeneratedSources.Length == 0,
            "duplicate inputs emitted stale source."
        );
        var changed = Run(
            new TextFile(
                "C:/consumer/views/Main.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Widget() { <Row name=\"changed\" /> }",
                "views/Main.lui"
            )
        );
        Assert(
            changed.Results.Single().GeneratedSources.Single().SourceText.ToString()
                != valid.Results.Single().GeneratedSources.Single().SourceText.ToString(),
            "changed input did not update generated source."
        );
        var invalidComponent = Run(
            new TextFile(
                "C:/consumer/Bad.lui",
                "namespace Sample; using Lucent.Core; internal component Bad() { <StringBuilder /> }",
                "Bad.lui"
            )
        );
        Assert(
            invalidComponent.Diagnostics.Any(diagnostic => diagnostic.Id == "LUI2001")
                && invalidComponent.Results.Single().GeneratedSources.Length == 0,
            "non-component tags emitted output."
        );
        var mixed = Run(
            new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"),
            new TextFile(
                "C:/consumer/Bad.lui",
                "namespace Sample; using Lucent.Core; internal component Bad() { <StringBuilder /> }",
                "Bad.lui"
            )
        );
        Assert(
            mixed.Diagnostics.Any(diagnostic => diagnostic.Id == "LUI2001")
                && mixed.Results.Single().GeneratedSources.Length == 1
                && mixed
                    .Results.Single()
                    .GeneratedSources.Single()
                    .SourceText.ToString()
                    .Contains("Widget"),
            "an invalid component suppressed another document's output."
        );
    }

    [TestMethod]
    public void GlobalOptionsInvalidateOutput()
    {
        var epochOne = RunWithGlobal(
            new Dictionary<string, string>
            {
                ["build_property.LucentLuiProjectEpoch"] = "epoch-1",
                ["build_property.LucentLuiProjectIdentity"] = "evaluated-project",
                ["build_property.LucentLuiCompilerOptions"] = "nullable:enable",
                ["build_property.LucentLuiLangVersion"] = "preview",
            },
            new TextFile("C:/consumer/Epoch.lui", Valid, "Epoch.lui")
        );
        var epochTwo = RunWithGlobal(
            new Dictionary<string, string>
            {
                ["build_property.LucentLuiProjectEpoch"] = "epoch-2",
                ["build_property.LucentLuiProjectIdentity"] = "evaluated-project",
                ["build_property.LucentLuiCompilerOptions"] = "nullable:enable",
                ["build_property.LucentLuiLangVersion"] = "preview",
            },
            new TextFile("C:/consumer/Epoch.lui", Valid, "Epoch.lui")
        );
        Assert(
            epochOne.Results.Single().GeneratedSources.Single().SourceText.ToString()
                != epochTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(),
            "project epoch change did not prevent stale publication."
        );
        var optionsOne = RunWithGlobal(
            new Dictionary<string, string>
            {
                ["build_property.LucentLuiCompilerOptions"] = "nullable:enable",
                ["build_property.LucentLuiDefines"] = "ONE",
            },
            new TextFile("C:/consumer/Options.lui", Valid, "Options.lui")
        );
        var optionsTwo = RunWithGlobal(
            new Dictionary<string, string>
            {
                ["build_property.LucentLuiCompilerOptions"] = "nullable:disable",
                ["build_property.LucentLuiDefines"] = "ONE",
            },
            new TextFile("C:/consumer/Options.lui", Valid, "Options.lui")
        );
        var definesTwo = RunWithGlobal(
            new Dictionary<string, string>
            {
                ["build_property.LucentLuiCompilerOptions"] = "nullable:disable",
                ["build_property.LucentLuiDefines"] = "TWO",
            },
            new TextFile("C:/consumer/Options.lui", Valid, "Options.lui")
        );
        Assert(
            optionsOne.Results.Single().GeneratedSources.Single().SourceText.ToString()
                != optionsTwo.Results.Single().GeneratedSources.Single().SourceText.ToString()
                && optionsTwo.Results.Single().GeneratedSources.Single().SourceText.ToString()
                    != definesTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(),
            "compiler options or defines change did not prevent stale publication."
        );
        var rootNamespaceOne = RunWithGlobal(
            new Dictionary<string, string> { ["build_property.RootNamespace"] = "Sample.One" },
            new TextFile("C:/consumer/Root.lui", Valid, "Root.lui")
        );
        var rootNamespaceTwo = RunWithGlobal(
            new Dictionary<string, string> { ["build_property.RootNamespace"] = "Sample.Two" },
            new TextFile("C:/consumer/Root.lui", Valid, "Root.lui")
        );
        Assert(
            rootNamespaceOne.Results.Single().GeneratedSources.Single().SourceText.ToString()
                != rootNamespaceTwo
                    .Results.Single()
                    .GeneratedSources.Single()
                    .SourceText.ToString(),
            "RootNamespace change did not invalidate generated map identity."
        );
        var versionOne = RunWithGlobal(
            new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-3" },
            new TextFile("C:/consumer/Version.lui", Valid, "Version.lui", "v1")
        );
        var versionTwo = RunWithGlobal(
            new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-3" },
            new TextFile("C:/consumer/Version.lui", Valid, "Version.lui", "v2")
        );
        Assert(
            versionOne.Results.Single().GeneratedSources.Single().SourceText.ToString()
                != versionTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(),
            "host document version did not invalidate generated map identity."
        );
    }

    [TestMethod]
    public void SiblingSymbolsAndStableIdentity()
    {
        var siblings = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; public component A() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Sample.Components; internal component B() { <A /> }",
                "B.lui"
            )
        );
        Assert(
            siblings.Diagnostics.Length == 0
                && siblings.Results.Single().GeneratedSources.Length == 2,
            "sibling .lui components were not indexed before binding."
        );
        var aliasSibling = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using StringAlias = System.String; using Lucent.Core; using static Lucent.Core.Components; public component A(StringAlias value) { <Text content={value} /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using SC = Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <SC::Components.A value=\"ok\" /> }",
                "B.lui"
            )
        );
        Assert(
            aliasSibling.Diagnostics.Length == 0
                && aliasSibling.Results.Single().GeneratedSources.Length == 2,
            "sibling declarations did not preserve aliases or bind alias-qualified components."
        );
        var orderedAliases = RunWithSource(
            "namespace Sample { public class Local {} }",
            new TextFile(
                "C:/consumer/Before.lui",
                "using BeforeAlias = Sample.Local; namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Before(BeforeAlias value) { <Row /> }",
                "Before.lui"
            ),
            new TextFile(
                "C:/consumer/After.lui",
                "namespace Sample; using AfterAlias = Local; using Lucent.Core; using static Lucent.Core.Components; internal component After(AfterAlias value) { <Row /> }",
                "After.lui"
            )
        );
        Assert(
            orderedAliases.Diagnostics.Length == 0
                && orderedAliases.Results.Single().GeneratedSources.Length == 2
                && Source(orderedAliases, "Before")
                    .Contains(
                        "using BeforeAlias = Sample.Local;\nnamespace Sample;",
                        StringComparison.Ordinal
                    )
                && Source(orderedAliases, "After")
                    .Contains(
                        "namespace Sample;\nusing AfterAlias = Local;",
                        StringComparison.Ordinal
                    ),
            "generated source or sibling declaration index moved aliases across a file-scoped namespace."
        );
        var duplicateComponent = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }",
                "B.lui"
            )
        );
        Assert(
            duplicateComponent.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2
                && duplicateComponent.Results.Single().GeneratedSources.Length == 0,
            "duplicate component identities emitted output."
        );
        var overloadDuplicate = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same(int value) { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same(string value) { <Row /> }",
                "B.lui"
            )
        );
        Assert(
            overloadDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2
                && overloadDuplicate.Results.Single().GeneratedSources.Length == 0,
            "component overload signatures affected duplicate identity."
        );
        var escapedDuplicate = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component @Same() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }",
                "B.lui"
            )
        );
        Assert(
            escapedDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2
                && escapedDuplicate.Results.Single().GeneratedSources.Length == 0,
            "canonical symbol identity did not detect escaped duplicate components."
        );
        var namespaceDuplicate = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace @Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }",
                "B.lui"
            )
        );
        Assert(
            namespaceDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2
                && namespaceDuplicate.Results.Single().GeneratedSources.Length == 0,
            "canonical containing namespace did not determine duplicate identity."
        );
        var errorSignature = Run(
            new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"),
            new TextFile(
                "C:/consumer/Bad.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad(MissingType value) { <Row /> }",
                "Bad.lui"
            )
        );
        Assert(
            errorSignature.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4005") == 1
                && errorSignature.Results.Single().GeneratedSources.Length == 1,
            "unresolved sibling signature was indexed or did not fail closed."
        );
        var siblingOne = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <Row /> }",
                "B.lui"
            )
        );
        var siblingTwo = Run(
            new TextFile(
                "C:/consumer/A.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A() { <Row /> }",
                "A.lui"
            ),
            new TextFile(
                "C:/consumer/B.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B(int value) { <Row /> }",
                "B.lui"
            )
        );
        Assert(
            Source(siblingOne, "A") != Source(siblingTwo, "A"),
            "sibling component-index changes did not invalidate publication identity."
        );
        var globalOne = RunWithSource(
            "global using System;",
            new TextFile("C:/consumer/Global.lui", Valid, "Global.lui")
        );
        var globalTwo = RunWithSource(
            "global using System.Text;",
            new TextFile("C:/consumer/Global.lui", Valid, "Global.lui")
        );
        Assert(
            Source(globalOne, "Widget") != Source(globalTwo, "Widget"),
            "actual global-using snapshot changes did not invalidate publication identity."
        );
    }

    [TestMethod]
    public void RetainedStructuralLocalsStayCurrentWithoutRemounting()
    {
        const string runtimeApi = """
namespace CurrentRuntime;
using System;
using Lucent.Core;
public sealed record Row(int Id, string Title);
public static class Probes
{
    public static int LoopFactories;
    public static string LoopSnapshot = "";
    public static Func<string> LoopLive = null!;
    public static int PatternFactories;
    public static string PatternSnapshot = "";
    public static Func<string> PatternLive = null!;

    [LucentComponent]
    public static ComponentRecipe LoopProbe(string snapshot, Func<string> live) =>
        ComponentRecipe.Create("loop-probe", (_, _) =>
        {
            LoopFactories++;
            LoopSnapshot = snapshot;
            LoopLive = live;
        });

    [LucentComponent]
    public static ComponentRecipe PatternProbe(string snapshot, Func<string> live) =>
        ComponentRecipe.Create("pattern-probe", (_, _) =>
        {
            PatternFactories++;
            PatternSnapshot = snapshot;
            PatternLive = live;
        });
}
""";
        const string loopSource = """
namespace CurrentRuntime;
using Lucent.Core;
using static Lucent.Core.Components;
using static CurrentRuntime.Probes;
internal component Loop(Signal<Row[]> rows) {
    <Row>
        foreach (var item in rows.Value) keyed by item.Id {
            <LoopProbe snapshot={item.Title} live={() => item.Title} />
        }
    </Row>
}
""";
        const string patternSource = """
namespace CurrentRuntime;
using Lucent.Core;
using static Lucent.Core.Components;
using static CurrentRuntime.Probes;
internal component Pattern(Signal<object?> candidate) {
    <Row>
        if (candidate.Value is Row { } item) {
            <PatternProbe snapshot={item.Title} live={() => item.Title} />
        }
    </Row>
}
""";
        var generatedResult = RunWithSource(
            runtimeApi,
            new TextFile("C:/consumer/Loop.lui", loopSource, "Loop.lui"),
            new TextFile("C:/consumer/Pattern.lui", patternSource, "Pattern.lui")
        );
        Assert(
            generatedResult.Diagnostics.Length == 0
                && generatedResult.Results.Single().GeneratedSources.Length == 2,
            "current-reader documents did not generate: "
                + string.Join(
                    " | ",
                    generatedResult.Diagnostics.Select(diagnostic =>
                        diagnostic.GetMessage(CultureInfo.InvariantCulture)
                    )
                )
        );
        const string harness = """
#nullable enable
namespace CurrentRuntime;
using System.Linq;
using Lucent.Core;
public static class Harness
{
    public static string Loop()
    {
        var graph = new ReactiveGraph();
        using var composition = new Composition(graph, "loop-current");
        using var theme = new ThemeContext(composition.Root.Scope, new Theme("loop-current"));
        var rows = composition.Root.Scope.Signal(new[] { new Row(1, "before") }, "rows");
        var root = composition.Mount(composition.Root, theme, Components.Loop(rows));
        graph.Drain();
        var retained = root.Children.Single().Children.Single().Id;
        rows.Value = new[] { new Row(1, "after") };
        graph.Drain();
        var current = root.Children.Single().Children.Single().Id;
        return $"{Probes.LoopSnapshot}|{Probes.LoopLive()}|{Probes.LoopFactories}|{retained == current}";
    }

    public static string Pattern()
    {
        var graph = new ReactiveGraph();
        using var composition = new Composition(graph, "pattern-current");
        using var theme = new ThemeContext(composition.Root.Scope, new Theme("pattern-current"));
        var candidate = composition.Root.Scope.Signal<object?>(new Row(1, "before"), "candidate");
        var root = composition.Mount(composition.Root, theme, Components.Pattern(candidate));
        graph.Drain();
        var retained = root.Children.Single().Children.Single().Id;
        candidate.Value = new Row(1, "after");
        graph.Drain();
        var current = root.Children.Single().Children.Single().Id;
        return $"{Probes.PatternSnapshot}|{Probes.PatternLive()}|{Probes.PatternFactories}|{retained == current}";
    }
}
""";
        var trees = new List<SyntaxTree>
        {
            CSharpSyntaxTree.ParseText(runtimeApi, new CSharpParseOptions(LanguageVersion.Preview)),
            CSharpSyntaxTree.ParseText(harness, new CSharpParseOptions(LanguageVersion.Preview)),
        };
        trees.AddRange(
            generatedResult
                .Results.Single()
                .GeneratedSources.Select(source =>
                    CSharpSyntaxTree.ParseText(
                        source.SourceText.ToString(),
                        new CSharpParseOptions(LanguageVersion.Preview),
                        source.HintName
                    )
                )
        );
        var compilation = CSharpCompilation.Create(
            "generated-current-readers",
            trees,
            References(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );
        using var stream = new MemoryStream();
        var emit = compilation.Emit(stream);
        Assert(
            emit.Success
                && !emit.Diagnostics.Any(diagnostic =>
                    diagnostic.Severity == DiagnosticSeverity.Warning
                ),
            "generated current-reader runtime was not warning-clean: "
                + string.Join(
                    " | ",
                    emit.Diagnostics.Select(diagnostic =>
                        diagnostic.GetMessage(CultureInfo.InvariantCulture)
                    )
                )
        );
        var assembly = Assembly.Load(stream.ToArray());
        var type = assembly.GetType("CurrentRuntime.Harness")!;
        Assert(
            (string)type.GetMethod("Loop")!.Invoke(null, null)! == "before|after|1|True",
            "same-key foreach replacement was stale or remounted."
        );
        Assert(
            (string)type.GetMethod("Pattern")!.Invoke(null, null)! == "before|after|1|True",
            "same-branch pattern replacement was stale or remounted."
        );
    }

    [TestMethod]
    public void GeneratedCodeExecutes()
    {
        const string InlineProbe =
            "namespace Sample; public static class Probe { public static int Reads; public static float Read(global::Lucent.Core.Signal<float> signal) { Reads++; return signal.Value; } }";
        const string InlineConsumer =
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; using static Lucent.Core.VisualProperties; public component Inline(Style? baseStyle, Signal<float> signal) { <Text style={baseStyle with { when Hover { Opacity: Sample.Probe.Read(signal); } }}>live</Text> }";
        var inlineGeneratedResult = RunWithSource(
            InlineProbe,
            new TextFile("C:/consumer/Inline.lui", InlineConsumer, "Inline.lui")
        );
        Assert(
            inlineGeneratedResult.Diagnostics.Length == 0
                && inlineGeneratedResult.Results.Single().GeneratedSources.Length == 1,
            "inline generated consumer did not compile through the generator."
        );
        var inlineGenerated = inlineGeneratedResult
            .Results.Single()
            .GeneratedSources.Single()
            .SourceText.ToString();
        var inlineCompilation = CSharpCompilation.Create(
            "generated-inline",
            [
                CSharpSyntaxTree.ParseText(
                    InlineProbe,
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
                CSharpSyntaxTree.ParseText(
                    inlineGenerated,
                    new CSharpParseOptions(LanguageVersion.Preview),
                    "Inline.g.cs"
                ),
            ],
            References(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );
        using var inlineAssemblyStream = new MemoryStream();
        var inlineEmit = inlineCompilation.Emit(inlineAssemblyStream);
        Assert(
            inlineEmit.Success
                && !inlineEmit.Diagnostics.Any(diagnostic =>
                    diagnostic.Severity == DiagnosticSeverity.Warning
                ),
            "generated inline consumer was not warning-clean: "
                + string.Join(
                    " | ",
                    inlineEmit.Diagnostics.Select(diagnostic =>
                        diagnostic.GetMessage(CultureInfo.InvariantCulture)
                    )
                )
        );
        var inlineAssembly = Assembly.Load(inlineAssemblyStream.ToArray());
        var inlineMethod = inlineAssembly
            .GetType("Sample.Components")!
            .GetMethod("Inline", BindingFlags.Public | BindingFlags.Static)!;
        var probeReads = inlineAssembly
            .GetType("Sample.Probe")!
            .GetField("Reads", BindingFlags.Public | BindingFlags.Static)!;
        var inlineGraph = new ReactiveGraph();
        using var inlineComposition = new Composition(inlineGraph, "generated-inline");
        using var inlineTheme = new ThemeContext(
            inlineComposition.Root.Scope,
            new Theme("generated-inline")
        );
        var inlineSignal = inlineComposition.Root.Scope.Signal(.25f, "generated-inline-source");
        var inlineRecipe = (ComponentRecipe)inlineMethod.Invoke(null, [Style.Empty, inlineSignal])!;
        var inlineRoot = inlineComposition.Mount(inlineComposition.Root, inlineTheme, inlineRecipe);
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 0
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1,
            "inactive generated variant evaluated its binding."
        );
        inlineSignal.Value = .5f;
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 0
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1,
            "inactive generated variant retained its source dependency."
        );
        inlineRoot.SetVariants(VariantState.Hover);
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 1
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == .5f,
            "activating generated variant did not read the current source exactly once."
        );
        inlineSignal.Value = .75f;
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 2
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == .75f,
            "active generated variant did not rerun its binding."
        );
        inlineRoot.SetVariants(VariantState.None);
        inlineGraph.Drain();
        inlineSignal.Value = .25f;
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 2
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1,
            "deactivated generated variant retained its reactive dependency."
        );
        inlineRoot.SetVariants(VariantState.Hover);
        inlineGraph.Drain();
        Assert(
            (int)probeReads.GetValue(null)! == 3
                && inlineRoot.Resolve(VisualProperties.Opacity).Value == .25f,
            "reactivating generated variant did not reacquire the current source."
        );
        var nullableInlineRecipe = (ComponentRecipe)
            inlineMethod.Invoke(null, [null, inlineSignal])!;
        var nullableInlineRoot = inlineComposition.Mount(
            inlineComposition.Root,
            inlineTheme,
            nullableInlineRecipe
        );
        inlineGraph.Drain();
        Assert(
            nullableInlineRoot.Resolve(VisualProperties.Opacity).Value == 1,
            "nullable inline base style did not mount as Style.Empty."
        );
        const string MultipleDefaultApi =
            "namespace Sample; using Lucent.Core; public static class Defaults { [LucentComponent] public static ComponentRecipe Multiple([DefaultContent] string first, [DefaultContent] string second) => null!; }";
        var multipleDefaultDocuments = RunWithSource(
            MultipleDefaultApi,
            new TextFile(
                "C:/consumer/Good.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Good() { <Row /> }",
                "Good.lui"
            ),
            new TextFile(
                "C:/consumer/Bad.lui",
                "namespace Sample; using Lucent.Core; using static Sample.Defaults; internal component Bad() { <Multiple>value</Multiple> }",
                "Bad.lui"
            )
        );
        Assert(
            multipleDefaultDocuments.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI2005")
                == 1
                && multipleDefaultDocuments.Results.Single().GeneratedSources.Length == 1
                && multipleDefaultDocuments
                    .Results.Single()
                    .GeneratedSources.Single()
                    .SourceText.ToString()
                    .Contains("Good", StringComparison.Ordinal),
            "multiple [DefaultContent] annotations did not isolate the invalid document."
        );
    }

    [TestMethod]
    public void InvalidSiblingDoesNotPoisonValidDocuments()
    {
        var parameterSiblingIsolation = Run(
            new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"),
            new TextFile(
                "C:/consumer/Bad.lui",
                "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad([Obsolete] ref string value, params int[] values) { <Row /> }",
                "Bad.lui"
            )
        );
        Assert(
            parameterSiblingIsolation.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI3004")
                == 2
                && parameterSiblingIsolation.Results.Single().GeneratedSources.Length == 1
                && parameterSiblingIsolation
                    .Results.Single()
                    .GeneratedSources.Single()
                    .SourceText.ToString()
                    .Contains("Widget", StringComparison.Ordinal),
            "unsupported parameters were indexed or suppressed a valid sibling."
        );
    }

    [TestMethod]
    public void IncrementalUpdatesInvalidateOnlyAffectedOutputs()
    {
        var trackedA = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"one\") { <Row /> }",
            "A.lui"
        );
        var trackedB = new TextFile(
            "C:/consumer/B.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <A /> }",
            "B.lui"
        );
        var trackedCompilation = CSharpCompilation.Create(
            "tracked",
            [
                CSharpSyntaxTree.ParseText(
                    "internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
            ],
            References()
        );
        GeneratorDriver tracked = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            [trackedA, trackedB],
            optionsProvider: new OptionsProvider([trackedA, trackedB], null),
            driverOptions: new GeneratorDriverOptions(
                IncrementalGeneratorOutputKind.None,
                true,
                null
            )
        );
        tracked = tracked.RunGenerators(trackedCompilation).RunGenerators(trackedCompilation);
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiDocumentOutput")
                .All(reason => reason == IncrementalStepRunReason.Cached),
            "unchanged inputs recomputed document output."
        );
        var body = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"one\") { <Row name=\"changed\" /> }",
            "A.lui"
        );
        tracked = tracked.ReplaceAdditionalText(trackedA, body).RunGenerators(trackedCompilation);
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiDocumentOutput")
                .Count(reason => reason != IncrementalStepRunReason.Cached) == 1,
            "body edit invalidated a sibling."
        );
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiPublication")
                .Count(reason => reason != IncrementalStepRunReason.Cached) == 1,
            "body edit republished a sibling."
        );
        var beforeDefault = Source(tracked.GetRunResult(), "B");
        var defaultEdit = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"two\") { <Row /> }",
            "A.lui"
        );
        tracked = tracked
            .ReplaceAdditionalText(body, defaultEdit)
            .RunGenerators(trackedCompilation);
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiDocumentOutput")
                .Count(reason => reason != IncrementalStepRunReason.Cached) == 2
                && Source(tracked.GetRunResult(), "B") != beforeDefault,
            "parameter default edit did not invalidate sibling output."
        );
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiPublication")
                .Count(reason => reason != IncrementalStepRunReason.Cached) == 2,
            "index edit did not republish the full component set."
        );
        var named = new TextFile(
            "C:/consumer/B.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <A value=\"ok\" /> }",
            "B.lui"
        );
        tracked = tracked.ReplaceAdditionalText(trackedB, named).RunGenerators(trackedCompilation);
        var nameEdit = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string renamed = \"two\") { <Row /> }",
            "A.lui"
        );
        tracked = tracked
            .ReplaceAdditionalText(defaultEdit, nameEdit)
            .RunGenerators(trackedCompilation);
        Assert(
            StepReasons(tracked.GetRunResult(), "LuiDocumentOutput")
                .Count(reason => reason != IncrementalStepRunReason.Cached) == 2
                && tracked.GetRunResult().Results.Single().GeneratedSources.Length == 1
                && tracked
                    .GetRunResult()
                    .Results.Single()
                    .GeneratedSources.All(source =>
                        !source.SourceText.ToString().Contains("value:", StringComparison.Ordinal)
                    ),
            "parameter name edit retained stale named output."
        );
        var moved = new TextFile(
            "C:/consumer/Bad.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad(MissingType value) { <Row /> }",
            "Bad.lui",
            "v1"
        );
        GeneratorDriver diagnosticDriver = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            [moved],
            optionsProvider: new OptionsProvider([moved], null),
            driverOptions: new GeneratorDriverOptions(
                IncrementalGeneratorOutputKind.None,
                true,
                null
            )
        );
        diagnosticDriver = diagnosticDriver.RunGenerators(trackedCompilation);
        var first = diagnosticDriver
            .GetRunResult()
            .Diagnostics.Single(diagnostic => diagnostic.Id == "LUI4005");
        var movedVersion = new TextFile(
            "C:/consumer/Bad.lui",
            "\n\nnamespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad(MissingType value) { <Row /> }",
            "Bad.lui",
            "v2"
        );
        diagnosticDriver = diagnosticDriver
            .ReplaceAdditionalText(moved, movedVersion)
            .RunGenerators(trackedCompilation);
        var second = diagnosticDriver
            .GetRunResult()
            .Diagnostics.Single(diagnostic => diagnostic.Id == "LUI4005");
        Assert(
            first.GetMessage(CultureInfo.InvariantCulture)
                == second.GetMessage(CultureInfo.InvariantCulture)
                && second.Location.SourceSpan.Start > first.Location.SourceSpan.Start,
            "moved index diagnostic reused its stale location."
        );
        var staleCompilation = CSharpCompilation.Create(
            "stale",
            [
                CSharpSyntaxTree.ParseText(
                    "internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
            ],
            References()
        );
        var stale = LuiCompiler.Compile(
            LuiParser.Parse(Valid),
            staleCompilation,
            new LuiFreshnessIdentity(
                "stale",
                "stale",
                new LuiDocumentIdentity("Stale.lui"),
                "v1",
                "preview"
            )
        );
        var current = LuiCompiler.Snapshot(
            new LuiFreshnessIdentity(
                "stale",
                "stale",
                new LuiDocumentIdentity("Stale.lui"),
                "v2",
                "preview"
            ),
            staleCompilation
        );
        Assert(
            stale.Success && !LuiGenerator.ShouldPublish(stale, current),
            "stale result published without cancellation."
        );
        var restoredA = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"two\") { <Row /> }",
            "A.lui"
        );
        tracked = tracked
            .ReplaceAdditionalText(nameEdit, restoredA)
            .RunGenerators(trackedCompilation);
        Assert(GeneratedCount(tracked) == 2, "restoring a valid signature left stale output.");
        var added = new TextFile(
            "C:/consumer/C.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component C() { <Row /> }",
            "C.lui"
        );
        tracked = tracked.AddAdditionalTexts([added]).RunGenerators(trackedCompilation);
        Assert(
            GeneratedCount(tracked) == 3 && ModifiedCount(tracked) == 3,
            "adding a document did not update the whole component set."
        );
        tracked = tracked.RemoveAdditionalTexts([added]).RunGenerators(trackedCompilation);
        Assert(
            GeneratedCount(tracked) == 2
                && StepReasons(tracked.GetRunResult(), "LuiDocumentOutput").Any(),
            "deleting a document left stale output."
        );
        var renamed = new TextFile(
            "C:/consumer/Renamed.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <A value=\"ok\" /> }",
            "Renamed.lui"
        );
        tracked = tracked
            .RemoveAdditionalTexts([named])
            .AddAdditionalTexts([renamed])
            .RunGenerators(trackedCompilation);
        Assert(
            GeneratedCount(tracked) == 2
                && Generated(tracked)
                    .Any(source => source.Contains("Renamed.lui", StringComparison.Ordinal)),
            "rename left stale document identity."
        );
        var duplicateDocument = new TextFile(
            "C:/consumer/Duplicate.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"two\") { <Row /> }",
            "Duplicate.lui"
        );
        tracked = tracked.AddAdditionalTexts([duplicateDocument]).RunGenerators(trackedCompilation);
        Assert(
            tracked.GetRunResult().Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2
                && GeneratedCount(tracked) == 0,
            "duplicate declaration retained generated output."
        );
        tracked = tracked
            .RemoveAdditionalTexts([duplicateDocument])
            .RunGenerators(trackedCompilation);
        var unreadableA = new TextFile("C:/consumer/A.lui", null, "A.lui");
        tracked = tracked
            .ReplaceAdditionalText(restoredA, unreadableA)
            .RunGenerators(trackedCompilation);
        Assert(
            tracked.GetRunResult().Diagnostics.Any(diagnostic => diagnostic.Id == "LUI4001")
                && GeneratedCount(tracked) == 0,
            "failed input retained generated output."
        );
        tracked = tracked
            .ReplaceAdditionalText(unreadableA, restoredA)
            .RunGenerators(trackedCompilation);
        var invalidA = new TextFile("C:/consumer/A.lui", "", "A.lui");
        tracked = tracked
            .ReplaceAdditionalText(restoredA, invalidA)
            .RunGenerators(trackedCompilation);
        Assert(
            tracked.GetRunResult().Diagnostics.Any(diagnostic => diagnostic.Id == "LUI1003")
                && GeneratedCount(tracked) == 0,
            "invalid input retained generated output."
        );
        tracked = tracked
            .ReplaceAdditionalText(invalidA, restoredA)
            .RunGenerators(trackedCompilation);
        var beforeOptions = Source(tracked.GetRunResult(), "B");
        tracked = tracked
            .WithUpdatedAnalyzerConfigOptions(
                new OptionsProvider(
                    [restoredA, renamed],
                    new Dictionary<string, string>
                    {
                        ["build_property.LucentLuiCompilerOptions"] = "nullable:enable",
                        ["build_property.LucentLuiDefines"] = "ONE",
                    }
                )
            )
            .RunGenerators(trackedCompilation);
        Assert(
            ModifiedCount(tracked) == 2 && Source(tracked.GetRunResult(), "B") != beforeOptions,
            "project options did not invalidate retained output."
        );
        tracked = tracked
            .WithUpdatedAnalyzerConfigOptions(
                new OptionsProvider(
                    [restoredA, renamed],
                    new Dictionary<string, string>
                    {
                        ["build_property.LucentLuiCompilerOptions"] = "nullable:enable",
                        ["build_property.LucentLuiDefines"] = "TWO",
                    }
                )
            )
            .RunGenerators(trackedCompilation);
        Assert(ModifiedCount(tracked) == 2, "project defines did not invalidate retained output.");
        var oldTree = trackedCompilation.SyntaxTrees.Single();
        trackedCompilation = trackedCompilation
            .RemoveSyntaxTrees(oldTree)
            .AddSyntaxTrees(
                CSharpSyntaxTree.ParseText(
                    "global using System; internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                )
            );
        tracked = tracked.RunGenerators(trackedCompilation);
        Assert(
            ModifiedCount(tracked) == 2,
            "global using change did not invalidate retained output."
        );
        using var referenceImage = new MemoryStream();
        var referenceCompilation = CSharpCompilation.Create(
            "tracked-reference",
            [
                CSharpSyntaxTree.ParseText(
                    "public sealed class TrackedReference {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
            ],
            References(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
        );
        Assert(
            referenceCompilation.Emit(referenceImage).Success,
            "reference fixture did not compile."
        );
        tracked = tracked.RunGenerators(
            trackedCompilation.AddReferences(
                MetadataReference.CreateFromImage(referenceImage.ToArray())
            )
        );
        Assert(
            ModifiedCount(tracked) == 2,
            "reference semantic change did not invalidate retained output."
        );
        var cancelledA = new TextFile(
            "C:/consumer/A.lui",
            "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A(string value = \"cancelled\") { <Row /> }",
            "A.lui"
        );
        tracked = tracked.ReplaceAdditionalText(restoredA, cancelledA);
        try
        {
            _ = tracked.RunGenerators(trackedCompilation, new CancellationToken(true));
            throw new InvalidOperationException("cancelled input completed generation.");
        }
        catch (OperationCanceledException) { }
        tracked = tracked
            .ReplaceAdditionalText(cancelledA, restoredA)
            .RunGenerators(trackedCompilation);
        var releaseDriver = RemovedTextDriver(trackedCompilation, out var released);
        for (var attempt = 0; released.IsAlive && attempt < 3; attempt++)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
        }
        GC.KeepAlive(releaseDriver);
        Assert(!released.IsAlive, "removed document remained retained by a converged live driver.");
    }

    static GeneratorDriverRunResult Run(params AdditionalText[] texts)
    {
        var compilation = CSharpCompilation.Create(
            "probe",
            [
                CSharpSyntaxTree.ParseText(
                    "internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
            ],
            References()
        );
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            texts,
            optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), null)
        );
        driver = driver.RunGenerators(compilation);
        return driver.GetRunResult();
    }

    static GeneratorDriverRunResult RunWithGlobal(
        IReadOnlyDictionary<string, string> global,
        params AdditionalText[] texts
    )
    {
        var compilation = CSharpCompilation.Create(
            "probe",
            [
                CSharpSyntaxTree.ParseText(
                    "internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
            ],
            References()
        );
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            texts,
            optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), global)
        );
        return driver.RunGenerators(compilation).GetRunResult();
    }

    static GeneratorDriverRunResult RunWithSource(string source, params AdditionalText[] texts)
    {
        var compilation = CSharpCompilation.Create(
            "probe",
            [
                CSharpSyntaxTree.ParseText(
                    "internal class C {}",
                    new CSharpParseOptions(LanguageVersion.Preview)
                ),
                CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview)),
            ],
            References()
        );
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            texts,
            optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), null)
        );
        return driver.RunGenerators(compilation).GetRunResult();
    }

    static string Source(GeneratorDriverRunResult result, string component) =>
        result
            .Results.Single()
            .GeneratedSources.Single(source =>
                source
                    .SourceText.ToString()
                    .Contains(" " + component + "(", StringComparison.Ordinal)
            )
            .SourceText.ToString();

    static IEnumerable<IncrementalStepRunReason> StepReasons(
        GeneratorDriverRunResult result,
        string name
    ) =>
        result
            .Results.Single()
            .TrackedSteps[name]
            .SelectMany(step => step.Outputs)
            .Select(output => output.Reason);

    static int ModifiedCount(GeneratorDriver driver) =>
        StepReasons(driver.GetRunResult(), "LuiDocumentOutput")
            .Count(reason => reason != IncrementalStepRunReason.Cached);

    static int GeneratedCount(GeneratorDriver driver) =>
        driver.GetRunResult().Results.Single().GeneratedSources.Length;

    static string[] Generated(GeneratorDriver driver) =>
        driver
            .GetRunResult()
            .Results.Single()
            .GeneratedSources.Select(source => source.SourceText.ToString())
            .ToArray();

    static GeneratorDriver RemovedTextDriver(Compilation compilation, out WeakReference released)
    {
        var removed = new TextFile("C:/consumer/Removed.lui", Valid, "Removed.lui");
        released = new WeakReference(removed);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new LuiGenerator().AsSourceGenerator()],
            [removed],
            optionsProvider: new OptionsProvider([removed], null),
            driverOptions: new GeneratorDriverOptions(
                IncrementalGeneratorOutputKind.None,
                true,
                null
            )
        );
        driver = driver
            .RunGenerators(compilation)
            .RemoveAdditionalTexts([removed])
            .WithUpdatedAnalyzerConfigOptions(new OptionsProvider([], null))
            .RunGenerators(compilation);
        return driver.RunGenerators(compilation);
    }

    static void Assert(bool condition, string message)
    {
        if (!condition)
            throw new InvalidOperationException(message);
    }

    static MetadataReference[] References() =>
        ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator)
            .Select(path => MetadataReference.CreateFromFile(path))
            .Append(
                MetadataReference.CreateFromFile(
                    Path.Combine(AppContext.BaseDirectory, "Lucent.Core.dll")
                )
            )
            .ToArray();

    sealed class TextFile(
        string path,
        string? text,
        string? logicalPath = null,
        string? documentVersion = null
    ) : AdditionalText
    {
        public override string Path => path;
        public string? LogicalPath => logicalPath;
        public string? DocumentVersion => documentVersion;

        public override SourceText? GetText(CancellationToken cancellationToken = default) =>
            text is null ? null : SourceText.From(text);
    }

    sealed class OptionsProvider(
        IEnumerable<TextFile> texts,
        IReadOnlyDictionary<string, string>? global
    ) : AnalyzerConfigOptionsProvider
    {
        private readonly Dictionary<AdditionalText, AnalyzerConfigOptions> options =
            texts.ToDictionary(
                text => (AdditionalText)text,
                text =>
                    (AnalyzerConfigOptions)new Options(text.LogicalPath, text.DocumentVersion, null)
            );
        public override AnalyzerConfigOptions GlobalOptions => new Options(null, null, global);

        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) =>
            new Options(null, null, null);

        public override AnalyzerConfigOptions GetOptions(AdditionalText text) =>
            options.TryGetValue(text, out var value) ? value : new Options(null, null, null);
    }

    sealed class Options(
        string? logicalPath,
        string? documentVersion,
        IReadOnlyDictionary<string, string>? values
    ) : AnalyzerConfigOptions
    {
        public override bool TryGetValue(string key, out string value)
        {
            if (key == "build_metadata.AdditionalFiles.LucentLuiLogicalPath" && logicalPath != null)
            {
                value = logicalPath;
                return true;
            }
            if (
                key == "build_metadata.AdditionalFiles.LucentLuiDocumentVersion"
                && documentVersion != null
            )
            {
                value = documentVersion;
                return true;
            }
            if (values is not null && values.TryGetValue(key, out var configured))
            {
                value = configured;
                return true;
            }
            value = "";
            return false;
        }
    }
}
