using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Lucent.Lui.Compiler;
using Lucent.Lui.Generator;

Assert(new LuiDocumentIdentity("views\\Main.lui").LogicalPath == "views/Main.lui", "logical paths were not normalized.");
foreach (var path in new[] { "/views/Main.lui", "\\views\\Main.lui", "C:/views/Main.lui", "C:\\views\\Main.lui", "C:Main.lui", "views/./Main.lui", "views/../Main.lui", ".", ".." })
{
    try { _ = new LuiDocumentIdentity(path); throw new InvalidOperationException("rooted or traversing path was accepted: " + path); }
    catch (ArgumentException) { }
}
Assert(LuiProbeEmitter.HintName(new LuiDocumentIdentity("views/Main.lui")) == LuiProbeEmitter.HintName(new LuiDocumentIdentity("views/Main.lui")), "hint identity was not deterministic.");
Assert(!new LuiProjectIdentity("C:/one", "preview").Equals(new LuiProjectIdentity("C:/two", "preview")), "absolute project roots must remain distinct project identities.");
Assert(new LuiDocumentIdentity("views/Main.lui").StableId == new LuiDocumentIdentity("views/Main.lui").StableId, "document identity changed across absolute roots.");
var rootA = Run(new TextFile("C:/one/views/Main.lui", "probe", "views/Main.lui"));
var rootB = Run(new TextFile("C:/two/views/Main.lui", "probe", "views/Main.lui"));
Assert(rootA.Results.Single().GeneratedSources.Single().HintName == rootB.Results.Single().GeneratedSources.Single().HintName, "absolute checkout roots changed a project-relative generated identity.");
var valid = Run(new TextFile("C:/consumer/views/Main.lui", "probe", "views/Main.lui"));
Assert(valid.Results.Single().GeneratedSources.Single().SourceText.ToString().Contains("<auto-generated/>") && valid.Results.Single().GeneratedSources.Single().SourceText.ToString().Contains("GeneratedCodeAttribute"), "generator did not emit marked source.");
Assert(valid.Diagnostics.Length == 0, "valid probe reported a diagnostic.");
var empty = Run(new TextFile("C:/consumer/Empty.lui", "", "Empty.lui"));
Assert(empty.Diagnostics.Single().Id == "LUI4001" && empty.Diagnostics.Single().Location.GetLineSpan().Path == "C:/consumer/Empty.lui", "empty input diagnostic lost its exact path.");
var unreadable = Run(new TextFile("C:/consumer/Unreadable.lui", null, "Unreadable.lui"));
Assert(unreadable.Diagnostics.Single().Id == "LUI4001" && unreadable.Results.Single().GeneratedSources.Length == 0 && unreadable.Diagnostics.Single().Location.GetLineSpan().Path == "C:/consumer/Unreadable.lui", "unreadable input did not fail closed with its exact path.");
var invalidPath = Run(new TextFile("C:/consumer/Main.lui", "probe", "../Main.lui"));
Assert(invalidPath.Diagnostics.Single().Id == "LUI4003" && invalidPath.Results.Single().GeneratedSources.Length == 0, "invalid metadata did not fail closed.");
var blankPath = Run(new TextFile("C:/consumer/Main.lui", "probe", " "));
Assert(blankPath.Diagnostics.Single().Id == "LUI4003" && blankPath.Results.Single().GeneratedSources.Length == 0, "blank metadata did not fail closed.");
var duplicate = Run(new TextFile("C:/one/Main.lui", "probe", "same/Main.lui"), new TextFile("C:/two/Main.lui", "probe", "same/Main.lui"));
Assert(duplicate.Diagnostics.Length == 2 && duplicate.Diagnostics.All(diagnostic => diagnostic.Id == "LUI4002") && duplicate.Results.Single().GeneratedSources.Length == 0, "duplicate inputs emitted stale source.");
var changed = Run(new TextFile("C:/consumer/views/Main.lui", "changed", "views/Main.lui"));
Assert(changed.Results.Single().GeneratedSources.Single().SourceText.ToString() != valid.Results.Single().GeneratedSources.Single().SourceText.ToString(), "changed input did not update generated source.");
return 0;

static GeneratorDriverRunResult Run(params AdditionalText[] texts)
{
    var compilation = CSharpCompilation.Create("probe", [CSharpSyntaxTree.ParseText("internal class C {}")], [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
    GeneratorDriver driver = CSharpGeneratorDriver.Create([new LuiGenerator().AsSourceGenerator()], texts, optionsProvider: new OptionsProvider(texts.Cast<TextFile>()));
    driver = driver.RunGenerators(compilation);
    return driver.GetRunResult();
}

static void Assert(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }

sealed class TextFile(string path, string? text, string? logicalPath = null) : AdditionalText
{
    public override string Path => path;
    public string? LogicalPath => logicalPath;
    public override SourceText? GetText(CancellationToken cancellationToken = default) => text is null ? null : SourceText.From(text);
}

sealed class OptionsProvider(IEnumerable<TextFile> texts) : AnalyzerConfigOptionsProvider
{
    private readonly Dictionary<AdditionalText, AnalyzerConfigOptions> options = texts.ToDictionary(text => (AdditionalText)text, text => (AnalyzerConfigOptions)new Options(text.LogicalPath));
    public override AnalyzerConfigOptions GlobalOptions => new Options(null);
    public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => new Options(null);
    public override AnalyzerConfigOptions GetOptions(AdditionalText text) => options.TryGetValue(text, out var value) ? value : new Options(null);
}

sealed class Options(string? logicalPath) : AnalyzerConfigOptions
{
    public override bool TryGetValue(string key, out string value)
    {
        value = logicalPath ?? "";
        return key == "build_metadata.AdditionalFiles.LucentLuiLogicalPath" && logicalPath != null;
    }
}
