using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using System.Reflection;
using Lucent.Lui.Compiler;
using Lucent.Lui.Generator;
using Lucent.Core;

Assert(new LuiDocumentIdentity("views\\Main.lui").LogicalPath == "views/Main.lui", "logical paths were not normalized.");
const string Valid = "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Widget() { <Row /> }";
foreach (var path in new[] { "/views/Main.lui", "\\views\\Main.lui", "C:/views/Main.lui", "C:\\views\\Main.lui", "C:Main.lui", "views/./Main.lui", "views/../Main.lui", ".", ".." })
{
    try { _ = new LuiDocumentIdentity(path); throw new InvalidOperationException("rooted or traversing path was accepted: " + path); }
    catch (ArgumentException) { }
}
Assert(new LuiFreshnessIdentity("1", "sample", new LuiDocumentIdentity("views/Main.lui"), "a", "preview").HintName == new LuiFreshnessIdentity("1", "sample", new LuiDocumentIdentity("views/Main.lui"), "a", "preview").HintName, "hint identity was not deterministic.");
Assert(!new LuiProjectIdentity("C:/one", "preview").Equals(new LuiProjectIdentity("C:/two", "preview")), "absolute project roots must remain distinct project identities.");
Assert(new LuiDocumentIdentity("views/Main.lui").StableId == new LuiDocumentIdentity("views/Main.lui").StableId, "document identity changed across absolute roots.");
var rootA = Run(new TextFile("C:/one/views/Main.lui", Valid, "views/Main.lui"));
var rootB = Run(new TextFile("C:/two/views/Main.lui", Valid, "views/Main.lui"));
Assert(rootA.Results.Single().GeneratedSources.Single().HintName == rootB.Results.Single().GeneratedSources.Single().HintName, "absolute checkout roots changed a project-relative generated identity.");
var valid = Run(new TextFile("C:/consumer/views/Main.lui", Valid, "views/Main.lui"));
var generated = valid.Results.Single().GeneratedSources.Single().SourceText.ToString();
Assert(generated.Contains("<auto-generated/>") && generated.Contains("GeneratedCodeAttribute") && generated.Contains("Row(content: [])") && generated.Contains("#line"), "generator did not emit mapped recipe source.");
Assert(valid.Diagnostics.Length == 0, "valid probe reported a diagnostic.");
var malformed = Run(new TextFile("C:/consumer/Broken.lui", "using static Lucent.Core.Components; internal component Broken() { <Row>", "Broken.lui"));
Assert(malformed.Diagnostics.Any(diagnostic => diagnostic.Id.StartsWith("LUI1", StringComparison.Ordinal)) && malformed.Results.Single().GeneratedSources.Length == 0, "syntax-invalid input emitted a probe.");
var empty = Run(new TextFile("C:/consumer/Empty.lui", "", "Empty.lui"));
Assert(empty.Diagnostics.Any(diagnostic => diagnostic.Id == "LUI1003" && diagnostic.Location.GetLineSpan().Path == "C:/consumer/Empty.lui"), "empty input diagnostic lost its exact path.");
var unreadable = Run(new TextFile("C:/consumer/Unreadable.lui", null, "Unreadable.lui"));
Assert(unreadable.Diagnostics.Single().Id == "LUI4001" && unreadable.Results.Single().GeneratedSources.Length == 0 && unreadable.Diagnostics.Single().Location.GetLineSpan().Path == "C:/consumer/Unreadable.lui", "unreadable input did not fail closed with its exact path.");
var invalidPath = Run(new TextFile("C:/consumer/Main.lui", Valid, "../Main.lui"));
Assert(invalidPath.Diagnostics.Single().Id == "LUI4003" && invalidPath.Results.Single().GeneratedSources.Length == 0, "invalid metadata did not fail closed.");
var blankPath = Run(new TextFile("C:/consumer/Main.lui", Valid, " "));
Assert(blankPath.Diagnostics.Single().Id == "LUI4003" && blankPath.Results.Single().GeneratedSources.Length == 0, "blank metadata did not fail closed.");
var duplicate = Run(new TextFile("C:/one/Main.lui", Valid, "same/Main.lui"), new TextFile("C:/two/Main.lui", Valid, "same/Main.lui"));
Assert(duplicate.Diagnostics.Length == 2 && duplicate.Diagnostics.All(diagnostic => diagnostic.Id == "LUI4002") && duplicate.Results.Single().GeneratedSources.Length == 0, "duplicate inputs emitted stale source.");
var changed = Run(new TextFile("C:/consumer/views/Main.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Widget() { <Row name=\"changed\" /> }", "views/Main.lui"));
Assert(changed.Results.Single().GeneratedSources.Single().SourceText.ToString() != valid.Results.Single().GeneratedSources.Single().SourceText.ToString(), "changed input did not update generated source.");
var invalidComponent = Run(new TextFile("C:/consumer/Bad.lui", "namespace Sample; using Lucent.Core; internal component Bad() { <StringBuilder /> }", "Bad.lui"));
Assert(invalidComponent.Diagnostics.Any(diagnostic => diagnostic.Id == "LUI2001") && invalidComponent.Results.Single().GeneratedSources.Length == 0, "non-component tags emitted output.");
var mixed = Run(new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"), new TextFile("C:/consumer/Bad.lui", "namespace Sample; using Lucent.Core; internal component Bad() { <StringBuilder /> }", "Bad.lui"));
Assert(mixed.Diagnostics.Any(diagnostic => diagnostic.Id == "LUI2001") && mixed.Results.Single().GeneratedSources.Length == 1 && mixed.Results.Single().GeneratedSources.Single().SourceText.ToString().Contains("Widget"), "an invalid component suppressed another document's output.");
var epochOne = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-1", ["build_property.LucentLuiProjectIdentity"] = "evaluated-project", ["build_property.LucentLuiCompilerOptions"] = "nullable:enable", ["build_property.LucentLuiLangVersion"] = "preview" }, new TextFile("C:/consumer/Epoch.lui", Valid, "Epoch.lui"));
var epochTwo = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-2", ["build_property.LucentLuiProjectIdentity"] = "evaluated-project", ["build_property.LucentLuiCompilerOptions"] = "nullable:enable", ["build_property.LucentLuiLangVersion"] = "preview" }, new TextFile("C:/consumer/Epoch.lui", Valid, "Epoch.lui"));
Assert(epochOne.Results.Single().GeneratedSources.Single().SourceText.ToString() != epochTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(), "project epoch change did not prevent stale publication.");
var optionsOne = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiCompilerOptions"] = "nullable:enable", ["build_property.LucentLuiDefines"] = "ONE" }, new TextFile("C:/consumer/Options.lui", Valid, "Options.lui"));
var optionsTwo = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiCompilerOptions"] = "nullable:disable", ["build_property.LucentLuiDefines"] = "ONE" }, new TextFile("C:/consumer/Options.lui", Valid, "Options.lui"));
var definesTwo = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiCompilerOptions"] = "nullable:disable", ["build_property.LucentLuiDefines"] = "TWO" }, new TextFile("C:/consumer/Options.lui", Valid, "Options.lui"));
Assert(optionsOne.Results.Single().GeneratedSources.Single().SourceText.ToString() != optionsTwo.Results.Single().GeneratedSources.Single().SourceText.ToString() && optionsTwo.Results.Single().GeneratedSources.Single().SourceText.ToString() != definesTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(), "compiler options or defines change did not prevent stale publication.");
var versionOne = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-3" }, new TextFile("C:/consumer/Version.lui", Valid, "Version.lui", "v1"));
var versionTwo = RunWithGlobal(new Dictionary<string, string> { ["build_property.LucentLuiProjectEpoch"] = "epoch-3" }, new TextFile("C:/consumer/Version.lui", Valid, "Version.lui", "v2"));
Assert(versionOne.Results.Single().GeneratedSources.Single().SourceText.ToString() != versionTwo.Results.Single().GeneratedSources.Single().SourceText.ToString(), "host document version did not invalidate generated map identity.");
var siblings = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; public component A() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Sample.Components; internal component B() { <A /> }", "B.lui"));
Assert(siblings.Diagnostics.Length == 0 && siblings.Results.Single().GeneratedSources.Length == 2, "sibling .lui components were not indexed before binding.");
var aliasSibling = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using StringAlias = System.String; using Lucent.Core; using static Lucent.Core.Components; public component A(StringAlias value) { <Text content={value} /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using SC = Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <SC::Components.A value=\"ok\" /> }", "B.lui"));
Assert(aliasSibling.Diagnostics.Length == 0 && aliasSibling.Results.Single().GeneratedSources.Length == 2, "sibling declarations did not preserve aliases or bind alias-qualified components.");
var orderedAliases = RunWithSource("namespace Sample { public class Local {} }",
    new TextFile("C:/consumer/Before.lui", "using BeforeAlias = Sample.Local; namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Before(BeforeAlias value) { <Row /> }", "Before.lui"),
    new TextFile("C:/consumer/After.lui", "namespace Sample; using AfterAlias = Local; using Lucent.Core; using static Lucent.Core.Components; internal component After(AfterAlias value) { <Row /> }", "After.lui"));
Assert(orderedAliases.Diagnostics.Length == 0 && orderedAliases.Results.Single().GeneratedSources.Length == 2 &&
    Source(orderedAliases, "Before").IndexOf("using BeforeAlias = Sample.Local;\nnamespace Sample;", StringComparison.Ordinal) >= 0 &&
    Source(orderedAliases, "After").IndexOf("namespace Sample;\nusing AfterAlias = Local;", StringComparison.Ordinal) >= 0,
    "generated source or sibling declaration index moved aliases across a file-scoped namespace.");
var duplicateComponent = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }", "B.lui"));
Assert(duplicateComponent.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2 && duplicateComponent.Results.Single().GeneratedSources.Length == 0, "duplicate component identities emitted output.");
var overloadDuplicate = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same(int value) { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same(string value) { <Row /> }", "B.lui"));
Assert(overloadDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2 && overloadDuplicate.Results.Single().GeneratedSources.Length == 0, "component overload signatures affected duplicate identity.");
var escapedDuplicate = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component @Same() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }", "B.lui"));
Assert(escapedDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2 && escapedDuplicate.Results.Single().GeneratedSources.Length == 0, "canonical symbol identity did not detect escaped duplicate components.");
var namespaceDuplicate = Run(new TextFile("C:/consumer/A.lui", "namespace @Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Same() { <Row /> }", "B.lui"));
Assert(namespaceDuplicate.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4004") == 2 && namespaceDuplicate.Results.Single().GeneratedSources.Length == 0, "canonical containing namespace did not determine duplicate identity.");
var errorSignature = Run(new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"), new TextFile("C:/consumer/Bad.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad(MissingType value) { <Row /> }", "Bad.lui"));
Assert(errorSignature.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI4005") == 1 && errorSignature.Results.Single().GeneratedSources.Length == 1, "unresolved sibling signature was indexed or did not fail closed.");
var siblingOne = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B() { <Row /> }", "B.lui"));
var siblingTwo = Run(new TextFile("C:/consumer/A.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component A() { <Row /> }", "A.lui"), new TextFile("C:/consumer/B.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component B(int value) { <Row /> }", "B.lui"));
Assert(Source(siblingOne, "A") != Source(siblingTwo, "A"), "sibling component-index changes did not invalidate publication identity.");
var globalOne = RunWithSource("global using System;", new TextFile("C:/consumer/Global.lui", Valid, "Global.lui"));
var globalTwo = RunWithSource("global using System.Text;", new TextFile("C:/consumer/Global.lui", Valid, "Global.lui"));
Assert(Source(globalOne, "Widget") != Source(globalTwo, "Widget"), "actual global-using snapshot changes did not invalidate publication identity.");
const string InlineProbe = "namespace Sample; public static class Probe { public static int Reads; public static float Read(global::Lucent.Core.Signal<float> signal) { Reads++; return signal.Value; } }";
const string InlineConsumer = "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; using static Lucent.Core.VisualProperties; public component Inline(Style? baseStyle, Signal<float> signal) { <Text style={baseStyle with { when Hover { Opacity: Sample.Probe.Read(signal); } }}>live</Text> }";
var inlineGeneratedResult = RunWithSource(InlineProbe, new TextFile("C:/consumer/Inline.lui", InlineConsumer, "Inline.lui"));
Assert(inlineGeneratedResult.Diagnostics.Length == 0 && inlineGeneratedResult.Results.Single().GeneratedSources.Length == 1, "inline generated consumer did not compile through the generator.");
var inlineGenerated = inlineGeneratedResult.Results.Single().GeneratedSources.Single().SourceText.ToString();
var inlineCompilation = CSharpCompilation.Create("generated-inline", [CSharpSyntaxTree.ParseText(InlineProbe, new CSharpParseOptions(LanguageVersion.Preview)), CSharpSyntaxTree.ParseText(inlineGenerated, new CSharpParseOptions(LanguageVersion.Preview), "Inline.g.cs")], References(), new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
using var inlineAssemblyStream = new MemoryStream();
var inlineEmit = inlineCompilation.Emit(inlineAssemblyStream);
Assert(inlineEmit.Success && !inlineEmit.Diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Warning), "generated inline consumer was not warning-clean: " + string.Join(" | ", inlineEmit.Diagnostics.Select(diagnostic => diagnostic.GetMessage())));
var inlineAssembly = Assembly.Load(inlineAssemblyStream.ToArray());
var inlineMethod = inlineAssembly.GetType("Sample.Components")!.GetMethod("Inline", BindingFlags.Public | BindingFlags.Static)!;
var probeReads = inlineAssembly.GetType("Sample.Probe")!.GetField("Reads", BindingFlags.Public | BindingFlags.Static)!;
var inlineGraph = new ReactiveGraph();
using var inlineComposition = new Composition(inlineGraph, "generated-inline");
using var inlineTheme = new ThemeContext(inlineComposition.Root.Scope, new Theme("generated-inline"));
var inlineSignal = inlineComposition.Root.Scope.Signal(.25f, "generated-inline-source");
var inlineRecipe = (ComponentRecipe)inlineMethod.Invoke(null, [Style.Empty, inlineSignal])!;
var inlineRoot = inlineComposition.Mount(inlineComposition.Root, inlineTheme, inlineRecipe);
inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 0 && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1, "inactive generated variant evaluated its binding.");
inlineSignal.Value = .5f; inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 0 && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1, "inactive generated variant retained its source dependency.");
inlineRoot.SetVariants(VariantState.Hover); inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 1 && inlineRoot.Resolve(VisualProperties.Opacity).Value == .5f, "activating generated variant did not read the current source exactly once.");
inlineSignal.Value = .75f; inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 2 && inlineRoot.Resolve(VisualProperties.Opacity).Value == .75f, "active generated variant did not rerun its binding.");
inlineRoot.SetVariants(VariantState.None); inlineGraph.Drain(); inlineSignal.Value = .25f; inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 2 && inlineRoot.Resolve(VisualProperties.Opacity).Value == 1, "deactivated generated variant retained its reactive dependency.");
inlineRoot.SetVariants(VariantState.Hover); inlineGraph.Drain();
Assert((int)probeReads.GetValue(null)! == 3 && inlineRoot.Resolve(VisualProperties.Opacity).Value == .25f, "reactivating generated variant did not reacquire the current source.");
var nullableInlineRecipe = (ComponentRecipe)inlineMethod.Invoke(null, [null, inlineSignal])!;
var nullableInlineRoot = inlineComposition.Mount(inlineComposition.Root, inlineTheme, nullableInlineRecipe);
inlineGraph.Drain();
Assert(nullableInlineRoot.Resolve(VisualProperties.Opacity).Value == 1, "nullable inline base style did not mount as Style.Empty.");
const string MultipleDefaultApi = "namespace Sample; using Lucent.Core; public static class Defaults { [LucentComponent] public static ComponentRecipe Multiple([DefaultContent] string first, [DefaultContent] string second) => null!; }";
var multipleDefaultDocuments = RunWithSource(MultipleDefaultApi,
    new TextFile("C:/consumer/Good.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Good() { <Row /> }", "Good.lui"),
    new TextFile("C:/consumer/Bad.lui", "namespace Sample; using Lucent.Core; using static Sample.Defaults; internal component Bad() { <Multiple>value</Multiple> }", "Bad.lui"));
Assert(multipleDefaultDocuments.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI2005") == 1 && multipleDefaultDocuments.Results.Single().GeneratedSources.Length == 1 && multipleDefaultDocuments.Results.Single().GeneratedSources.Single().SourceText.ToString().Contains("Good", StringComparison.Ordinal), "multiple [DefaultContent] annotations did not isolate the invalid document.");
var parameterSiblingIsolation = Run(
    new TextFile("C:/consumer/Good.lui", Valid, "Good.lui"),
    new TextFile("C:/consumer/Bad.lui", "namespace Sample; using Lucent.Core; using static Lucent.Core.Components; internal component Bad([Obsolete] ref string value, params int[] values) { <Row /> }", "Bad.lui"));
Assert(parameterSiblingIsolation.Diagnostics.Count(diagnostic => diagnostic.Id == "LUI3004") == 2 && parameterSiblingIsolation.Results.Single().GeneratedSources.Length == 1 && parameterSiblingIsolation.Results.Single().GeneratedSources.Single().SourceText.ToString().Contains("Widget", StringComparison.Ordinal), "unsupported parameters were indexed or suppressed a valid sibling.");
return 0;

static GeneratorDriverRunResult Run(params AdditionalText[] texts)
{
    var compilation = CSharpCompilation.Create("probe", [CSharpSyntaxTree.ParseText("internal class C {}", new CSharpParseOptions(LanguageVersion.Preview))], References());
    GeneratorDriver driver = CSharpGeneratorDriver.Create([new LuiGenerator().AsSourceGenerator()], texts, optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), null));
    driver = driver.RunGenerators(compilation);
    return driver.GetRunResult();
}
static GeneratorDriverRunResult RunWithGlobal(IReadOnlyDictionary<string, string> global, params AdditionalText[] texts)
{
    var compilation = CSharpCompilation.Create("probe", [CSharpSyntaxTree.ParseText("internal class C {}", new CSharpParseOptions(LanguageVersion.Preview))], References());
    GeneratorDriver driver = CSharpGeneratorDriver.Create([new LuiGenerator().AsSourceGenerator()], texts, optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), global));
    return driver.RunGenerators(compilation).GetRunResult();
}
static GeneratorDriverRunResult RunWithSource(string source, params AdditionalText[] texts)
{
    var compilation = CSharpCompilation.Create("probe", [CSharpSyntaxTree.ParseText("internal class C {}", new CSharpParseOptions(LanguageVersion.Preview)), CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview))], References());
    GeneratorDriver driver = CSharpGeneratorDriver.Create([new LuiGenerator().AsSourceGenerator()], texts, optionsProvider: new OptionsProvider(texts.Cast<TextFile>(), null));
    return driver.RunGenerators(compilation).GetRunResult();
}
static string Source(GeneratorDriverRunResult result, string component) => result.Results.Single().GeneratedSources.Single(source => source.SourceText.ToString().Contains(" " + component + "(", StringComparison.Ordinal)).SourceText.ToString();

static void Assert(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
static MetadataReference[] References() => ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!).Split(Path.PathSeparator).Select(path => MetadataReference.CreateFromFile(path)).Append(MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Lucent.Core.dll"))).ToArray();

sealed class TextFile(string path, string? text, string? logicalPath = null, string? documentVersion = null) : AdditionalText
{
    public override string Path => path;
    public string? LogicalPath => logicalPath;
    public string? DocumentVersion => documentVersion;
    public override SourceText? GetText(CancellationToken cancellationToken = default) => text is null ? null : SourceText.From(text);
}

sealed class OptionsProvider(IEnumerable<TextFile> texts, IReadOnlyDictionary<string, string>? global) : AnalyzerConfigOptionsProvider
{
    private readonly Dictionary<AdditionalText, AnalyzerConfigOptions> options = texts.ToDictionary(text => (AdditionalText)text, text => (AnalyzerConfigOptions)new Options(text.LogicalPath, text.DocumentVersion, null));
    public override AnalyzerConfigOptions GlobalOptions => new Options(null, null, global);
    public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => new Options(null, null, null);
    public override AnalyzerConfigOptions GetOptions(AdditionalText text) => options.TryGetValue(text, out var value) ? value : new Options(null, null, null);
}

sealed class Options(string? logicalPath, string? documentVersion, IReadOnlyDictionary<string, string>? values) : AnalyzerConfigOptions
{
    public override bool TryGetValue(string key, out string value)
    {
        if (key == "build_metadata.AdditionalFiles.LucentLuiLogicalPath" && logicalPath != null) { value = logicalPath; return true; }
        if (key == "build_metadata.AdditionalFiles.LucentLuiDocumentVersion" && documentVersion != null) { value = documentVersion; return true; }
        if (values is not null && values.TryGetValue(key, out var configured)) { value = configured; return true; }
        value = ""; return false;
    }
}
