using System.Security.Cryptography;
using Lucent.Core;
using Lucent.Renderer.Skia;
using SkiaSharp;

namespace Lucent.Renderer.Skia.Tests;

[TestClass]
public sealed class ImagePreparationTests
{
    private static readonly byte[] PngBytes = EncodePng(1, 1);

    // This is the committed tests/Lucent.Lui.Sdk.Fixtures/Assets/Artwork/tiny.png
    // payload. It is retained as a malformed historical-fixture regression; the runtime
    // positive proof uses a dedicated valid PNG generated by Skia below.
    private static readonly byte[] PackagedArtworkTinyPngBytes = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADUlEQVR42mNk+M/wHwAF/gL+3j37WQAAAABJRU5ErkJggg=="
    );

    private static readonly byte[] JpegBytes = Convert.FromBase64String(
        "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAHlAP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8Af//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8Af//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8Af//Z"
    );

    [TestMethod]
    public void PreparesPngAndJpegAsPremultipliedSrgbPixels()
    {
        using var png = Prepare(Source(PngBytes, AssetFormat.Png, .5f, .5f, 2), 1, 1);
        using var jpeg = Prepare(Source(JpegBytes, AssetFormat.Jpeg, .5f, .5f, 2), 1, 1);

        Assert.AreEqual(1, png.Width);
        Assert.AreEqual(1, png.Height);
        Assert.AreEqual(4L, png.ByteCount);
        Assert.AreEqual(4, png.Pixels.Length);
        Assert.IsTrue(png.Pixels.Span[3] > 0, "PNG decode returned no alpha.");
        Assert.AreEqual(1, jpeg.Width);
        Assert.AreEqual(1, jpeg.Height);
        Assert.AreEqual(4, jpeg.Pixels.Length);
        Assert.IsTrue(jpeg.Pixels.Span[3] > 0, "JPEG decode returned no alpha.");
        Assert.IsTrue(
            Enumerable
                .Range(0, png.Pixels.Length / 4)
                .All(index =>
                {
                    var offset = index * 4;
                    return png.Pixels.Span[offset] <= png.Pixels.Span[offset + 3]
                        && png.Pixels.Span[offset + 1] <= png.Pixels.Span[offset + 3]
                        && png.Pixels.Span[offset + 2] <= png.Pixels.Span[offset + 3];
                })
        );
    }

    [TestMethod]
    public void RejectsHistoricalPackagedArtworkTinyPngFixtureAsMalformed()
    {
        AssertLoadFailure(
            Source(PackagedArtworkTinyPngBytes, AssetFormat.Png, .5f, .5f, 2).PackagedAsset!,
            ImageLoadFailureKind.InvalidData
        );
    }

    [TestMethod]
    public void DecodesDedicatedValidRuntimePngFixture()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "pixel.png");
        Assert.IsTrue(File.Exists(path), $"Missing dedicated valid PNG fixture: {path}");
        var valid = File.ReadAllBytes(path);
        using var image = Prepare(Source(valid, AssetFormat.Png, .5f, .5f, 2), 1, 1);

        Assert.AreEqual(1, image.Width);
        Assert.AreEqual(1, image.Height);
        Assert.AreEqual(4L, image.ByteCount);
        Assert.IsTrue(image.Pixels.Span[3] > 0, "Packaged artwork PNG decoded without alpha.");
    }

    [TestMethod]
    public void UsesSupportedDecodeSizeThenPreservesAspectWhenResampling()
    {
        var encoded = EncodePng(128, 64);
        using var image = Prepare(Source(encoded, AssetFormat.Png, 128, 64), 32, 32);

        Assert.AreEqual(32, image.Width);
        Assert.AreEqual(16, image.Height);
        Assert.AreEqual(32L * 16 * 4, image.ByteCount);
    }

    [TestMethod]
    public void DownsamplesFinePatternWithNativeHighQualityFilter()
    {
        var encoded = EncodeCheckerboardPng(64, 64);
        using var image = Prepare(Source(encoded, AssetFormat.Png, 64, 64), 8, 8);

        for (var index = 0; index < image.Pixels.Length; index += 4)
        {
            var pixels = image.Pixels.Span;
            Assert.AreEqual(
                255,
                pixels[index + 3],
                "Checkerboard alpha changed during resampling."
            );
            Assert.IsTrue(
                pixels[index] is > 32 and < 223
                    && pixels[index + 1] is > 32 and < 223
                    && pixels[index + 2] is > 32 and < 223,
                "Fine pattern downsampling retained nearest-neighbor extremes."
            );
        }
    }

    [TestMethod]
    public void AppliesJpegExifOrientationExactlyOnce()
    {
        var encoded = AddJpegExifOrientation(EncodeJpeg(2, 1), orientation: 6);
        using var image = Prepare(Source(encoded, AssetFormat.Jpeg, 1, 2), 2, 2);

        Assert.AreEqual(1, image.Width);
        Assert.AreEqual(2, image.Height);
    }

    [TestMethod]
    public void ResamplingKeepsPremultipliedAlphaInvariant()
    {
        using var image = Prepare(Source(EncodeAlphaPatternPng(), AssetFormat.Png, 2, 2), 1, 1);

        var pixels = image.Pixels.Span;
        Assert.IsTrue(pixels[3] > 0, "Alpha pattern was lost during resampling.");
        Assert.IsTrue(pixels[0] <= pixels[3]);
        Assert.IsTrue(pixels[1] <= pixels[3]);
        Assert.IsTrue(pixels[2] <= pixels[3]);
    }

    [TestMethod]
    public void RejectsHashMetadataAndShortSourceMismatches()
    {
        var badHash = new AssetReference(
            new AssetId("Tests", "bad-hash.png"),
            new string('0', 64),
            PngBytes.Length,
            AssetFormat.Png,
            () => new MemoryStream(PngBytes),
            new(.5f, .5f, 2)
        );
        var badMetadata = Source(PngBytes, AssetFormat.Png, 2, 1);
        var shortSource = new AssetReference(
            new AssetId("Tests", "short.png"),
            Convert.ToHexString(SHA256.HashData(PngBytes)),
            PngBytes.Length,
            AssetFormat.Png,
            () => new MemoryStream(PngBytes[..^1]),
            new(.5f, .5f, 2)
        );

        AssertLoadFailure(badHash, ImageLoadFailureKind.InvalidData);
        AssertLoadFailure(badMetadata.PackagedAsset!, ImageLoadFailureKind.InvalidData);
        AssertLoadFailure(shortSource, ImageLoadFailureKind.InvalidData);
    }

    [TestMethod]
    public void RejectsUnsupportedSvgAndTemporaryBudgetExhaustion()
    {
        var svgBytes =
            "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1\" height=\"1\" />"u8.ToArray();
        var svg = Source(svgBytes, AssetFormat.Svg, 1, 1);
        var source = Source(PngBytes, AssetFormat.Png, .5f, .5f, 2);

        AssertLoadFailure(svg.PackagedAsset!, ImageLoadFailureKind.UnsupportedFormat);
        var limits = new ImageLoadLimits(
            maximumEncodedBytes: 1024,
            maximumSourcePixels: 64,
            maximumOutputBytes: 64,
            maximumTemporaryBytes: 1,
            maximumCachedBytes: 64,
            maximumLeasedBytes: 64
        );
        var request = new ImagePreparationRequest(source, new ImageRendition(1, 1), limits);
        var failure = Assert.ThrowsExactly<ImageLoadException>(() =>
            Complete(new SkiaImagePreparer().PrepareAsync(request, CancellationToken.None))
        );
        Assert.AreEqual(ImageLoadFailureKind.BudgetDeclined, failure.Kind);
    }

    [TestMethod]
    public void PaintsRasterImageAndReusesOwnerNativeCache()
    {
        var graph = new ReactiveGraph();
        using var composition = new Composition(graph, "renderer-image");
        composition.ConfigureImages(new ImageCache(new ImmediatePreparer()));
        var theme = new ThemeContext(composition.Root.Scope, ControlThemes.Light);
        composition.Mount(
            composition.Root,
            theme,
            Components.Image(
                Source(PngBytes, AssetFormat.Png, .5f, .5f, 2),
                "one pixel",
                style: Style
                    .Empty.Set(LayoutProperties.Width, 20f)
                    .Set(LayoutProperties.Height, 20f)
            )
        );

        using var renderer = new SkiaSceneRenderer();
        using var scene = ReadyScene(composition, renderer);
        using var bitmap = new SKBitmap(20, 20, SKColorType.Rgba8888, SKAlphaType.Premul);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(SKColors.Transparent);
        renderer.Render(scene, canvas);
        Assert.IsTrue(
            Enumerable.Range(0, bitmap.Width).Any(x => bitmap.GetPixel(x, 10).Alpha != 0),
            "The retained image scene did not paint pixels."
        );
        Assert.AreEqual(1L, renderer.ImageCreationCount);

        canvas.Clear(SKColors.Transparent);
        renderer.Render(scene, canvas);
        Assert.AreEqual(1L, renderer.ImageCreationCount);
        Assert.AreEqual(1, renderer.LiveImageCount);

        scene.Dispose();
        Assert.ThrowsExactly<ObjectDisposedException>(() => renderer.Render(scene, canvas));
        renderer.Dispose();
        Assert.AreEqual(0, renderer.LiveImageCount);
        Assert.AreEqual(0L, renderer.RetainedImageBytes);
    }

    [TestMethod]
    public void PaintsSourceAndMonochromePixelsWithAlphaAtFractionalDpi()
    {
        using var source = RenderImage(
            [64, 32, 16, 128],
            1,
            1,
            ImageColorMode.Source,
            Color.FromRgb(32, 64, 128),
            scale: 1.5f
        );
        var sourcePixel = source.GetPixel(3, 3);
        // SKBitmap.GetPixel exposes unpremultiplied channel values on this premultiplied
        // surface; the alpha and relative source color must still be preserved.
        AssertPixelNear(sourcePixel, 128, 64, 32, 128, "source mode");

        using var monochrome = RenderImage(
            [64, 32, 16, 128],
            1,
            1,
            ImageColorMode.Monochrome,
            Color.FromRgb(32, 64, 128),
            scale: 1.5f
        );
        var tintedPixel = monochrome.GetPixel(3, 3);
        Assert.IsTrue(
            tintedPixel.Red < tintedPixel.Green && tintedPixel.Green < tintedPixel.Blue,
            $"Monochrome tint did not replace source RGB ordering: {tintedPixel}."
        );
        Assert.AreEqual(
            128,
            tintedPixel.Alpha,
            2,
            $"Monochrome tint changed source alpha: {tintedPixel}."
        );
    }

    [TestMethod]
    public void ClipsPremultipliedImageAtLogicalBoundsAtFractionalDpi()
    {
        using var pixels = RenderImage(
            [64, 32, 16, 128],
            1,
            1,
            ImageColorMode.Source,
            Color.FromRgb(32, 64, 128),
            scale: 1.5f,
            clip: true,
            viewportWidth: 6,
            viewportHeight: 6,
            rootWidth: 4,
            rootHeight: 4,
            imageWidth: 8,
            imageHeight: 8
        );

        var inside = pixels.GetPixel(2, 2);
        Assert.AreEqual(128, inside.Alpha, 2, $"Clipped image lost interior alpha: {inside}.");
        Assert.IsTrue(
            inside.Red <= inside.Alpha
                && inside.Green <= inside.Alpha
                && inside.Blue <= inside.Alpha,
            $"Renderer emitted non-premultiplied interior pixels: {inside}."
        );
        Assert.AreEqual(
            0,
            pixels.GetPixel(7, 7).Alpha,
            "Pixels outside the logical clip bounds were painted at 150% scale."
        );
    }

    [TestMethod]
    public void BoundsNativeImageCacheByEntryCountDuringChurn()
    {
        const int imageCount = 260;
        var graph = new ReactiveGraph();
        using var composition = new Composition(graph, "renderer-image-cache-churn");
        composition.ConfigureImages(new ImageCache(new ImmediatePreparer()));
        var theme = new ThemeContext(composition.Root.Scope, ControlThemes.Light);
        composition.Root.Present(
            theme,
            author: Style
                .Empty.Set(LayoutProperties.Axis, LayoutAxis.Row)
                .Set(LayoutProperties.CrossAlignment, LayoutAlignment.Start)
        );
        for (var index = 0; index < imageCount; index++)
        {
            byte[] bytes = [(byte)(index & 0xff), (byte)(index >> 8)];
            composition.Mount(
                composition.Root,
                theme,
                Components.Image(
                    Source(bytes, AssetFormat.Png, .5f, .5f, 2),
                    $"image {index}",
                    style: Style
                        .Empty.Set(LayoutProperties.Width, 1f)
                        .Set(LayoutProperties.Height, 1f)
                )
            );
        }

        using var renderer = new SkiaSceneRenderer();
        using var scene = ReadyScene(
            composition,
            renderer,
            new(imageCount + 2, 2, 1),
            minimumImageCount: imageCount
        );
        using var bitmap = new SKBitmap(
            imageCount + 2,
            2,
            SKColorType.Rgba8888,
            SKAlphaType.Premul
        );
        using (var canvas = new SKCanvas(bitmap))
        {
            canvas.Clear(SKColors.Transparent);
            renderer.Render(scene, canvas);
        }

        Assert.IsTrue(
            renderer.ImageCreationCount >= imageCount,
            $"Expected one native image per unique source, got {renderer.ImageCreationCount}."
        );
        Assert.IsTrue(
            renderer.LiveImageCount <= 256,
            $"Native image entry cap was exceeded: {renderer.LiveImageCount}."
        );
        Assert.IsTrue(renderer.RetainedImageBytes <= 32L * 1024 * 1024);
    }

    private static SKBitmap RenderImage(
        byte[] pixels,
        int pixelWidth,
        int pixelHeight,
        ImageColorMode colorMode,
        Color tint,
        float scale,
        bool clip = false,
        float viewportWidth = 4,
        float viewportHeight = 4,
        float rootWidth = 4,
        float rootHeight = 4,
        float imageWidth = 4,
        float imageHeight = 4
    )
    {
        var graph = new ReactiveGraph();
        using var composition = new Composition(graph, "renderer-image-pixels");
        composition.ConfigureImages(
            new ImageCache(new ImmediatePreparer(pixelWidth, pixelHeight, pixels))
        );
        var theme = new ThemeContext(composition.Root.Scope, ControlThemes.Light);
        composition.Root.Present(
            theme,
            author: Style.Empty.Set(TypographyProperties.TextColor, tint)
        );
        var imageParent = composition.Root;
        if (clip)
        {
            imageParent = composition.Child(composition.Root, "image-clip");
            imageParent.Present(
                theme,
                author: Style
                    .Empty.Set(LayoutProperties.Width, rootWidth)
                    .Set(LayoutProperties.Height, rootHeight)
                    .Set(LayoutProperties.Clip, true)
            );
        }
        composition.Mount(
            imageParent,
            theme,
            Components.Image(
                Source(PngBytes, AssetFormat.Png, .5f, .5f, 2),
                "pixel",
                style: Style
                    .Empty.Set(LayoutProperties.Width, imageWidth)
                    .Set(LayoutProperties.Height, imageHeight)
                    .Set(ImageProperties.ColorMode, colorMode)
            )
        );

        using var renderer = new SkiaSceneRenderer();
        using var scene = ReadyScene(
            composition,
            renderer,
            new(viewportWidth, viewportHeight, scale)
        );
        var bitmap = new SKBitmap(
            (int)MathF.Ceiling(viewportWidth * scale),
            (int)MathF.Ceiling(viewportHeight * scale),
            SKColorType.Rgba8888,
            SKAlphaType.Premul
        );
        using (var canvas = new SKCanvas(bitmap))
        {
            canvas.Clear(SKColors.Transparent);
            renderer.Render(scene, canvas);
        }
        return bitmap;
    }

    private static void AssertPixelNear(
        SKColor actual,
        byte red,
        byte green,
        byte blue,
        byte alpha,
        string label
    )
    {
        Assert.AreEqual(red, actual.Red, 4, $"Unexpected {label} red channel: {actual}.");
        Assert.AreEqual(green, actual.Green, 4, $"Unexpected {label} green channel: {actual}.");
        Assert.AreEqual(blue, actual.Blue, 4, $"Unexpected {label} blue channel: {actual}.");
        Assert.AreEqual(alpha, actual.Alpha, 2, $"Unexpected {label} alpha channel: {actual}.");
    }

    private static RasterImage Prepare(ImageSource source, int width, int height)
    {
        var request = new ImagePreparationRequest(
            source,
            new ImageRendition(width, height),
            ImageLoadLimits.Default
        );
        return (RasterImage)Complete(
            new SkiaImagePreparer().PrepareAsync(request, CancellationToken.None)
        );
    }

    private static void AssertLoadFailure(AssetReference asset, ImageLoadFailureKind kind)
    {
        var source = ImageSource.FromAsset(asset);
        var request = new ImagePreparationRequest(
            source,
            new ImageRendition(1, 1),
            ImageLoadLimits.Default
        );
        var failure = Assert.ThrowsExactly<ImageLoadException>(() =>
            Complete(new SkiaImagePreparer().PrepareAsync(request, CancellationToken.None))
        );
        Assert.AreEqual(kind, failure.Kind);
    }

    private static T Complete<T>(ValueTask<T> valueTask)
    {
        if (valueTask.IsCompletedSuccessfully)
            return valueTask.Result;
        return valueTask.AsTask().GetAwaiter().GetResult();
    }

    private static ImageSource Source(
        byte[] bytes,
        AssetFormat format,
        float width,
        float height,
        float density = 1
    ) =>
        ImageSource.FromAsset(
            new AssetReference(
                new AssetId("Tests", $"{Guid.NewGuid():N}.{format.ToString().ToLowerInvariant()}"),
                Convert.ToHexString(SHA256.HashData(bytes)),
                bytes.Length,
                format,
                () => new MemoryStream(bytes, writable: false),
                new(width, height, density)
            )
        );

    private static byte[] EncodePng(int width, int height)
    {
        using var bitmap = new SKBitmap(width, height, SKColorType.Rgba8888, SKAlphaType.Premul);
        bitmap.Erase(new SKColor(35, 100, 160, 255));
        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        return data?.ToArray()
            ?? throw new InvalidOperationException("Skia did not encode the test image.");
    }

    private static byte[] EncodeCheckerboardPng(int width, int height)
    {
        using var bitmap = new SKBitmap(width, height, SKColorType.Rgba8888, SKAlphaType.Premul);
        for (var y = 0; y < height; y++)
        for (var x = 0; x < width; x++)
            bitmap.SetPixel(x, y, (x + y) % 2 == 0 ? SKColors.White : SKColors.Black);
        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        return data?.ToArray()
            ?? throw new InvalidOperationException("Skia did not encode the checkerboard.");
    }

    private static byte[] EncodeJpeg(int width, int height)
    {
        using var bitmap = new SKBitmap(width, height, SKColorType.Rgba8888, SKAlphaType.Opaque);
        bitmap.SetPixel(0, 0, SKColors.Red);
        bitmap.SetPixel(1, 0, SKColors.Blue);
        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Jpeg, 100);
        return data?.ToArray()
            ?? throw new InvalidOperationException("Skia did not encode the JPEG.");
    }

    private static byte[] EncodeAlphaPatternPng()
    {
        using var bitmap = new SKBitmap(2, 2, SKColorType.Rgba8888, SKAlphaType.Premul);
        bitmap.Erase(SKColors.Transparent);
        bitmap.SetPixel(0, 0, new SKColor(255, 0, 0, 128));
        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        return data?.ToArray()
            ?? throw new InvalidOperationException("Skia did not encode the alpha pattern.");
    }

    private static byte[] AddJpegExifOrientation(byte[] jpeg, ushort orientation)
    {
        if (jpeg.Length < 2 || jpeg[0] != 0xff || jpeg[1] != 0xd8)
            throw new InvalidDataException("The test JPEG did not have an SOI marker.");

        var tiff = new byte[]
        {
            (byte)'I',
            (byte)'I',
            0x2a,
            0x00,
            0x08,
            0x00,
            0x00,
            0x00,
            0x01,
            0x00,
            0x12,
            0x01,
            0x03,
            0x00,
            0x01,
            0x00,
            0x00,
            0x00,
            (byte)orientation,
            (byte)(orientation >> 8),
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
            0x00,
        };
        var exif = new byte[6 + tiff.Length];
        "Exif\0\0"u8.CopyTo(exif);
        tiff.CopyTo(exif, 6);
        var segmentLength = checked(exif.Length + 2);
        using var output = new MemoryStream(jpeg.Length + exif.Length + 4);
        output.Write([0xff, 0xd8]);
        output.WriteByte(0xff);
        output.WriteByte(0xe1);
        output.WriteByte((byte)(segmentLength >> 8));
        output.WriteByte((byte)segmentLength);
        output.Write(exif);
        output.Write(jpeg, 2, jpeg.Length - 2);
        return output.ToArray();
    }

    private static RetainedScene ReadyScene(
        Composition composition,
        ITextShaper shaper,
        LayoutViewport viewport = default,
        int minimumImageCount = 1
    )
    {
        if (viewport.Width <= 0 || viewport.Height <= 0 || viewport.Scale <= 0)
            viewport = new(20, 20, 1);
        var deadline = Environment.TickCount64 + 5_000;
        do
        {
            var scene = SceneLayout.Project(composition, viewport, shaper);
            if (Nodes(scene.Nodes).OfType<ImageSceneNode>().Count() >= minimumImageCount)
                return scene;
            scene.Dispose();
            Thread.Sleep(1);
        } while (Environment.TickCount64 < deadline);
        Assert.Fail("The image cache did not publish a ready scene.");
        throw new InvalidOperationException();
    }

    private static IEnumerable<SceneNode> Nodes(IEnumerable<SceneNode> nodes)
    {
        foreach (var node in nodes)
        {
            yield return node;
            var children = node switch
            {
                ClipSceneNode clip => clip.Children,
                OpacitySceneNode opacity => opacity.Children,
                _ => null,
            };
            if (children is not null)
                foreach (var child in Nodes(children))
                    yield return child;
        }
    }

    private sealed class ImmediatePreparer : IImagePreparer
    {
        private readonly int _width;
        private readonly int _height;
        private readonly byte[] _pixels;

        public ImmediatePreparer(int width = 1, int height = 1, byte[]? pixels = null)
        {
            _width = width;
            _height = height;
            _pixels = pixels ?? [255, 0, 0, 255];
        }

        public ValueTask<PreparedImage> PrepareAsync(
            ImagePreparationRequest request,
            CancellationToken cancellationToken
        ) => ValueTask.FromResult<PreparedImage>(new RasterImage(_width, _height, _pixels));
    }
}
