<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Lucent.Reactive.R3/Lucent.Reactive.R3.csproj" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
</Project>
